# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requireAdminNotify: true # VG Rules Tweak
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 6h # VG-RoleTime
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 6h # animed-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 20h # VG-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 40h # VG-RoleTime
    - !type:AgeRequirement # VG-MRP
      requiredAge: 21
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: true # VG-MRP
  antagAdvantage: 5 # VG-MRP: Heads can be antags
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics

  special:
  - !type:AddSkillGroupSpecial 
    group: MedicalSkills #VG-Tweak SkillsIntegration
#  - !type:AddImplantSpecial # VG-MRP
#    implants: [ MindShieldImplant ] # VG-MRP
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: CMOGear
  # equipment: # ADT tweak
 #id: CMOPDA  # ADT Tweak
    # ears: ClothingHeadsetCMO # ADT tweak
#    belt: ClothingBeltMedicalFilled ADT tweak
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
- type: chameleonOutfit
  id: ChiefMedicalOfficerChameleonOutfit
  job: ChiefMedicalOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
