using System.Linq;
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Client._VG.Sponsors;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Shared.Preferences.Loadouts.Effects;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutGroupContainer : BoxContainer
{
    private const string ClosedGroupMark = "▶";
    private const string OpenedGroupMark = "▼";

    private Dictionary<string, bool> _openedGroups = new();

    private readonly LoadoutGroupPrototype _groupProto;
    private readonly SponsorsManager _sponsorsManager;

    public event Action<ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    public LoadoutGroupContainer(HumanoidCharacterProfile profile, RoleLoadout loadout, LoadoutGroupPrototype groupProto, ICommonSession session, IDependencyCollection collection, bool isSponsor)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _groupProto = groupProto;

        _sponsorsManager = collection.Resolve<SponsorsManager>();

        RefreshLoadouts(profile, loadout, session, collection, isSponsor);
    }

    public void RefreshLoadouts(HumanoidCharacterProfile profile, RoleLoadout loadout, ICommonSession session, IDependencyCollection collection, bool isSponsor)
    {
        var protoMan = collection.Resolve<IPrototypeManager>();
        var loadoutSystem = collection.Resolve<IEntityManager>().System<LoadoutSystem>();
        RestrictionsContainer.RemoveAllChildren();

        if (_groupProto.MinLimit > 0)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-min-limit", ("count", _groupProto.MinLimit)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        if (_groupProto.MaxLimit > 0)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-max-limit", ("count", _groupProto.MaxLimit)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        if (protoMan.Resolve(loadout.Role, out var roleProto) && roleProto.Points != null && loadout.Points != null)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-points-limit", ("count", loadout.Points.Value), ("max", roleProto.Points.Value)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        LoadoutsContainer.RemoveAllChildren();

        IEnumerable<ProtoId<LoadoutPrototype>> groupLoadouts = _groupProto.Loadouts;

        if (_groupProto.ID == "Inventory" || _groupProto.ID == "SponsorInventory")
        {
            List<string> allowedItems = new();
            
            if (_sponsorsManager.TryGetInfo(out var sponsorInfo))
            {
                // Add custom loadouts
                if (sponsorInfo.CustomLoadouts != null)
                    allowedItems.AddRange(sponsorInfo.CustomLoadouts);
                
                // Add allowed markings (for backwards compatibility)
                if (sponsorInfo.AllowedMarkings != null)
                    allowedItems.AddRange(sponsorInfo.AllowedMarkings);
            }
            
            // Also include loadouts that have sponsorTarget matching the player
            var allLoadouts = protoMan.EnumeratePrototypes<LoadoutPrototype>();
            if (_sponsorsManager.TryGetInfo(out var sponsorData))
            {
                foreach (var loadoutProto in allLoadouts)
                {
                    // Check for sponsorTarget field in the prototype's data fields
                    var target = GetSponsorTargetFromLoadout(loadoutProto);
                    if (!string.IsNullOrEmpty(target) && sponsorData.CharacterName == target)
                    {
                        if (!allowedItems.Contains(loadoutProto.ID))
                            allowedItems.Add(loadoutProto.ID);
                    }
                }
            }

            groupLoadouts = protoMan.EnumeratePrototypes<LoadoutPrototype>()
                .Where(p => allowedItems.Contains(p.ID))
                .Select(p => (ProtoId<LoadoutPrototype>)p.ID)
                .ToList();
        }

        var validProtos = groupLoadouts.Select(id => protoMan.Index(id));

        var groups = validProtos
            .GroupBy(p => string.IsNullOrEmpty(p.GroupBy) ? p.ID : p.GroupBy)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (var kvp in groups)
        {
            var protos = kvp.Value;

            if (protos.Count > 1)
            {
                var uiElements = protos
                    .Select(proto =>
                    {
                        var elem = CreateLoadoutUI(proto, profile, loadout, session, collection, loadoutSystem);
                        elem.HorizontalExpand = true;
                        return elem;
                    })
                    .ToList();

                var firstElement = uiElements.FirstOrDefault(e => e.Select.Pressed) ?? uiElements[0];
                var otherElements = uiElements.Where(e => !ReferenceEquals(e, firstElement)).ToList();

                firstElement.HorizontalExpand = true;
                var subContainer = new SubLoadoutContainer()
                {
                    Visible = _openedGroups.GetValueOrDefault(kvp.Key, false)
                };
                var toggle = CreateToggleButton(kvp, firstElement, subContainer);

                LoadoutsContainer.AddChild(firstElement);
                LoadoutsContainer.AddChild(subContainer);

                var subList = subContainer.Grid;
                foreach (var proto in otherElements)
                {
                    subList.AddChild(proto);
                }
                var itemName = firstElement.Text ?? "";
                UpdateSubGroupSelectedInfo(firstElement, itemName, subList);
            }
            else
            {
                LoadoutsContainer.AddChild(
                    CreateLoadoutUI(protos[0], profile, loadout, session, collection, loadoutSystem)
                );
            }
        }
    }

    private string? GetSponsorTargetFromLoadout(LoadoutPrototype proto)
    {
        // Try to get sponsorTarget from the prototype's abstract data
        // This is a workaround since TryGet doesn't exist on LoadoutPrototype
        // You may need to add a property to LoadoutPrototype or use reflection
        // For now, return null and handle via CustomLoadouts list
        
        // Alternative approach: check if the loadout ID contains the username pattern
        // Or better: store the mapping in the JSON file directly
        
        return null;
    }

    private ToggleLoadoutButton CreateToggleButton(KeyValuePair<string, List<LoadoutPrototype>> kvp, LoadoutContainer firstElement, SubLoadoutContainer subContainer)
    {
        var toggle = new ToggleLoadoutButton
        {
            Text = ClosedGroupMark
        };

        toggle.Text = subContainer.Visible ? OpenedGroupMark : ClosedGroupMark;
        toggle.Pressed = subContainer.Visible;

        toggle.OnPressed += _ =>
        {
            var willOpen = !subContainer.Visible;
            subContainer.Visible = willOpen;
            toggle.Text = willOpen ? OpenedGroupMark : ClosedGroupMark;
            toggle.Pressed = willOpen;
            _openedGroups[kvp.Key] = willOpen;
        };

        firstElement.AddChild(toggle);
        toggle.SetPositionFirst();
        return toggle;
    }

    private void UpdateSubGroupSelectedInfo(LoadoutContainer loadout, string itemName, BoxContainer subList)
    {
        var countSubSelected = subList.Children
            .OfType<LoadoutContainer>()
            .Count(c => c.Select.Pressed);

        if (countSubSelected > 0)
        {
            loadout.Text = Loc.GetString("loadouts-count-items-in-group", ("item", itemName), ("count", countSubSelected));
        }
    }

    private LoadoutContainer CreateLoadoutUI(LoadoutPrototype proto, HumanoidCharacterProfile profile, RoleLoadout loadout, ICommonSession session, IDependencyCollection collection, LoadoutSystem loadoutSystem)
{
    var selected = loadout.SelectedLoadouts[_groupProto.ID];
    var pressed = selected.Any(e => e.Prototype == proto.ID);

    if (proto.SponsorOnly)
    {
        if (!_sponsorsManager.TryGetInfo(out var sponsorInfo))
        {
            var sponsorCont = new LoadoutContainer(proto, true, FormattedMessage.FromUnformatted("Sponsor only"));
            sponsorCont.Text = loadoutSystem.GetName(proto);
            sponsorCont.Select.Pressed = false;
            sponsorCont.Select.OnPressed += args =>
            {
                if (args.Button.Pressed)
                    OnLoadoutPressed?.Invoke(proto.ID);
                else
                    OnLoadoutUnpressed?.Invoke(proto.ID);
            };
            return sponsorCont;
        }

        var isAllowed = false;
        
        // Check custom loadouts
        if (sponsorInfo.CustomLoadouts != null && sponsorInfo.CustomLoadouts.Contains(proto.ID))
            isAllowed = true;
        
        // Check allowed markings (backwards compatibility)
        if (sponsorInfo.AllowedMarkings != null && sponsorInfo.AllowedMarkings.Contains(proto.ID))
            isAllowed = true;

        if (!isAllowed)
        {
            var notAllowedCont = new LoadoutContainer(proto, true, FormattedMessage.FromUnformatted("Not available"));
            notAllowedCont.Text = loadoutSystem.GetName(proto);
            notAllowedCont.Select.Pressed = false;
            notAllowedCont.Select.OnPressed += args =>
            {
                if (args.Button.Pressed)
                    OnLoadoutPressed?.Invoke(proto.ID);
                else
                    OnLoadoutUnpressed?.Invoke(proto.ID);
            };
            return notAllowedCont;
        }
    }

    var enabled = loadout.IsValid(profile, session, proto.ID, collection, out var reason);
    var cont = new LoadoutContainer(proto, !enabled, reason);
    cont.Text = loadoutSystem.GetName(proto);
    cont.Select.Pressed = pressed;

    cont.Select.OnPressed += args =>
    {
        if (args.Button.Pressed)
            OnLoadoutPressed?.Invoke(proto.ID);
        else
            OnLoadoutUnpressed?.Invoke(proto.ID);
    };

    return cont;
}
}