using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.MiningShop;

[GenerateTypedNameReferences]
public sealed partial class MiningShopEntry : Control
{
    public MiningShopEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetBackgroundColor(Color color, Color borderColor)
    {
        if (BackgroundPanel.PanelOverride is StyleBoxFlat style)
        {
            style.BackgroundColor = color;
            style.BorderColor = borderColor;
        }
    }

    public void SetDisabled(bool disabled)
    {
        if (BackgroundPanel.PanelOverride is StyleBoxFlat style)
        {
            style.BackgroundColor = disabled ? Color.FromHex("#333333") : Color.FromHex("#162031");
        }
    }
}