using Content.Shared._VG;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._VG.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DeltaTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public DeltaTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DisableFiltersCheckBox.OnToggled += OnCheckBoxToggled;
        DisableFiltersCheckBox.Pressed = _cfg.GetCVar(VGCCVars.VisionFiltersEnabled);

        DisableBloomCheckBox.OnToggled += OnCheckBoxToggled;
        DisableBloomCheckBox.Pressed = _cfg.GetCVar(VGCCVars.BloomEnabled);

        NewCharacterWindowCheckBox.OnToggled += OnCheckBoxToggled;
        NewCharacterWindowCheckBox.Pressed = _cfg.GetCVar(VGCCVars.CharacterSetupNewWindowEnabled);

        ApplyButton.OnPressed += OnApplyButtonPressed;
        UpdateApplyButton();
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateApplyButton();
    }

    private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
    {
        _cfg.SetCVar(VGCCVars.VisionFiltersEnabled, DisableFiltersCheckBox.Pressed);
        _cfg.SetCVar(VGCCVars.BloomEnabled, DisableBloomCheckBox.Pressed);
        _cfg.SetCVar(VGCCVars.CharacterSetupNewWindowEnabled, NewCharacterWindowCheckBox.Pressed);

        _cfg.SaveToFile();
        UpdateApplyButton();
    }

    private void UpdateApplyButton()
    {
        var isVisionSame = DisableFiltersCheckBox.Pressed == _cfg.GetCVar(VGCCVars.VisionFiltersEnabled);
        var isBloomSame = DisableBloomCheckBox.Pressed == _cfg.GetCVar(VGCCVars.BloomEnabled);
        var isNewCharWindowSame = NewCharacterWindowCheckBox.Pressed == _cfg.GetCVar(VGCCVars.CharacterSetupNewWindowEnabled);

        ApplyButton.Disabled = isVisionSame && isBloomSame && isNewCharWindowSame;
    }
}