using Content.Shared._VG;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._VG.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DeltaTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public DeltaTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Vision filters
        DisableFiltersCheckBox.OnToggled += OnCheckBoxToggled;
        DisableFiltersCheckBox.Pressed = _cfg.GetCVar(VGCCVars.NoVisionFilters);

        // Bloom post-processing
        DisableBloomCheckBox.OnToggled += OnCheckBoxToggled;
        DisableBloomCheckBox.Pressed = _cfg.GetCVar(VGCCVars.NoBloomPostProcessing);

        // New character window
        NewCharacterWindowCheckBox.OnToggled += OnCheckBoxToggled;
        NewCharacterWindowCheckBox.Pressed = _cfg.GetCVar(VGCCVars.CharacterSetupNewWindowEnabled);

        ApplyButton.OnPressed += OnApplyButtonPressed;
        UpdateApplyButton();
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateApplyButton();
    }

    private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
    {
        _cfg.SetCVar(VGCCVars.NoVisionFilters, DisableFiltersCheckBox.Pressed);
        _cfg.SetCVar(VGCCVars.NoBloomPostProcessing, DisableBloomCheckBox.Pressed);
        _cfg.SetCVar(VGCCVars.CharacterSetupNewWindowEnabled, NewCharacterWindowCheckBox.Pressed);

        _cfg.SaveToFile();
        UpdateApplyButton();
    }

    private void UpdateApplyButton()
    {
        var isNoVisionFiltersSame = DisableFiltersCheckBox.Pressed == _cfg.GetCVar(VGCCVars.NoVisionFilters);
        var isNoBloomSame = DisableBloomCheckBox.Pressed == _cfg.GetCVar(VGCCVars.NoBloomPostProcessing);
        var isNewCharWindowSame = NewCharacterWindowCheckBox.Pressed == _cfg.GetCVar(VGCCVars.CharacterSetupNewWindowEnabled);

        ApplyButton.Disabled = isNoVisionFiltersSame && isNoBloomSame && isNewCharWindowSame;
    }
}