using System.Linq;
using Content.Client._VG.Sponsors;
using Content.Client.ADT.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._VG.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class VGLayerMarkingItem : BoxContainer
{
    private readonly VGLayerMarkingPicker _parent;
    private readonly MarkingPrototype _prototype;
    private readonly Marking _marking;
    private readonly Color _skinColor;
    private readonly Color _eyeColor;

    private List<LegacyColorSelectorSliders>? _colorSliders;
    private bool _isSettingInitialState;

    public MarkingPrototype Prototype => _prototype;
    public Marking Marking => _marking;

    public VGLayerMarkingItem(VGLayerMarkingPicker parent, MarkingPrototype prototype, Marking marking, Color skinColor, Color eyeColor)
    {
        RobustXamlLoader.Load(this);
        _parent = parent;
        _prototype = prototype;
        _marking = marking;
        _skinColor = skinColor;
        _eyeColor = eyeColor;

        var spriteSys = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
        if (prototype.Sprites.Count > 0)
            MarkingTexture.Texture = spriteSys.Frame0(prototype.Sprites[0]);

        string baseName = Loc.GetString($"marking-{prototype.ID}");
        SelectButton.Text = baseName;

        // Обработка спонсорских маркеров
        if (prototype.SponsorOnly)
        {
            var sponsorManager = IoCManager.Resolve<SponsorsManager>();
            bool hasSponsor = sponsorManager.TryGetInfo(out var info) && info.AllowedMarkings.Contains(prototype.ID);
            SelectButton.Text = baseName + " (СПОНСОР)";
            if (!hasSponsor)
            {
                SelectButton.Disabled = true;
                ColorsButton.Disabled = true;
            }
        }

        SelectButton.OnToggled += OnSelectToggled;
        ColorsButton.OnToggled += OnColorsToggled;

        _isSettingInitialState = true;
        bool isSelected = _parent.GetMarkingSet()?.Markings.GetValueOrDefault(_parent.GetCategory())?.Any(m => m.MarkingId == prototype.ID) ?? false;
        SelectButton.Pressed = isSelected;
        ColorsButton.Visible = isSelected && marking.MarkingColors.Count > 0 && !prototype.ForcedColoring;
        _isSettingInitialState = false;
    }

    private void OnSelectToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_isSettingInitialState) return;

        bool success = _parent.OnMarkingToggled(this, args.Pressed);
        if (!success)
        {
            SelectButton.Pressed = !args.Pressed;
            return;
        }
        ColorsButton.Visible = args.Pressed && _marking.MarkingColors.Count > 0 && !_prototype.ForcedColoring;
        if (!args.Pressed)
            ColorsButton.Pressed = false;
    }

    private void OnColorsToggled(BaseButton.ButtonToggledEventArgs args)
    {
        ColorsContainer.Visible = args.Pressed;
        if (args.Pressed && _colorSliders == null)
            BuildColorSliders();
    }

    private void BuildColorSliders()
    {
        _colorSliders = new();
        var stateNames = GetMarkingStateNames(_prototype);
        for (int i = 0; i < _prototype.Sprites.Count; i++)
        {
            var container = new BoxContainer { Orientation = LayoutOrientation.Vertical };
            container.AddChild(new Label { Text = stateNames[i] });
            var slider = new LegacyColorSelectorSliders();
            slider.Color = _marking.MarkingColors[i];
            int idx = i;
            slider.OnColorChanged += color =>
            {
                _parent.OnMarkingColorChanged(this, idx, color);
                _marking.SetColor(idx, color);
            };
            container.AddChild(slider);
            ColorsContainer.AddChild(container);
            _colorSliders.Add(slider);
        }
    }

    private List<string> GetMarkingStateNames(MarkingPrototype marking)
    {
        var list = new List<string>();
        foreach (var spec in marking.Sprites)
        {
            switch (spec)
            {
                case SpriteSpecifier.Rsi rsi:
                    list.Add(Loc.GetString($"marking-{marking.ID}-{rsi.RsiState}"));
                    break;
                case SpriteSpecifier.Texture tex:
                    list.Add(Loc.GetString($"marking-{marking.ID}-{tex.TexturePath.Filename}"));
                    break;
            }
        }
        return list;
    }
}