using System.Linq;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VG.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class VGLayerMarkingOrderer : BoxContainer
{
    private readonly VGLayerMarkingPicker _parent;
    private readonly MarkingCategories _category;
    private readonly List<Marking> _markings;

    public VGLayerMarkingOrderer(VGLayerMarkingPicker parent, MarkingCategories category, List<Marking> markings)
    {
        RobustXamlLoader.Load(this);
        _parent = parent;
        _category = category;
        _markings = markings;
        BuildUI();
    }

    private void BuildUI()
    {
        ItemsContainer.RemoveAllChildren();
        for (int i = 0; i < _markings.Count; i++)
        {
            var marking = _markings[i];
            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(2) };
            var label = new Label { Text = Loc.GetString($"marking-{marking.MarkingId}"), HorizontalExpand = true };
            row.AddChild(label);
            var upButton = new Button { Text = "▲", MinWidth = 30 };
            var downButton = new Button { Text = "▼", MinWidth = 30 };
            int idx = i;
            upButton.OnPressed += _ => MoveMarking(idx, -1);
            downButton.OnPressed += _ => MoveMarking(idx, 1);
            row.AddChild(upButton);
            row.AddChild(downButton);
            ItemsContainer.AddChild(row);
        }
    }

    private void MoveMarking(int index, int delta)
    {
        int newIndex = index + delta;
        if (newIndex < 0 || newIndex >= _markings.Count) return;
        var temp = _markings[index];
        _markings[index] = _markings[newIndex];
        _markings[newIndex] = temp;
        BuildUI();
        _parent.OnOrderChanged();
    }
}