using System.Linq;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VG.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class VGLayerMarkingPicker : BoxContainer
{
    private readonly VGMarkingPicker _parent;
    private readonly MarkingSet? _markingSet;
    private readonly MarkingCategories _category;
    private readonly Dictionary<string, MarkingPrototype> _availableMarkings;
    private readonly string _species;
    private readonly Sex _sex;
    private readonly Color _skinColor;
    private readonly Color _eyeColor;

    private readonly List<VGLayerMarkingItem> _items = new();
    private bool _reorderMode;

    public VGLayerMarkingPicker(
        VGMarkingPicker parent,
        MarkingSet? markingSet,
        MarkingCategories category,
        Dictionary<string, MarkingPrototype> availableMarkings,
        string species,
        Sex sex,
        Color skinColor,
        Color eyeColor)
    {
        RobustXamlLoader.Load(this);
        _parent = parent;
        _markingSet = markingSet;
        _category = category;
        _availableMarkings = availableMarkings;
        _species = species;
        _sex = sex;
        _skinColor = skinColor;
        _eyeColor = eyeColor;

        SearchBar.OnTextChanged += _ => FilterItems();
        ReorderButton.OnToggled += OnReorderToggled;

        BuildItems();
        UpdateCounts();
    }

    private void BuildItems()
    {
        ItemsContainer.RemoveAllChildren();
        _items.Clear();

        List<Marking> selectedMarkings = new();
        if (_markingSet != null && _markingSet.Markings.TryGetValue(_category, out var markings))
            selectedMarkings = markings.ToList();

        foreach (var (id, proto) in _availableMarkings)
        {
            var existing = selectedMarkings.FirstOrDefault(m => m.MarkingId == id);
            var marking = existing ?? new Marking(id, proto.Sprites.Count);
            var item = new VGLayerMarkingItem(this, proto, marking, _skinColor, _eyeColor);
            ItemsContainer.AddChild(item);
            _items.Add(item);
        }

        _items.Sort((a, b) => string.Compare(a.Prototype.ID, b.Prototype.ID, StringComparison.Ordinal));
        ItemsContainer.RemoveAllChildren();
        foreach (var item in _items)
            ItemsContainer.AddChild(item);

        UpdateItemStates();
    }

    private void FilterItems()
    {
        string filter = SearchBar.Text.Trim().ToLowerInvariant();
        foreach (var item in _items)
        {
            bool match = string.IsNullOrEmpty(filter) ||
                         item.Prototype.ID.ToLowerInvariant().Contains(filter) ||
                         Loc.GetString($"marking-{item.Prototype.ID}").ToLowerInvariant().Contains(filter);
            item.Visible = match;
        }
    }

    private void UpdateCounts()
    {
        int selectedCount = _markingSet?.Markings.GetValueOrDefault(_category)?.Count ?? 0;
        int maxPoints = _markingSet?.PointsLeft(_category) ?? -1;
        if (maxPoints >= 0)
            MarkingsStatus.Text = Loc.GetString("marking-points-remaining", ("points", maxPoints));
        else
            MarkingsStatus.Text = $"{selectedCount} selected";
    }

    internal bool OnMarkingToggled(VGLayerMarkingItem item, bool isNowSelected)
    {
        if (_markingSet == null) return false;

        if (isNowSelected)
        {
            int pointsLeft = _markingSet.PointsLeft(_category);
            if (pointsLeft != -1 && pointsLeft <= 0 && !item.Prototype.ForcedColoring)
                return false;

            var colors = MarkingColoring.GetMarkingLayerColors(item.Prototype, _skinColor, _eyeColor, _markingSet);
            var newMarking = new Marking(item.Prototype.ID, colors);
            _markingSet.AddBack(_category, newMarking);
            _parent.RaiseMarkingAdded(_markingSet);
        }
        else
        {
            _markingSet.Remove(_category, item.Prototype.ID);
            _parent.RaiseMarkingRemoved(_markingSet);
        }
        UpdateCounts();
        UpdateItemStates();
        return true;
    }

    internal void OnMarkingColorChanged(VGLayerMarkingItem item, int colorIndex, Color newColor)
    {
        if (_markingSet == null) return;
        var marking = item.Marking;
        marking.SetColor(colorIndex, newColor);
        if (_markingSet.Markings.TryGetValue(_category, out var list))
        {
            int idx = list.FindIndex(m => m.MarkingId == marking.MarkingId);
            if (idx != -1)
            {
                list[idx] = marking;
                _parent.RaiseMarkingColorChange(_markingSet);
            }
        }
    }

    private void OnReorderToggled(BaseButton.ButtonToggledEventArgs args)
    {
        _reorderMode = args.Pressed;
        SelectionScroll.Visible = !_reorderMode;
        OrderingContainer.Visible = _reorderMode;
        if (_reorderMode)
            BuildOrderingUI();
    }

    private void BuildOrderingUI()
    {
        OrderingContainer.RemoveAllChildren();
        if (_markingSet == null) return;
        if (!_markingSet.Markings.TryGetValue(_category, out var markings)) return;
        var orderer = new VGLayerMarkingOrderer(this, _category, markings);
        OrderingContainer.AddChild(orderer);
    }

    internal void OnOrderChanged()
    {
        if (_markingSet != null)
            _parent.RaiseMarkingRankChange(_markingSet);
        UpdateCounts();
        UpdateItemStates();
    }

    internal MarkingSet? GetMarkingSet() => _markingSet;
    internal MarkingCategories GetCategory() => _category;

    internal void UpdateItemStates()
    {
        if (_markingSet == null) return;
        var selectedIds = _markingSet.Markings.GetValueOrDefault(_category)?.Select(m => m.MarkingId).ToHashSet() ?? new HashSet<string>();
        foreach (var item in _items)
        {
            bool isSelected = selectedIds.Contains(item.Prototype.ID);
            if (item.SelectButton.Pressed != isSelected)
                item.SelectButton.Pressed = isSelected;

            bool showColors = isSelected && item.Marking.MarkingColors.Count > 0 && !item.Prototype.ForcedColoring;
            if (item.ColorsButton.Visible != showColors)
                item.ColorsButton.Visible = showColors;

            if (!isSelected && item.ColorsButton.Pressed)
            {
                item.ColorsButton.Pressed = false;
                item.ColorsContainer.Visible = false;
            }
        }
        UpdateButtonsEnabled();
    }

    private void UpdateButtonsEnabled()
    {
        if (_markingSet == null) return;
        int pointsLeft = _markingSet.PointsLeft(_category);
        bool canAddMore = pointsLeft == -1 || pointsLeft > 0;
        foreach (var item in _items)
        {
            bool isSelected = _markingSet.Markings.GetValueOrDefault(_category)?.Any(m => m.MarkingId == item.Prototype.ID) ?? false;
            item.SelectButton.Disabled = !canAddMore && !isSelected;
        }
    }
}