using System.Linq;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VG.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class VGMarkingPicker : Control
{
    private MarkingSet? _markingSet;
    private string _species = string.Empty;
    private Sex _sex = Sex.Unsexed;
    private Color _skinColor;
    private Color _eyeColor;

    public HashSet<MarkingCategories> ExcludeCategories { get; set; } = new();

    public event Action<MarkingSet>? OnMarkingAdded;
    public event Action<MarkingSet>? OnMarkingRemoved;
    public event Action<MarkingSet>? OnMarkingColorChange;
    public event Action<MarkingSet>? OnMarkingRankChange;

    public VGMarkingPicker()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(MarkingSet markingSet, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        _markingSet = markingSet;
        _species = species;
        _sex = sex;
        _skinColor = skinColor;
        _eyeColor = eyeColor;

        foreach (var child in OrganTabs.Children.ToList())
        {
            OrganTabs.RemoveChild(child);
            child.Dispose();
        }
        OrganTabs.RemoveAllChildren();
    
        BuildTabs();

        if (OrganTabs.ChildCount > 0)
            OrganTabs.CurrentTab = 0;
    }   

    private void BuildTabs()
    {
        foreach (var child in OrganTabs.Children.ToList())
        {
            OrganTabs.RemoveChild(child);
            child.Dispose();
        }
        OrganTabs.RemoveAllChildren();

        var organCategories = new Dictionary<string, List<MarkingCategories>>
        {
            ["Head"] = new()
            {
                MarkingCategories.Hair,
                MarkingCategories.FacialHair,
                MarkingCategories.Head,
                MarkingCategories.HeadTop,
                MarkingCategories.HeadSide,
                MarkingCategories.Snout,
                MarkingCategories.SnoutCover,
                MarkingCategories.SnoutOverlay
            },
            ["Chest"] = new()
            {
                MarkingCategories.Chest,
                MarkingCategories.UndergarmentTop,
                MarkingCategories.UndergarmentBottom
            },
            ["Arms"] = new() { MarkingCategories.Arms },
            ["Legs"] = new() { MarkingCategories.Legs },
            ["Tail"] = new() { MarkingCategories.Tail },
            ["Overlay"] = new()
            {
                MarkingCategories.Overlay,
                MarkingCategories.OverlayBandage,
                MarkingCategories.Special
            }
        };

        foreach (var (organName, categories) in organCategories)
        {
            var filtered = categories.Where(c => !ExcludeCategories.Contains(c)).ToList();
            if (filtered.Count == 0)
                continue;

            bool hasAny = false;
            foreach (var cat in filtered)
            {
                if (GetAvailableMarkingsForCategory(cat).Count > 0)
                {
                    hasAny = true;
                    break;
                }
            }
            if (!hasAny)
                continue;

            var organTab = new VGOrganTab(this, organName, filtered, _markingSet, _species, _sex, _skinColor, _eyeColor);
            OrganTabs.AddChild(organTab);
            OrganTabs.SetTabTitle(OrganTabs.ChildCount - 1, Loc.GetString($"vg-markings-organ-{organName.ToLower()}"));
        }

        OrganTabs.TabsVisible = OrganTabs.ChildCount > 1;
    }

    public void ForceRebuild()
    {
        if (_markingSet == null) return;
        SetData(_markingSet, _species, _sex, _skinColor, _eyeColor);
    }

    internal Dictionary<string, MarkingPrototype> GetAvailableMarkingsForCategory(MarkingCategories category)
    {
        var manager = IoCManager.Resolve<MarkingManager>();
        return manager.MarkingsByCategoryAndSpeciesAndSex(category, _species, _sex)
            .ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
    }

    internal MarkingSet? GetMarkingSet() => _markingSet;

    internal void RaiseMarkingAdded(MarkingSet set) => OnMarkingAdded?.Invoke(set);
    internal void RaiseMarkingRemoved(MarkingSet set) => OnMarkingRemoved?.Invoke(set);
    internal void RaiseMarkingColorChange(MarkingSet set) => OnMarkingColorChange?.Invoke(set);
    internal void RaiseMarkingRankChange(MarkingSet set) => OnMarkingRankChange?.Invoke(set);
}