using System.Linq;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VG.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class VGOrganTab : Control
{
    private readonly VGMarkingPicker _parent;
    private readonly string _organName;
    private readonly List<MarkingCategories> _categories;
    private readonly MarkingSet? _markingSet;
    private readonly string _species;
    private readonly Sex _sex;
    private readonly Color _skinColor;
    private readonly Color _eyeColor;

    public VGOrganTab(
        VGMarkingPicker parent,
        string organName,
        List<MarkingCategories> categories,
        MarkingSet? markingSet,
        string species,
        Sex sex,
        Color skinColor,
        Color eyeColor)
    {
        RobustXamlLoader.Load(this);
        _parent = parent;
        _organName = organName;
        _categories = categories;
        _markingSet = markingSet;
        _species = species;
        _sex = sex;
        _skinColor = skinColor;
        _eyeColor = eyeColor;
        BuildLayerTabs();
    }

    private void BuildLayerTabs()
    {
        // Уничтожаем все старые дочерние элементы (включая LayerTabs и прямой контент)
        foreach (var child in Children.ToList())
        {
            RemoveChild(child);
            child.Dispose();
        }
    
        var categoriesWithMarkings = _categories
            .Where(cat => _parent.GetAvailableMarkingsForCategory(cat).Count > 0)
            .ToList();

        if (categoriesWithMarkings.Count == 1)
        {
            // Вместо использования LayerTabs, добавляем слой напрямую
            var category = categoriesWithMarkings[0];
            var available = _parent.GetAvailableMarkingsForCategory(category);
            var layerPicker = new VGLayerMarkingPicker(_parent, _markingSet, category, available, _species, _sex, _skinColor, _eyeColor);
            AddChild(layerPicker);
            LayerTabs.Visible = false;
        }
        else
        {
            // Используем TabContainer
            AddChild(LayerTabs);
            LayerTabs.Visible = true;
            foreach (var category in categoriesWithMarkings)
            {
                var available = _parent.GetAvailableMarkingsForCategory(category);
                var layerPicker = new VGLayerMarkingPicker(_parent, _markingSet, category, available, _species, _sex, _skinColor, _eyeColor);
                LayerTabs.AddChild(layerPicker);
                string title = Loc.GetString($"markings-category-{category}");
                LayerTabs.SetTabTitle(LayerTabs.ChildCount - 1, title);
            }
            if (LayerTabs.ChildCount > 0)
                LayerTabs.CurrentTab = 0;
            LayerTabs.TabsVisible = LayerTabs.ChildCount > 1;
        }
    }
}