- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requireAdminNotify: true # VG Rules Tweak
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 10h # Corvax-RoleTime
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 6h # VG-RoleTime
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 20h # VG-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 40h # VG-RoleTime
#       ADT tweak start
#    - !type:SpeciesRequirement
#      inverted: true
#      species:
#      - Vox
#       ADT tweak end
    - !type:AgeRequirement # VG-MRP
      requiredAge: 21
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  canBeAntag: true # VG-MRP
  antagAdvantage: 5 # VG-MRP: Heads can be antags
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
#  - !type:AddImplantSpecial # VG-MRP
#    implants: [ MindShieldImplant ] # VG-MRP
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    # eyes: ClothingEyesGlassesMeson #ADT-Tweak - заменено на выбор
    # ears: ClothingHeadsetCE # ADT tweak
# ADT-Tweak-start по причине того, что ассистент и остальной состав ИО спавнится с двумя поясами, если их выбрать в лоудауте
    # belt: ClothingBeltUtilityEngineering
# ADT-Tweak-end
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout

#ADT tweak start
- type: chameleonOutfit
  id: ChiefEngineerChameleonOutfit
  job: ChiefEngineer
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
#ADT tweak end