using System.Linq;
using System.Numerics;
using Content.Client.Interaction;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class CategoryMarkingOrderer : BoxContainer
{
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly MarkingCategories _category;
    private readonly MarkingsViewModel _model;
    private readonly DragDropHelper<CategoryMarkingDragged> _dragDropHelper;
    private readonly List<CategoryDragDropBeacon> _beacons = new();
    private CategoryDragDropBeacon? _dragTarget;
    private CategoryMarkingItem? _dragItem;
    private CategoryMarkingItemContainer? _dragContainer;

    public CategoryMarkingOrderer(MarkingsViewModel model, MarkingCategories category)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _model = model;
        _category = category;
        _dragDropHelper = new DragDropHelper<CategoryMarkingDragged>(OnBeginDrag, OnContinueDrag, OnEndDrag);

        UpdateItems();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _model.MarkingsReset += UpdateItems;
        _model.MarkingsChanged += OnMarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _model.MarkingsReset -= UpdateItems;
        _model.MarkingsChanged -= OnMarkingsChanged;
    }

    private void OnMarkingsChanged(MarkingCategories category)
    {
        if (_category != category) return;
        UpdateItems();
    }

    private void UpdateItems()
    {
        Items.RemoveAllChildren();
        _beacons.Clear();

        if (_model.SelectedMarkings(_category) is not { } markings)
            return;

        for (var idx = 0; idx < markings.Count; idx++)
        {
            var marking = markings[idx];

            if (!_prototype.TryIndex<MarkingPrototype>(marking.MarkingId, out var proto))
                continue;

            var container = new CategoryMarkingItemContainer();
            container.Margin = new Thickness(4);

            var item = new CategoryMarkingItem(_model, _category, proto, false);
            item.DefaultCursorShape = CursorShape.Hand;
            item.Pressed += (args, control) => OnItemPressed(args, control, container);
            item.Unpressed += OnItemUnpressed;

            container.AddChild(item);

            var before = new CategoryDragDropBeacon(CandidatePosition.Before, idx);
            var after = new CategoryDragDropBeacon(CandidatePosition.After, idx);
            _beacons.Add(before);
            _beacons.Add(after);

            Items.AddChild(before);
            Items.AddChild(container);
            Items.AddChild(after);
        }
    }

    private void OnItemPressed(GUIBoundKeyEventArgs args, CategoryMarkingItem control, CategoryMarkingItemContainer container)
    {
        _dragDropHelper.MouseDown(new(control, container));
    }

    private void OnItemUnpressed(GUIBoundKeyEventArgs args, CategoryMarkingItem control)
    {
        _dragDropHelper.EndDrag();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _dragDropHelper.Update(args.DeltaSeconds);
    }

    private bool OnBeginDrag()
    {
        var dragged = _dragDropHelper.Dragged;
        _dragItem = dragged.Item;
        _dragContainer = dragged.Container;
        if (_dragItem == null || _dragContainer == null)
            return false;

        _dragContainer.Visible = false;
        _dragItem.Orphan();
        _dragItem.DefaultCursorShape = CursorShape.Move;
        _uiManager.PopupRoot.AddChild(_dragItem);
        LayoutContainer.SetPosition(_dragItem, _uiManager.MousePositionScaled.Position - new Vector2(32, 32));
        return true;
    }

    private bool OnContinueDrag(float frameTime)
    {
        if (_dragItem == null)
            return false;

        LayoutContainer.SetPosition(_dragItem, _uiManager.MousePositionScaled.Position - new Vector2(32, 32));

        var mousePos = _uiManager.MousePositionScaled.Position;
        var closestBeacon = _beacons.Count > 0
            ? _beacons.MinBy(b => (mousePos - b.GlobalPosition).LengthSquared())
            : null;

        if (closestBeacon != _dragTarget)
        {
            _dragTarget?.UnbecomeTarget();
            _dragTarget = closestBeacon;
            _dragTarget?.BecomeTarget();
        }

        return true;
    }

    private void OnEndDrag()
    {
        if (_dragItem == null || _dragContainer == null)
        {
            _dragTarget = null;
            return;
        }

        _dragContainer.Visible = true;
        _dragItem.Orphan();
        _dragContainer.AddChild(_dragItem);
        _dragTarget?.UnbecomeTarget();

        if (_dragTarget != null)
            _model.ChangeMarkingOrder(_category, _dragItem.MarkingId, _dragTarget.CandidatePosition, _dragTarget.Index);

        _dragItem = null;
        _dragContainer = null;
        _dragTarget = null;
    }
}

internal readonly record struct CategoryMarkingDragged(CategoryMarkingItem Item, CategoryMarkingItemContainer Container);

internal sealed class CategoryMarkingItemContainer : PanelContainer
{
    public CategoryMarkingItemContainer()
    {
        SetHeight = 64;
        HorizontalExpand = true;
    }
}

internal sealed class CategoryDragDropBeacon : PanelContainer
{
    public readonly CandidatePosition CandidatePosition;
    public readonly int Index;

    public CategoryDragDropBeacon(CandidatePosition position, int index)
    {
        CandidatePosition = position;
        Index = index;
    }

    public void BecomeTarget()
    {
        SetHeight = 16;
        HorizontalExpand = true;
        PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#3A7EBF") };
    }

    public void UnbecomeTarget()
    {
        SetHeight = float.NaN;
        PanelOverride = null;
    }
}
