using System.Linq;
using Content.Client.ADT.UserInterface.Controls;
using Content.Client.Guidebook.Controls;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class CategoryMarkingItem : BoxContainer, ISearchableControl
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;
    private readonly MarkingsViewModel _model;
    private readonly MarkingPrototype _proto;
    private readonly MarkingCategories _category;
    private readonly bool _interactive;

    private List<LegacyColorSelectorSliders>? _colorSliders;

    private bool _colorChangePending;
    private float _colorThrottleTimer;
    private const float ColorThrottleDelay = 0.016f;

    public event Action<GUIBoundKeyEventArgs, CategoryMarkingItem>? Pressed;
    public event Action<GUIBoundKeyEventArgs, CategoryMarkingItem>? Unpressed;

    public string MarkingId => _proto.ID;

    public CategoryMarkingItem(MarkingsViewModel model, MarkingCategories category, MarkingPrototype proto, bool interactive)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entity.System<SpriteSystem>();

        _model = model;
        _category = category;
        _proto = proto;
        _interactive = interactive;

        UpdateData();
        UpdateSelection();

        SelectButton.OnPressed += SelectButtonPressed;
        ColorsButton.OnPressed += ColorsButtonPressed;

        OnKeyBindDown += OnKeyDown;
        OnKeyBindUp += OnKeyUp;

        if (!interactive)
            SelectButton.MouseFilter = MouseFilterMode.Ignore;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _model.MarkingsReset += UpdateSelection;
        _model.MarkingsChanged += OnMarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _model.MarkingsReset -= UpdateSelection;
        _model.MarkingsChanged -= OnMarkingsChanged;
    }

    private void OnMarkingsChanged(MarkingCategories category)
    {
        if (_category != category) return;
        UpdateSelection();
    }

    private void UpdateData()
    {
        MarkingTexture.Textures = _proto.Sprites.Select(s => _sprite.Frame0(s)).ToList();
        SelectButton.Text = Loc.GetString($"marking-{_proto.ID}");

        if (_proto.SponsorOnly && _interactive)
        {
            SelectButton.Disabled = !_model.IsSponsorAllowed(_proto.ID);
            if (SelectButton.Disabled)
                SelectButton.Text += " " + Loc.GetString("sponsor-only-text");
        }
    }

    private void UpdateSelection()
    {
        var selected = _model.IsMarkingSelected(_category, _proto.ID);
        SelectButton.Pressed = selected && _interactive;
        ColorsButton.Visible = selected && _interactive && _model.IsMarkingColorCustomizable(_category, _proto.ID);

        if (!selected || !_interactive)
        {
            ColorsButton.Pressed = false;
            ColorsContainer.Visible = false;
        }

        if (_model.GetMarking(_category, _proto.ID) is { } marking && _colorSliders is { } sliders)
        {
            for (var i = 0; i < _proto.Sprites.Count && i < sliders.Count; i++)
                sliders[i].Color = marking.MarkingColors[i];
        }
    }

    private void SelectButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (!_interactive)
        {
            SelectButton.Pressed = false;
            return;
        }

        if (_model.IsMarkingSelected(_category, _proto.ID))
        {
            if (!_model.TryDeselectMarking(_category, _proto.ID))
                SelectButton.Pressed = true;
        }
        else
        {
            if (!_model.TrySelectMarking(_category, _proto.ID))
                SelectButton.Pressed = false;
        }
    }

    private void ColorsButtonPressed(BaseButton.ButtonEventArgs args)
    {
        ColorsContainer.Visible = ColorsButton.Pressed;

        if (_colorSliders is not null)
            return;

        if (_model.GetMarking(_category, _proto.ID) is not { } marking)
            return;

        _colorSliders = new();

        for (var i = 0; i < _proto.Sprites.Count; i++)
        {
            var container = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            ColorsContainer.AddChild(container);

            var selector = new LegacyColorSelectorSliders();
            _colorSliders.Add(selector);

            var label = _proto.Sprites[i] switch
            {
                SpriteSpecifier.Rsi rsi => Loc.GetString($"marking-{_proto.ID}-{rsi.RsiState}"),
                SpriteSpecifier.Texture texture => Loc.GetString($"marking-{_proto.ID}-{texture.TexturePath.Filename}"),
                _ => _proto.ID,
            };

            container.AddChild(new Label { Text = label });
            container.AddChild(selector);

            selector.Color = marking.MarkingColors[i];

            selector.OnColorChanged += _ =>
            {
                _colorChangePending = true;
                _colorThrottleTimer = ColorThrottleDelay;
            };
        }
    }

    public bool CheckMatchesSearch(string query)
    {
        return Loc.GetString($"marking-{_proto.ID}").Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private void OnKeyDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick) return;
        Pressed?.Invoke(args, this);
    }

    private void OnKeyUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick) return;
        Unpressed?.Invoke(args, this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (!_colorChangePending) return;
        _colorThrottleTimer -= args.DeltaSeconds;
        if (_colorThrottleTimer > 0) return;
        _colorChangePending = false;
        if (_colorSliders == null) return;
        for (var i = 0; i < _colorSliders.Count; i++)
            _model.TrySetMarkingColor(_category, _proto.ID, i, _colorSliders[i].Color);
    }
}
