using System.Linq;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.Guidebook.Controls;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class CategoryMarkingPicker : BoxContainer
{
    private readonly IReadOnlyDictionary<string, MarkingPrototype> _allMarkings;
    private readonly MarkingCategories _category;
    private readonly MarkingsViewModel _model;
    private List<ISearchableControl> _searchable = new();
    private const int ColumnWidth = 500;

    public CategoryMarkingPicker(MarkingsViewModel model, MarkingCategories category, IReadOnlyDictionary<string, MarkingPrototype> allMarkings)
    {
        RobustXamlLoader.Load(this);

        _model = model;
        _category = category;
        _allMarkings = allMarkings;

        OrderingItems.AddChild(new CategoryMarkingOrderer(model, category));

        PopulateItems();

        SearchBar.OnTextChanged += _ =>
        {
            foreach (var element in _searchable)
                element.SetHiddenState(true, SearchBar.Text.Trim());
        };

        UpdateStatus();
        ReorderButton.OnPressed += ReorderButtonPressed;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _model.MarkingsReset += UpdateStatus;
        _model.MarkingsChanged += OnMarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _model.MarkingsReset -= UpdateStatus;
        _model.MarkingsChanged -= OnMarkingsChanged;
    }

    private void OnMarkingsChanged(MarkingCategories category)
    {
        if (_category != category) return;
        UpdateStatus();
    }

    private void PopulateItems()
    {
        foreach (var marking in _allMarkings.Values.OrderBy(m => Loc.GetString($"marking-{m.ID}")))
        {
            var item = new CategoryMarkingItem(_model, _category, marking, true);
            Items.AddChild(item);
        }
        _searchable = Items.GetSearchableControls();
    }

    private void UpdateStatus()
    {
        var pointsLeft = _model.PointsLeft(_category);
        if (pointsLeft >= 0)
            MarkingsStatus.Text = Loc.GetString("marking-points-remaining", ("points", pointsLeft));
        else
            MarkingsStatus.Text = string.Empty;
    }

    private void ReorderButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (ReorderButton.Pressed)
        {
            SelectionItems.Visible = false;
            SearchBar.Visible = false;
            OrderingItems.Visible = true;
        }
        else
        {
            SelectionItems.Visible = true;
            SearchBar.Visible = true;
            OrderingItems.Visible = false;
        }
    }

    protected override void Resized()
    {
        base.Resized();
        Items.Columns = Math.Max(1, (int)(Width / ColumnWidth));
    }
}
