using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private readonly MarkingsViewModel _model = new();

    // Legacy events kept for compatibility with HumanoidMarkingModifierWindow / HumanoidProfileEditor.
    // OnMarkingAdded is fired for ALL types of changes (add, remove, reorder, color).
    public Action<MarkingSet>? OnMarkingAdded;
    public Action<MarkingSet>? OnMarkingRemoved;
    public Action<MarkingSet>? OnMarkingColorChange;
    public Action<MarkingSet>? OnMarkingRankChange;

    public bool Forced
    {
        get => _model.Forced;
        set => _model.Forced = value;
    }

    public bool IgnoreSpecies
    {
        get => _model.IgnoreSpecies;
        set
        {
            _model.IgnoreSpecies = value;
            _model.SetIgnoreCategories(_model.IgnoreCategories);
        }
    }

    public Color CurrentSkinColor
    {
        get => _model.SkinColor;
        set => _model.SkinColor = value;
    }

    public Color CurrentEyeColor
    {
        get => _model.EyeColor;
        set => _model.EyeColor = value;
    }

    public Marking? HairMarking
    {
        get => _model.HairMarking;
        set => _model.HairMarking = value;
    }

    public Marking? FacialHairMarking
    {
        get => _model.FacialHairMarking;
        set => _model.FacialHairMarking = value;
    }

    private readonly HashSet<MarkingCategories> _ignoreCategories = new();

    public string IgnoreCategories
    {
        get => string.Join(',', _ignoreCategories);
        set
        {
            _ignoreCategories.Clear();
            foreach (var part in value.Split(','))
            {
                if (Enum.TryParse<MarkingCategories>(part.Trim(), out var parsed))
                    _ignoreCategories.Add(parsed);
            }
            _model.SetIgnoreCategories(_ignoreCategories);
        }
    }

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _model.CategoriesChanged += UpdateTabs;
        _model.MarkingsReset += UpdateTabs;
        _model.MarkingsChanged += OnMarkingsChanged;
        UpdateTabs();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _model.CategoriesChanged -= UpdateTabs;
        _model.MarkingsReset -= UpdateTabs;
        _model.MarkingsChanged -= OnMarkingsChanged;
    }

    private void OnMarkingsChanged(MarkingCategories _)
    {
        OnMarkingAdded?.Invoke(_model.GetMarkings());
    }

    // -------- Legacy API --------

    public void SetData(List<Marking> markings, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        _model.SetData(markings, species, sex, skinColor, eyeColor);
    }

    public void SetData(MarkingSet set, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        _model.SetData(set, species, sex, skinColor, eyeColor);
    }

    public void SetSpecies(string species)
    {
        _model.SetSpecies(species);
    }

    public void SetSex(Sex sex)
    {
        _model.SetSex(sex);
    }

    // -------- Tab management --------

    private void UpdateTabs()
    {
        CategoryTabs.RemoveAllChildren();
        var i = 0;

        foreach (var category in _model.GetVisibleCategories())
        {
            var allMarkings = _model.GetAvailableMarkings(category);
            var control = new CategoryMarkingPicker(_model, category, allMarkings);
            CategoryTabs.AddChild(control);
            CategoryTabs.SetTabTitle(i, Loc.GetString($"markings-category-{category}"));
            i++;
        }

        CategoryTabs.TabsVisible = i > 1;
        if (i > 0)
            CategoryTabs.CurrentTab = 0;
    }
}
