using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;
using System.Collections.Generic;

namespace Content.Client._VG.Storage.UI;

[GenerateTypedNameReferences]
public sealed partial class SmartOreBagWindow : FancyWindow
{
    private readonly List<ProtoId<EntityPrototype>> _initialIgnored = new();
    private readonly Dictionary<CheckBox, ProtoId<EntityPrototype>> _checkBoxMapping = new();
    
    public event System.Action<List<ProtoId<EntityPrototype>>>? OnConfirmed;

    public SmartOreBagWindow()
    {
        RobustXamlLoader.Load(this);
        
        CancelButton.OnPressed += OnCancelPressed;
        SaveButton.OnPressed += OnSavePressed;
    }

    public void UpdateState(List<ProtoId<EntityPrototype>> ignoredOres)
    {
        _initialIgnored.Clear();
        _initialIgnored.AddRange(ignoredOres);
        _checkBoxMapping.Clear();
        OreListContainer.RemoveAllChildren();
        BuildOreList();
    }

    private void BuildOreList()
    {
        var oreIds = new List<string>
        {
            "SteelOre1",
            "SpaceQuartz1",
            "Coal1",
            "GoldOre1",
            "SilverOre1",
            "Salt1",
            "PlasmaOre1",
            "UraniumOre1",
            "BananiumOre1",
            "DiamondOre1",
            
            // ADT-руды
            "ADTCopperOre",
            "ADTZincOre",
            "ADTLeadOre",
            "ADTBSore",
            
            // Артефакты
            "ArtifactFragment1"
        };
        
        foreach (var oreId in oreIds)
        {
            var protoId = new ProtoId<EntityPrototype>(oreId);
            
            var displayName = Loc.GetString($"ent-{oreId}") ?? oreId;
            
            var checkBox = new CheckBox
            {
                Text = displayName,
                Pressed = !_initialIgnored.Contains(protoId),
                ToolTip = Loc.GetString($"ent-{oreId}.desc") 
            };
            _checkBoxMapping[checkBox] = protoId;
            OreListContainer.AddChild(checkBox);
        }
    }

    private void OnSavePressed(BaseButton.ButtonEventArgs args)
    {
        var ignored = new List<ProtoId<EntityPrototype>>();
        foreach (var (checkBox, protoId) in _checkBoxMapping)
        {
            if (!checkBox.Pressed)
                ignored.Add(protoId);
        }
        OnConfirmed?.Invoke(ignored);
        Close();
    }

    private void OnCancelPressed(BaseButton.ButtonEventArgs args)
    {
        Close();
    }
}