using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Collections.Generic;
using System.Linq;

namespace Content.Client._VG.Storage.UI;

[GenerateTypedNameReferences]
public sealed partial class SmartOreBagWindow : FancyWindow
{
    private readonly List<ProtoId<EntityPrototype>> _initialIgnored = new();
    private readonly Dictionary<CheckBox, ProtoId<EntityPrototype>> _checkBoxMapping = new();
    
    public event System.Action<List<ProtoId<EntityPrototype>>>? OnConfirmed;

    public SmartOreBagWindow()
    {
        RobustXamlLoader.Load(this);
        
        CancelButton.OnPressed += OnCancelPressed;
        SaveButton.OnPressed += OnSavePressed;
        SelectAllButton.OnPressed += OnSelectAll;
        SelectNoneButton.OnPressed += OnSelectNone;
        SearchBox.OnTextChanged += OnSearchChanged;
    }

    public void UpdateState(List<ProtoId<EntityPrototype>> ignoredOres)
    {
        _initialIgnored.Clear();
        _initialIgnored.AddRange(ignoredOres);
        _checkBoxMapping.Clear();
        
        BasicOresContainer.RemoveAllChildren();
        SpecialOresContainer.RemoveAllChildren();
        ArtifactsContainer.RemoveAllChildren();
        
        BuildOreList();
        UpdateSelectedCount();
    }

    private void BuildOreList()
    {
        var basicOres = new List<(string Id, string Name)>
        {
            ("SteelOre1", "Железная руда"),
            ("SpaceQuartz1", "Кварц"),
            ("Coal1", "Уголь"),
            ("GoldOre1", "Золотая руда"),
            ("SilverOre1", "Серебряная руда"),
            ("Salt1", "Соль"),
            ("PlasmaOre1", "Плазма"),
            ("UraniumOre1", "Урановая руда"),
            ("BananiumOre1", "Бананиум"),
            ("DiamondOre1", "Алмаз"),
        };
        
        var specialOres = new List<(string Id, string Name)>
        {
            ("ADTCopperOre", "Медная руда"),
            ("ADTZincOre", "Цинковая руда"),
            ("ADTLeadOre", "Свинцовая руда"),
            ("ADTBSore", "БС-руда"),
        };
        
        var artifacts = new List<(string Id, string Name)>
        {
            ("ArtifactFragment1", "Фрагмент артефакта"),
        };
        
        AddOresToContainer(basicOres, BasicOresContainer);
        AddOresToContainer(specialOres, SpecialOresContainer);
        AddOresToContainer(artifacts, ArtifactsContainer);
    }

    private void AddOresToContainer(List<(string Id, string Name)> ores, BoxContainer container)
    {
        foreach (var (oreId, displayName) in ores)
        {
            var protoId = new ProtoId<EntityPrototype>(oreId);
            var checkBox = new CheckBox
            {
                Text = displayName,
                Pressed = !_initialIgnored.Contains(protoId),
                ToolTip = Loc.GetString($"ent-{oreId}.desc"),
                Margin = new Thickness(0, 3, 0, 3),
                StyleClasses = { "CheckBoxBig" }
            };
            
            checkBox.OnToggled += _ => UpdateSelectedCount();
            
            _checkBoxMapping[checkBox] = protoId;
            container.AddChild(checkBox);
        }
    }

    private void UpdateSelectedCount()
    {
        var selectedCount = _checkBoxMapping.Count(kv => kv.Key.Pressed);
        SelectedCountLabel.Text = $"Выбрано: {selectedCount} / {_checkBoxMapping.Count} руд";
        SelectedCountLabel.FontColorOverride = selectedCount > 0 ? Color.FromHex("#4caf50") : Color.FromHex("#888888");
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        var searchText = args.Text?.ToLowerInvariant() ?? "";
        
        foreach (var (checkBox, _) in _checkBoxMapping)
        {
            checkBox.Visible = string.IsNullOrEmpty(searchText) || 
                               checkBox.Text?.ToLowerInvariant().Contains(searchText) == true;
        }
    }

    private void OnSelectAll(BaseButton.ButtonEventArgs args)
    {
        foreach (var (checkBox, _) in _checkBoxMapping)
        {
            checkBox.Pressed = true;
        }
        UpdateSelectedCount();
    }

    private void OnSelectNone(BaseButton.ButtonEventArgs args)
    {
        foreach (var (checkBox, _) in _checkBoxMapping)
        {
            checkBox.Pressed = false;
        }
        UpdateSelectedCount();
    }

    private void OnSavePressed(BaseButton.ButtonEventArgs args)
    {
        var ignored = new List<ProtoId<EntityPrototype>>();
        foreach (var (checkBox, protoId) in _checkBoxMapping)
        {
            if (!checkBox.Pressed)
                ignored.Add(protoId);
        }
        OnConfirmed?.Invoke(ignored);
        Close();
    }

    private void OnCancelPressed(BaseButton.ButtonEventArgs args)
    {
        Close();
    }
}