using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.Localization;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class EventDropWindow : DefaultWindow
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly ILocalizationManager _loc = default!;
        
        private List<string> _currentQueue = new();
        private List<PresetInfo> _presets = new();

        private class PresetInfo
        {
            public string Id { get; set; } = "";
            public string Description { get; set; } = "";
            public int ItemsCount { get; set; }
            public int UniqueItems { get; set; }
        }

        public EventDropWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            MainTabContainer.SetTabTitle(0, Loc.GetString("admin-event-drop-tab-queue"));
            MainTabContainer.SetTabTitle(1, Loc.GetString("admin-event-drop-tab-presets"));

            WireEvents();
            RefreshQueueDisplay();
            UpdateStatus();
            RefreshPresetButtons();
        }

        private void WireEvents()
        {
            AddItemButton.OnPressed += OnAddItem;
            ClearQueueButton.OnPressed += OnClearQueue;
            SendDropButton.OnPressed += OnSendDrop;
            RemoveLastButton.OnPressed += OnRemoveLast;
            AmountInput.OnTextChanged += _ => ValidateAmountInput();
            ItemInput.OnTextEntered += _ => OnAddItem(null!);
            
            SavePresetButton.OnPressed += OnSavePreset;
            LoadPresetButton.OnPressed += OnLoadPreset;
            DeletePresetButton.OnPressed += OnDeletePreset;
            RefreshPresetsButton.OnPressed += OnRefreshPresets;
            PresetNameInput.OnTextChanged += _ => RefreshPresetButtons();
            PresetNameInput.OnTextEntered += _ => OnLoadPreset(null!);
            
            MainTabContainer.OnTabChanged += _ =>
            {
                if (MainTabContainer.CurrentTab == 1)
                    ShowPresetsInfo();
            };
        }

        private void OnRefreshPresets(BaseButton.ButtonEventArgs args)
        {
            ShowPresetsInfo();
            UpdateStatus(Loc.GetString("admin-event-drop-status-presets-refreshed"));
        }

        private void ShowPresetsInfo()
        {
            PresetsContainer.RemoveAllChildren();
            
            var infoLabel = new Label
            {
                Text = Loc.GetString("admin-event-drop-presets-console-info"),
                Margin = new Thickness(5),
                StyleClasses = { "LabelSmall" }
            };
            PresetsContainer.AddChild(infoLabel);

            _consoleHost.ExecuteCommand("drop_preset_list");
        }

        private void OnAddItem(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(ItemInput.Text))
                return;

            var input = ItemInput.Text.Trim();
            var amount = 1;
            if (!string.IsNullOrWhiteSpace(AmountInput.Text))
                int.TryParse(AmountInput.Text, out amount);
            if (amount < 1) amount = 1;

            if (input.StartsWith("preset:", StringComparison.OrdinalIgnoreCase))
            {
                var presetId = input.Substring(7);
                var cmd = $"drop_add preset:{CommandParsing.Escape(presetId)}";
                _consoleHost.ExecuteCommand(cmd);
                UpdateStatus(Loc.GetString("admin-event-drop-status-preset-added", ("preset", presetId)));
                _currentQueue.Add(Loc.GetString("admin-event-drop-queue-preset-format", ("preset", presetId)));
            }
            else
            {
                for (int i = 0; i < amount; i++)
                    _currentQueue.Add(input);
                var cmd = $"drop_add {CommandParsing.Escape(input)} {amount}";
                _consoleHost.ExecuteCommand(cmd);
                UpdateStatus(Loc.GetString("admin-event-drop-status-items-added", ("amount", amount), ("item", input)));
            }
            
            ItemInput.Text = string.Empty;
            AmountInput.Text = "1";
            RefreshQueueDisplay();
        }

        private void OnClearQueue(BaseButton.ButtonEventArgs args)
        {
            _currentQueue.Clear();
            _consoleHost.ExecuteCommand("drop_clear");
            UpdateStatus(Loc.GetString("admin-event-drop-status-queue-cleared"));
            RefreshQueueDisplay();
        }

        private void OnSendDrop(BaseButton.ButtonEventArgs args)
        {
            if (_currentQueue.Count == 0)
            {
                UpdateStatus(Loc.GetString("admin-event-drop-status-queue-empty"));
                return;
            }
            _consoleHost.ExecuteCommand("drop_send");
            UpdateStatus(Loc.GetString("admin-event-drop-status-capsule-sent"));
            _currentQueue.Clear();
            RefreshQueueDisplay();
        }

        private void OnRemoveLast(BaseButton.ButtonEventArgs args)
        {
            if (_currentQueue.Count == 0) return;
            var last = _currentQueue.Last();
            _currentQueue.RemoveAt(_currentQueue.Count - 1);

            _consoleHost.ExecuteCommand("drop_clear");
            foreach (var item in _currentQueue)
            {
                if (item.StartsWith(Loc.GetString("admin-event-drop-queue-preset-prefix")))
                {
                    var presetId = ExtractPresetIdFromDisplayString(item);
                    if (!string.IsNullOrEmpty(presetId))
                        _consoleHost.ExecuteCommand($"drop_add preset:{CommandParsing.Escape(presetId)}");
                }
                else
                {
                    _consoleHost.ExecuteCommand($"drop_add {CommandParsing.Escape(item)}");
                }
            }
            
            UpdateStatus(Loc.GetString("admin-event-drop-status-item-removed", ("item", last)));
            RefreshQueueDisplay();
        }

        private void OnSavePreset(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(PresetNameInput.Text))
            {
                UpdateStatus(Loc.GetString("admin-event-drop-status-error-no-name"));
                return;
            }
            var presetId = PresetNameInput.Text.Trim();
            var description = PresetDescriptionInput.Text.Trim();
            
            var cmd = $"drop_preset_save {CommandParsing.Escape(presetId)}";
            if (!string.IsNullOrWhiteSpace(description))
                cmd += $" \"{CommandParsing.Escape(description)}\"";
            _consoleHost.ExecuteCommand(cmd);
            
            UpdateStatus(Loc.GetString("admin-event-drop-status-preset-saved", ("preset", presetId)));
            PresetNameInput.Text = "";
            PresetDescriptionInput.Text = "";
        }

        private void OnLoadPreset(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(PresetNameInput.Text))
            {
                UpdateStatus(Loc.GetString("admin-event-drop-status-error-no-name"));
                return;
            }
            
            var presetId = PresetNameInput.Text.Trim();
            _consoleHost.ExecuteCommand($"drop_preset_load {CommandParsing.Escape(presetId)}");
            UpdateStatus(Loc.GetString("admin-event-drop-status-preset-loaded", ("preset", presetId)));
            
            _currentQueue.Clear();
            _currentQueue.Add(Loc.GetString("admin-event-drop-queue-preset-format", ("preset", presetId)));
            RefreshQueueDisplay();
            MainTabContainer.CurrentTab = 0;
        }

        private void OnDeletePreset(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(PresetNameInput.Text))
            {
                UpdateStatus(Loc.GetString("admin-event-drop-status-error-no-name"));
                return;
            }
            
            var presetId = PresetNameInput.Text.Trim();
            _consoleHost.ExecuteCommand($"drop_preset_delete {CommandParsing.Escape(presetId)}");
            UpdateStatus(Loc.GetString("admin-event-drop-status-preset-deleted", ("preset", presetId)));
            PresetNameInput.Text = "";
        }

        private void RefreshQueueDisplay()
        {
            if (_currentQueue.Count == 0)
                QueueLabel.Text = Loc.GetString("admin-event-drop-queue-empty");
            else
                QueueLabel.Text = string.Join(Loc.GetString("admin-event-drop-queue-separator"), _currentQueue);
        }

        private void RefreshPresetButtons()
        {
            var hasName = !string.IsNullOrWhiteSpace(PresetNameInput.Text);
            SavePresetButton.Disabled = !hasName;
            LoadPresetButton.Disabled = !hasName;
            DeletePresetButton.Disabled = !hasName;
        }

        private void ValidateAmountInput()
        {
            if (!int.TryParse(AmountInput.Text, out var amount) || amount < 1)
                AmountInput.Text = "1";
        }

        private string ExtractPresetIdFromDisplayString(string displayString)
        {
            var startIndex = displayString.IndexOf(':') + 1;
            var endIndex = displayString.LastIndexOf(']');
            if (startIndex > 0 && endIndex > startIndex)
                return displayString.Substring(startIndex, endIndex - startIndex);
            return "";
        }

        private void UpdateStatus(string? message = null)
        {
            if (message != null)
                StatusLabel.Text = Loc.GetString("admin-event-drop-status-format", 
                    ("time", DateTime.Now.ToString("HH:mm:ss")), 
                    ("message", message));
            else
                StatusLabel.Text = Loc.GetString("admin-event-drop-status-ready");
        }
    }
}