using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.Administration;
using Content.Shared.Roles;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class PlayTimeEditorWindow : DefaultWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        private readonly IClientConsoleHost _consoleHost;
        
        // Списки для ролей и отделов
        private readonly List<(string Name, string Tracker)> _allRoles = new();
        private readonly List<(string LocalizedName, string Id)> _allDepartments = new();
        
        // Переключатель между режимами: роль или отдел
        private enum TargetType
        {
            Role,
            Department
        }
        
        private TargetType _currentTargetType = TargetType.Role;

        public PlayTimeEditorWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _consoleHost = IoCManager.Resolve<IClientConsoleHost>();

            // Устанавливаем заголовки вкладок
            MainTabContainer.SetTabTitle(0, Loc.GetString("admin-time-panel-tab-edit"));
            MainTabContainer.SetTabTitle(1, Loc.GetString("admin-time-panel-tab-reset"));

            InitializeData();
            WireEvents();
            SetButtonsState(true);
        }

        private void InitializeData()
        {
            _allRoles.Clear();
            _allDepartments.Clear();

            // Загружаем все профессии (роли)
            foreach (var job in _prototypeManager.EnumeratePrototypes<JobPrototype>())
            {
                _allRoles.Add((job.LocalizedName, job.PlayTimeTracker));
            }

            // Загружаем все отделы
            foreach (var dept in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
            {
                // Пытаемся получить локализованное название отдела
                var deptName = Loc.TryGetString($"department-{dept.ID}", out var localized) 
                    ? localized 
                    : dept.ID;
                
                _allDepartments.Add((deptName, dept.ID));
            }

            // Заполняем выпадающие списки
            RefreshFilteredRoles("");
            RefreshFilteredDepartments("");
        }

        private void UpdateTargetSelector()
        {
            // Прячем/показываем соответствующие контролы
            RoleOption.Visible = _currentTargetType == TargetType.Role;
            DepartmentOption.Visible = _currentTargetType == TargetType.Department;
            RoleFilterInput.PlaceHolder = _currentTargetType == TargetType.Role 
                ? Loc.GetString("admin-time-panel-window-role-filtre")
                : Loc.GetString("admin-time-panel-window-department-filtre");
            
            RefreshFilteredRoles(RoleFilterInput.Text);
            RefreshFilteredDepartments(RoleFilterInput.Text);
        }

        private void RefreshFilteredRoles(string filter)
        {
            RoleOption.Clear();
            var index = 0;

            var sortedRoles = _allRoles
                .Where(r => r.Name.Contains(filter, StringComparison.OrdinalIgnoreCase))
                .OrderBy(r => r.Name);

            foreach (var (name, tracker) in sortedRoles)
            {
                RoleOption.AddItem(name);
                RoleOption.SetItemMetadata(index++, tracker);
            }

            if (RoleOption.ItemCount > 0)
                RoleOption.SelectId(0);
        }

        private void RefreshFilteredDepartments(string filter)
        {
            DepartmentOption.Clear();
            var index = 0;

            var sortedDepartments = _allDepartments
                .Where(d => d.LocalizedName.Contains(filter, StringComparison.OrdinalIgnoreCase) || 
                           d.Id.Contains(filter, StringComparison.OrdinalIgnoreCase))
                .OrderBy(d => d.LocalizedName);

            foreach (var (localizedName, id) in sortedDepartments)
            {
                DepartmentOption.AddItem(localizedName);
                DepartmentOption.SetItemMetadata(index++, id);
            }

            if (DepartmentOption.ItemCount > 0)
                DepartmentOption.SelectId(0);
        }

        private void WireEvents()
        {
            // События для вкладки редактирования
            PlayerNameLine.OnTextChanged += _ => RefreshButtons();
            MinutesInput.OnTextChanged += _ => RefreshButtons();
            MinutesInput.OnTextChanged += UpdateTimeButtonsLabels;
            PlayerList.OnSelectionChanged += OnPlayerSelected;
            RoleFilterInput.OnTextChanged += _ => 
            {
                if (_currentTargetType == TargetType.Role)
                    RefreshFilteredRoles(RoleFilterInput.Text);
                else
                    RefreshFilteredDepartments(RoleFilterInput.Text);
            };

            // Радио-кнопки
            RoleRadioButton.OnToggled += args =>
            {
                if (args.Pressed)
                {
                    DepartmentRadioButton.Pressed = false;
                    _currentTargetType = TargetType.Role;
                    UpdateTargetSelector();
                }
            };
            
            DepartmentRadioButton.OnToggled += args =>
            {
                if (args.Pressed)
                {
                    RoleRadioButton.Pressed = false;
                    _currentTargetType = TargetType.Department;
                    UpdateTargetSelector();
                }
            };

            // Кнопки добавления времени
            AddHourButton.OnPressed += _ => AdjustMinutes(60);
            AddDayButton.OnPressed += _ => AdjustMinutes(1440);
            AddWeekButton.OnPressed += _ => AdjustMinutes(10080);
            AddMonthButton.OnPressed += _ => AdjustMinutes(43200);

            // Кнопки применения
            ApplyRoleButton.OnPressed += OnApply;
            ApplyTotalButton.OnPressed += OnApplyTotal;
            
            // Выбор в выпадающих списках
            RoleOption.OnItemSelected += args => RoleOption.SelectId(args.Id);
            DepartmentOption.OnItemSelected += args => DepartmentOption.SelectId(args.Id);

            // События для вкладки сброса
            ResetPlayerNameLine.OnTextChanged += _ => RefreshResetButtons();
            ResetPlayerList.OnSelectionChanged += OnResetPlayerSelected;

            ResetAllButton.OnPressed += OnResetAll;
            ResetRolesButton.OnPressed += OnResetRoles;
            ResetOverallButton.OnPressed += OnResetOverall;
        }

        private void OnPlayerSelected(PlayerInfo? player)
        {
            PlayerNameLine.Text = player?.Username ?? string.Empty;
            RefreshButtons();
        }

        private void OnResetPlayerSelected(PlayerInfo? player)
        {
            ResetPlayerNameLine.Text = player?.Username ?? string.Empty;
            RefreshResetButtons();
        }

        private void OnApply(BaseButton.ButtonEventArgs _)
        {
            if (string.IsNullOrWhiteSpace(PlayerNameLine.Text) || 
                string.IsNullOrWhiteSpace(MinutesInput.Text))
                return;

            if (_currentTargetType == TargetType.Role)
            {
                // Добавление к конкретной роли
                if (RoleOption.SelectedMetadata is not string role || string.IsNullOrWhiteSpace(role))
                    return;

                _consoleHost.ExecuteCommand($"playtime_addrole_as \"{PlayerNameLine.Text}\" \"{CommandParsing.Escape(role)}\" {MinutesInput.Text}");
            }
            else
            {
                // Добавление ко всем ролям отдела
                if (DepartmentOption.SelectedMetadata is not string department || string.IsNullOrWhiteSpace(department))
                    return;

                _consoleHost.ExecuteCommand($"playtime_adddepartment_as \"{PlayerNameLine.Text}\" \"{CommandParsing.Escape(department)}\" {MinutesInput.Text}");
            }
        }

        private void OnApplyTotal(BaseButton.ButtonEventArgs _)
        {
            if (string.IsNullOrWhiteSpace(PlayerNameLine.Text) || 
                string.IsNullOrWhiteSpace(MinutesInput.Text))
                return;

            _consoleHost.ExecuteCommand($"playtime_addoverall_as \"{PlayerNameLine.Text}\" {MinutesInput.Text}");
        }

        private void OnResetAll(BaseButton.ButtonEventArgs _)
        {
            if (string.IsNullOrWhiteSpace(ResetPlayerNameLine.Text))
                return;

            _consoleHost.ExecuteCommand($"playtime_resetall_as \"{ResetPlayerNameLine.Text}\"");
        }

        private void OnResetRoles(BaseButton.ButtonEventArgs _)
        {
            if (string.IsNullOrWhiteSpace(ResetPlayerNameLine.Text))
                return;

            _consoleHost.ExecuteCommand($"playtime_resetroles_as \"{ResetPlayerNameLine.Text}\"");
        }

        private void OnResetOverall(BaseButton.ButtonEventArgs _)
        {
            if (string.IsNullOrWhiteSpace(ResetPlayerNameLine.Text))
                return;

            _consoleHost.ExecuteCommand($"playtime_resetoverall_as \"{ResetPlayerNameLine.Text}\"");
        }

        private void RefreshButtons()
        {
            var inputValid = !string.IsNullOrWhiteSpace(PlayerNameLine.Text) && 
                           !string.IsNullOrWhiteSpace(MinutesInput.Text) &&
                           uint.TryParse(MinutesInput.Text, out _);
            
            SetButtonsState(!inputValid);
        }

        private void RefreshResetButtons()
        {
            var inputValid = !string.IsNullOrWhiteSpace(ResetPlayerNameLine.Text);
            
            ResetAllButton.Disabled = !inputValid;
            ResetRolesButton.Disabled = !inputValid;
            ResetOverallButton.Disabled = !inputValid;
        }

        private void SetButtonsState(bool disabled)
        {
            ApplyRoleButton.Disabled = disabled;
            ApplyTotalButton.Disabled = disabled;
        }

        private void UpdateTimeButtonsLabels(LineEditEventArgs _)
        {
            if (!uint.TryParse(MinutesInput.Text, out var minutes))
                return;

            AddHourButton.Text = $"+1h ({minutes / 60})";
            AddDayButton.Text = $"+1d ({minutes / 1440})";
            AddWeekButton.Text = $"+1w ({minutes / 10080})";
            AddMonthButton.Text = $"+1M ({minutes / 43200})";
        }

        private void AdjustMinutes(uint delta)
        {
            if (!uint.TryParse(MinutesInput.Text, out var current))
                current = 0;

            var total = current + delta;
            MinutesInput.Text = total.ToString();

            UpdateTimeButtonsLabels(null!);
            RefreshButtons();
        }
    }
}