using System;
using Content.Client._VG.Sponsors;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.Administration;
using Content.Shared.Roles;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class SponsorEditorWindow : DefaultWindow
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly SponsorsManager _sponsorsManager = default!;

        public SponsorEditorWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            MainTabContainer.SetTabTitle(0, Loc.GetString("admin-sponsor-panel-tab-sponsor"));
            MainTabContainer.SetTabTitle(1, Loc.GetString("admin-sponsor-panel-tab-loadout"));
            MainTabContainer.SetTabTitle(2, Loc.GetString("admin-sponsor-panel-tab-color")); // Новая вкладка

            WireEvents();
            RefreshButtons();
        }

        private void WireEvents()
        {
            // События для вкладки спонсоров
            PlayerNameLine.OnTextChanged += _ => RefreshButtons();
            TierInput.OnTextChanged += _ => RefreshButtons();
            DaysInput.OnTextChanged += _ => RefreshButtons();
            PlayerList.OnSelectionChanged += OnPlayerSelected;

            AddDayButton.OnPressed += _ => AdjustDays(1);
            AddWeekButton.OnPressed += _ => AdjustDays(7);
            AddMonthButton.OnPressed += _ => AdjustDays(30);
            AddYearButton.OnPressed += _ => AdjustDays(365);
            ClearExpireButton.OnPressed += _ => DaysInput.Text = "0";

            AddSponsorButton.OnPressed += OnAddSponsor;
            RemoveSponsorButton.OnPressed += OnRemoveSponsor;

            // События для вкладки лодаутов
            LoadoutPlayerNameLine.OnTextChanged += _ => RefreshLoadoutButtons();
            LoadoutIdInput.OnTextChanged += _ => RefreshLoadoutButtons();
            LoadoutPlayerList.OnSelectionChanged += OnLoadoutPlayerSelected;

            AddLoadoutButton.OnPressed += OnAddLoadout;
            RemoveLoadoutButton.OnPressed += OnRemoveLoadout;

            // События для вкладки цвета
            ColorPlayerNameLine.OnTextChanged += _ => RefreshColorButtons();
            ColorHexInput.OnTextChanged += _ => RefreshColorButtons();
            ColorPlayerList.OnSelectionChanged += OnColorPlayerSelected;

            ApplyColorButton.OnPressed += OnApplyColor;
            ClearColorButton.OnPressed += OnClearColor;
        }

        private void OnPlayerSelected(PlayerInfo? player)
        {
            PlayerNameLine.Text = player?.Username ?? string.Empty;
            RefreshButtons();
        }

        private void OnLoadoutPlayerSelected(PlayerInfo? player)
        {
            LoadoutPlayerNameLine.Text = player?.Username ?? string.Empty;
            RefreshLoadoutButtons();
        }

        private void OnColorPlayerSelected(PlayerInfo? player)
        {
            ColorPlayerNameLine.Text = player?.Username ?? string.Empty;
            RefreshColorButtons();
        }

        private void OnAddSponsor(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(PlayerNameLine.Text))
                return;

            if (!int.TryParse(TierInput.Text, out var tier) || tier < 1 || tier > 3)
            {
                TierInput.Text = "";
                return;
            }

            var days = 0;
            if (!string.IsNullOrWhiteSpace(DaysInput.Text) && !int.TryParse(DaysInput.Text, out days))
            {
                DaysInput.Text = "";
                return;
            }

            var notes = NotesInput.Text;
            if (string.IsNullOrWhiteSpace(notes))
                notes = "null";

            var cmd = $"sponsoradd \"{CommandParsing.Escape(PlayerNameLine.Text)}\" {tier}";
            if (days > 0)
                cmd += $" {days}";
            if (!string.IsNullOrWhiteSpace(notes) && notes != "null")
                cmd += $" \"{CommandParsing.Escape(notes)}\"";

            _consoleHost.ExecuteCommand(cmd);

            // Очистка полей
            TierInput.Text = "";
            DaysInput.Text = "0";
            NotesInput.Text = "";
        }

        private void OnRemoveSponsor(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(PlayerNameLine.Text))
                return;

            var cmd = $"sponsorremove \"{CommandParsing.Escape(PlayerNameLine.Text)}\"";
            _consoleHost.ExecuteCommand(cmd);

            PlayerNameLine.Text = "";
        }

        private void OnAddLoadout(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(LoadoutPlayerNameLine.Text))
                return;

            if (string.IsNullOrWhiteSpace(LoadoutIdInput.Text))
                return;

            var cmd = $"sponsoraddloadout \"{CommandParsing.Escape(LoadoutPlayerNameLine.Text)}\" {LoadoutIdInput.Text}";
            _consoleHost.ExecuteCommand(cmd);

            LoadoutIdInput.Text = "";
        }

        private void OnRemoveLoadout(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(LoadoutPlayerNameLine.Text))
                return;

            if (string.IsNullOrWhiteSpace(LoadoutIdInput.Text))
                return;

            var cmd = $"sponsorremoveloadout \"{CommandParsing.Escape(LoadoutPlayerNameLine.Text)}\" {LoadoutIdInput.Text}";
            _consoleHost.ExecuteCommand(cmd);

            LoadoutIdInput.Text = "";
        }

        private void OnApplyColor(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(ColorPlayerNameLine.Text))
                return;

            var colorHex = ColorHexInput.Text?.Trim();
            if (string.IsNullOrWhiteSpace(colorHex))
                return;

            // Простая валидация HEX
            if (!colorHex.StartsWith('#') || 
                (colorHex.Length != 4 && colorHex.Length != 7 && colorHex.Length != 9))
            {
                ColorHexInput.Text = "";
                return;
            }

            var cmd = $"sponsorooccolor \"{CommandParsing.Escape(ColorPlayerNameLine.Text)}\" {colorHex}";
            _consoleHost.ExecuteCommand(cmd);

            ColorHexInput.Text = "";
        }

        private void OnClearColor(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(ColorPlayerNameLine.Text))
                return;

            var cmd = $"sponsorooccolorclear \"{CommandParsing.Escape(ColorPlayerNameLine.Text)}\"";
            _consoleHost.ExecuteCommand(cmd);
    
            ColorHexInput.Text = "";
            RefreshColorButtons();
        }

        private void RefreshButtons()
        {
            var inputValid = !string.IsNullOrWhiteSpace(PlayerNameLine.Text);
            AddSponsorButton.Disabled = !inputValid || string.IsNullOrWhiteSpace(TierInput.Text);
            RemoveSponsorButton.Disabled = !inputValid;
        }

        private void RefreshLoadoutButtons()
        {
            var inputValid = !string.IsNullOrWhiteSpace(LoadoutPlayerNameLine.Text) && 
                           !string.IsNullOrWhiteSpace(LoadoutIdInput.Text);
            AddLoadoutButton.Disabled = !inputValid;
            RemoveLoadoutButton.Disabled = !inputValid;
        }

        private void RefreshColorButtons()
        {
            var inputValid = !string.IsNullOrWhiteSpace(ColorPlayerNameLine.Text) && 
                           !string.IsNullOrWhiteSpace(ColorHexInput.Text);
            ApplyColorButton.Disabled = !inputValid;
            // Кнопка очистки всегда активна
            ClearColorButton.Disabled = false;
        }

        private void AdjustDays(int delta)
        {
            if (!int.TryParse(DaysInput.Text, out var current))
                current = 0;

            var total = current + delta;
            if (total < 0)
                total = 0;

            DaysInput.Text = total.ToString();
            RefreshButtons();
        }
    }
}