using System;
using Content.Client._VG.Sponsors;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.Administration;
using Content.Shared.Roles;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class SponsorEditorWindow : DefaultWindow
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly SponsorsManager _sponsorsManager = default!;

        public SponsorEditorWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            WireEvents();
            RefreshButtons();
        }

        private void WireEvents()
        {
            PlayerNameLine.OnTextChanged += _ => RefreshButtons();
            TierInput.OnTextChanged += _ => RefreshButtons();
            DaysInput.OnTextChanged += _ => RefreshButtons();
            PlayerList.OnSelectionChanged += OnPlayerSelected;

            AddDayButton.OnPressed += _ => AdjustDays(1);
            AddWeekButton.OnPressed += _ => AdjustDays(7);
            AddMonthButton.OnPressed += _ => AdjustDays(30);
            AddYearButton.OnPressed += _ => AdjustDays(365);
            ClearExpireButton.OnPressed += _ => DaysInput.Text = "0";

            AddSponsorButton.OnPressed += OnAddSponsor;
            RemoveSponsorButton.OnPressed += OnRemoveSponsor;
        }

        private void OnPlayerSelected(PlayerInfo? player)
        {
            PlayerNameLine.Text = player?.Username ?? string.Empty;
            RefreshButtons();
        }

        private void OnAddSponsor(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(PlayerNameLine.Text))
                return;

            if (!int.TryParse(TierInput.Text, out var tier) || tier < 1 || tier > 3)
            {
                TierInput.Text = "";
                return;
            }

            var days = 0;
            if (!string.IsNullOrWhiteSpace(DaysInput.Text) && !int.TryParse(DaysInput.Text, out days))
            {
                DaysInput.Text = "";
                return;
            }

            var notes = NotesInput.Text;
            if (string.IsNullOrWhiteSpace(notes))
                notes = "null";

            var cmd = $"sponsoradd \"{CommandParsing.Escape(PlayerNameLine.Text)}\" {tier}";
            if (days > 0)
                cmd += $" {days}";
            if (!string.IsNullOrWhiteSpace(notes) && notes != "null")
                cmd += $" \"{CommandParsing.Escape(notes)}\"";

            _consoleHost.ExecuteCommand(cmd);

            // Очистка полей
            TierInput.Text = "";
            DaysInput.Text = "0";
            NotesInput.Text = "";
        }

        private void OnRemoveSponsor(BaseButton.ButtonEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(PlayerNameLine.Text))
                return;

            var cmd = $"sponsorremove \"{CommandParsing.Escape(PlayerNameLine.Text)}\"";
            _consoleHost.ExecuteCommand(cmd);

            PlayerNameLine.Text = "";
        }

        private void RefreshButtons()
        {
            var inputValid = !string.IsNullOrWhiteSpace(PlayerNameLine.Text);
            AddSponsorButton.Disabled = !inputValid || string.IsNullOrWhiteSpace(TierInput.Text);
            RemoveSponsorButton.Disabled = !inputValid;
        }

        private void AdjustDays(int delta)
        {
            if (!int.TryParse(DaysInput.Text, out var current))
                current = 0;

            var total = current + delta;
            if (total < 0)
                total = 0;

            DaysInput.Text = total.ToString();
            RefreshButtons();
        }
    }
}