using System.Linq;
using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static System.StringComparison;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private AudioSystem _audioSystem;

    private bool _playState;
    private List<JukeboxPrototype> _allSongs = new();
    private JukeboxRepeatMode _repeatMode = JukeboxRepeatMode.NoRepeat;

    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;
    public event Action<float>? SetVolume;
    public event Action<JukeboxRepeatMode>? OnRepeatModeChanged;
    public event Action<bool>? OnShuffleToggled;
    public event Action? OnNextTrack;
    public event Action? OnPrevTrack;
    public event Action<ProtoId<JukeboxPrototype>>? OnPlaySelected;

    private EntityUid? _audio;
    private float _lockTimer;

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        MusicList.OnItemSelected += args =>
        {
            var entry = MusicList[args.ItemIndex];
            if (entry.Metadata is not string juke)
                return;

            if (_playState && _audio != null)
                OnPlaySelected?.Invoke(new ProtoId<JukeboxPrototype>(juke));
            else
                OnSongSelected?.Invoke(new ProtoId<JukeboxPrototype>(juke));
        };

        SearchBar.OnTextChanged += _ => FilterSongs();

        PlayButton.OnPressed += _ => OnPlayPressed?.Invoke(!_playState);
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();
        PrevButton.OnPressed += _ => OnPrevTrack?.Invoke();
        NextButton.OnPressed += _ => OnNextTrack?.Invoke();

        PlaybackSlider.OnReleased += _ =>
        {
            SetTime?.Invoke(PlaybackSlider.Value);
            _lockTimer = 0.5f;
        };

        VolumeSlider.OnValueChanged += _ =>
        {
            VolumeNumberLabel.Text = $"{VolumeSlider.Value:F0}%";
        };

        VolumeSlider.OnReleased += _ =>
        {
            SetVolume?.Invoke(VolumeSlider.Value);
            _lockTimer = 0.5f;
        };

        RepeatButton.OnPressed += _ =>
        {
            _repeatMode = _repeatMode switch
            {
                JukeboxRepeatMode.NoRepeat => JukeboxRepeatMode.RepeatAll,
                JukeboxRepeatMode.RepeatAll => JukeboxRepeatMode.RepeatOne,
                JukeboxRepeatMode.RepeatOne => JukeboxRepeatMode.NoRepeat,
                _ => JukeboxRepeatMode.NoRepeat
            };
            UpdateRepeatButtonText();
            OnRepeatModeChanged?.Invoke(_repeatMode);
        };

        ShuffleButton.OnToggled += args =>
        {
            OnShuffleToggled?.Invoke(args.Pressed);
            ShuffleButton.Text = args.Pressed
                ? Loc.GetString("jukebox-menu-buttonshuffle-on")
                : Loc.GetString("jukebox-menu-buttonshuffle");
        };

        VolumeSlider.MaxValue = 100f;
        SetPlayPauseButton(false, true);
    }

    private void FilterSongs()
    {
        var searchText = SearchBar.Text;
        MusicList.Clear();

        var filtered = string.IsNullOrWhiteSpace(searchText)
            ? _allSongs
            : _allSongs.Where(s => s.Name.Contains(searchText, OrdinalIgnoreCase)).ToList();

        foreach (var song in filtered)
        {
            MusicList.AddItem(song.Name, metadata: song.ID);
        }
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        _allSongs = jukeboxProtos.OrderBy(s => s.Name).ToList();
        FilterSongs();
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;
        PlayButton.Text = playing ? "⏸" : "▶";
    }

    public void SetSelectedSong(string name, float length)
    {
        SongName.Text = string.IsNullOrEmpty(name) ? "---" : name;
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    public void SetVolumeSlider(float volume)
    {
        VolumeSlider.SetValueWithoutEvent(volume);
        VolumeNumberLabel.Text = $"{volume:F0}%";
    }

    public void SetRepeatMode(JukeboxRepeatMode mode)
    {
        _repeatMode = mode;
        UpdateRepeatButtonText();
    }

    private void UpdateRepeatButtonText()
    {
        RepeatButton.Text = _repeatMode switch
        {
            JukeboxRepeatMode.NoRepeat => Loc.GetString("jukebox-menu-buttonrepeat-off"),
            JukeboxRepeatMode.RepeatAll => Loc.GetString("jukebox-menu-buttonrepeat-all"),
            JukeboxRepeatMode.RepeatOne => Loc.GetString("jukebox-menu-buttonrepeat-one"),
            _ => Loc.GetString("jukebox-menu-buttonrepeat-off")
        };
    }

    public void SetShuffleEnabled(bool enabled)
    {
        ShuffleButton.Pressed = enabled;
        ShuffleButton.Text = enabled
            ? Loc.GetString("jukebox-menu-buttonshuffle-on")
            : Loc.GetString("jukebox-menu-buttonshuffle");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
            _lockTimer -= args.DeltaSeconds;

        PlaybackSlider.Disabled = _lockTimer > 0f;
        VolumeSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\\:ss}";
        }
        else
        {
            DurationLabel.Text = "00:00 / 00:00";
        }

        if (!PlaybackSlider.Grabbed && !VolumeSlider.Grabbed)
        {
            if (audio != null || _entManager.TryGetComponent(_audio, out audio))
            {
                PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
            }
            else
            {
                PlaybackSlider.SetValueWithoutEvent(0f);
            }
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }
}