using Content.Client.GameTicking.Managers;
using Content.Shared.PDA;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Content.Shared.Popups;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Timing;
using Robust.Shared.IoC;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        [Dependency] private readonly IClipboardManager _clipboard = null!;
        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
        [Dependency] private readonly IEntityManager _entMan = default!;
        private ClientGameTicker _gameTicker = default!;

        public event Action<EntityUid>? OnProgramItemPressed;
        public event Action<EntityUid>? OnUninstallButtonPressed;
        public event Action<EntityUid>? OnInstallButtonPressed;
        public event Action<Color>? OnWallpaperColorSelected;
        public event Action<string?>? OnWallpaperPathSelected; // VG-Wallpaper

        public const int HomeView = 0;
        public const int ProgramListView = 1;
        public const int SettingsView = 2;
        public const int ProgramContentView = 3;
        public const int BootViewIndex = 4;

        private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
        private string _owner = Loc.GetString("comp-pda-ui-unknown");
        private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
        private string _stationName = Loc.GetString("comp-pda-ui-unknown");
        private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
        private string _instructions = Loc.GetString("comp-pda-ui-unknown");

        private bool _hasWallpaperColor;
        private bool _settingWallpaperColorFromState;
        private Color _wallpaperColor = Color.White;

        private int _currentView;
        private bool _bootScreenVisible;
        private CancellationTokenSource? _bootAnimationCts;
        private CancellationTokenSource? _fadeAnimationCts;

        public PdaMenu()
        {
            IoCManager.InjectDependencies(this);
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
            RobustXamlLoader.Load(this);

            ViewContainer.OnChildAdded += control => control.Visible = false;

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));
            ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));

            var popupsystem = _entMan.System<SharedPopupSystem>();
            
            HomeButton.OnPressed += _ => ToHomeScreen();

            ProgramListButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = true;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = false;
                ChangeView(ProgramListView);
            };

            SettingsButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;
                ProgramTitle.IsCurrent = false;
                ChangeView(SettingsView);
            };

            ProgramTitle.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = true;
                ChangeView(ProgramContentView);
            };

            ProgramCloseButton.OnPressed += _ =>
            {
                HideProgramHeader();
                ToHomeScreen();
            };

            PdaOwnerButton.OnPressed += _ =>
            {
                _clipboard.SetText(_pdaOwner);
                popupsystem.PopupCursor(Loc.GetString("ui-copy-text-in-pda"));
            };

            IdInfoButton.OnPressed += _ =>
            {
                _clipboard.SetText(_owner + ", " + _jobTitle);
                popupsystem.PopupCursor(Loc.GetString("ui-copy-text-in-pda"));
            };

            StationNameButton.OnPressed += _ =>
            {
                _clipboard.SetText(_stationName);
                popupsystem.PopupCursor(Loc.GetString("ui-copy-text-in-pda"));
            };

            StationAlertLevelButton.OnPressed += _ =>
            {
                _clipboard.SetText(_alertLevel);
                popupsystem.PopupCursor(Loc.GetString("ui-copy-text-in-pda"));
            };

            StationTimeButton.OnPressed += _ =>
            {
                var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
                _clipboard.SetText(stationTime.ToString("hh\\:mm\\:ss"));
                popupsystem.PopupCursor(Loc.GetString("ui-copy-text-in-pda"));
            };

            StationAlertLevelInstructionsButton.OnPressed += _ =>
            {
                _clipboard.SetText(_instructions);
                popupsystem.PopupCursor(Loc.GetString("ui-copy-text-in-pda"));
            };

            WallpaperColorSelector.OnColorChanged += color =>
            {
                if (_settingWallpaperColorFromState)
                    return;
                _hasWallpaperColor = true;
                _wallpaperColor = color.WithAlpha(1f);
                WallpaperColor = _wallpaperColor;
                if (!WallpaperColorSelector.IsGrabbed)
                    OnWallpaperColorSelected?.Invoke(_wallpaperColor);
            };

            WallpaperColorSelector.OnColorReleased += color =>
            {
                _hasWallpaperColor = true;
                _wallpaperColor = color.WithAlpha(1f);
                WallpaperColor = _wallpaperColor;
                OnWallpaperColorSelected?.Invoke(_wallpaperColor);
            };

            // VG-Wallpaper
            WallpaperDropdown.AddItem(Loc.GetString("pda-wallpaper-none"));
            WallpaperDropdown.SetItemMetadata(0, string.Empty);
            WallpaperDropdown.AddItem(Loc.GetString("pda-wallpaper-space"));
            WallpaperDropdown.SetItemMetadata(1, "/Textures/_VG/PDA/Wallpapers/space1.png");
            WallpaperDropdown.AddItem(Loc.GetString("pda-wallpaper-space2"));
            WallpaperDropdown.SetItemMetadata(2, "/Textures/_VG/PDA/Wallpapers/space2.png");
            WallpaperDropdown.AddItem(Loc.GetString("pda-wallpaper-blackhole"));
            WallpaperDropdown.SetItemMetadata(3, "/Textures/_VG/PDA/Wallpapers/blackhole.png");
            WallpaperDropdown.AddItem(Loc.GetString("pda-wallpaper-forest"));
            WallpaperDropdown.SetItemMetadata(4, "/Textures/_VG/PDA/Wallpapers/forest.png");
            WallpaperDropdown.OnItemSelected += OnWallpaperDropdownSelected;

            HideAllViews();
            BootView.Visible = false;
            BootView.Modulate = Color.White;
            
            ToHomeScreen();
        }

        private void OnWallpaperDropdownSelected(OptionButton.ItemSelectedEventArgs args)
        {
            WallpaperDropdown.SelectId(args.Id);
            var path = args.Button.GetItemMetadata(args.Id) as string;
            if (string.IsNullOrEmpty(path))
            {
                OnWallpaperPathSelected?.Invoke(null);
            }
            else
            {
                OnWallpaperPathSelected?.Invoke(path);
            }
        }

        public void ShowBootScreen(bool show)
        {
            if (show == _bootScreenVisible)
                return;

            _bootScreenVisible = show;
            if (show)
            {
                _bootAnimationCts?.Cancel();
                _bootAnimationCts = new CancellationTokenSource();
                _ = AnimateBootIcon(_bootAnimationCts.Token);
                
                BootWelcomeLabel.Text = Loc.GetString("pda-boot-welcome");
                BootView.Modulate = Color.White;
                ChangeView(BootViewIndex);
                NavigationBar.Visible = false;
                ContentFooter.Visible = false;
            }
            else
            {
                _bootAnimationCts?.Cancel();
                _bootAnimationCts = null;
                _ = FadeOutBootAndShowMain();
            }
        }

        private async Task FadeOutBootAndShowMain()
        {
            _fadeAnimationCts?.Cancel();
            _fadeAnimationCts = new CancellationTokenSource();
            var token = _fadeAnimationCts.Token;

            float opacity = 1f;
            float step = 0.05f;
            while (opacity > 0 && !token.IsCancellationRequested)
            {
                opacity -= step;
                if (opacity < 0) opacity = 0;
                BootView.Modulate = new Color(1f, 1f, 1f, opacity);
                await Task.Delay(16, token);
            }

            BootView.Visible = false;
            BootView.Modulate = Color.White;

            var mainView = ViewContainer.GetChild(HomeView);
            mainView.Visible = true;
            mainView.Modulate = new Color(1f, 1f, 1f, 0f);
            
            opacity = 0f;
            while (opacity < 1f && !token.IsCancellationRequested)
            {
                opacity += step;
                if (opacity > 1f) opacity = 1f;
                mainView.Modulate = new Color(1f, 1f, 1f, opacity);
                await Task.Delay(16, token);
            }

            for (int i = 0; i < ViewContainer.ChildCount; i++)
            {
                ViewContainer.GetChild(i).Modulate = Color.White;
            }

            ToHomeScreen();
            
            NavigationBar.Visible = true;
            ContentFooter.Visible = true;
            _bootScreenVisible = false;
            
            _fadeAnimationCts = null;
        }

        private async Task AnimateBootIcon(CancellationToken token)
        {
            float opacity = 1f;
            float step = 0.05f;
            bool increasing = false;
            
            while (!token.IsCancellationRequested)
            {
                if (increasing)
                {
                    opacity += step;
                    if (opacity >= 1f)
                    {
                        opacity = 1f;
                        increasing = false;
                    }
                }
                else
                {
                    opacity -= step;
                    if (opacity <= 0.3f)
                    {
                        opacity = 0.3f;
                        increasing = true;
                    }
                }
                
                BootIcon.Modulate = new Color(1f, 1f, 1f, opacity);
                await Task.Delay(50, token);
            }
            
            BootIcon.Modulate = Color.White;
        }

        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;

            var effectiveWallpaperColor = state.HasWallpaperColor
                ? state.WallpaperColor
                : DefaultWallpaperColor ?? state.WallpaperColor;

            WallpaperColor = state.HasWallpaperColor ? state.WallpaperColor : null;
            if (!WallpaperColorSelector.IsGrabbed &&
                (state.HasWallpaperColor != _hasWallpaperColor ||
                !ColorsClose(effectiveWallpaperColor, _wallpaperColor)))
            {
                _settingWallpaperColorFromState = true;
                WallpaperColorSelector.Color = effectiveWallpaperColor;
                _settingWallpaperColorFromState = false;
            }

            _hasWallpaperColor = state.HasWallpaperColor;
            _wallpaperColor = effectiveWallpaperColor;
            
            // VG-Wallpaper: обновляем обои
            WallpaperPath = state.WallpaperPath;

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;
                PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                    ("actualOwnerName", _pdaOwner)));
                PdaOwnerLabel.Visible = true;
            }
            else
            {
                PdaOwnerLabel.Visible = false;
            }

            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
                _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", _owner),
                    ("jobTitle", _jobTitle)));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", _stationName)));

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));

            var alertLevel = state.PdaOwnerInfo.StationAlertLevel;
            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            var alertLevelKey = alertLevel != null ? $"alert-level-{alertLevel}" : "alert-level-unknown";
            _alertLevel = Loc.GetString(alertLevelKey);

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", _alertLevel)));

            _instructions = Loc.GetString($"{alertLevelKey}-instructions");
            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", _instructions)));

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            EjectPaiButton.IsActive = state.HasPai;
            ActivateMusicButton.Visible = state.CanPlayMusic;
            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;
        }

        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
        {
            ProgramList.RemoveAllChildren();
            if (programs.Count == 0)
            {
                ProgramList.AddChild(new Label()
                {
                    Text = Loc.GetString("comp-pda-io-no-programs-available"),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    VerticalExpand = true
                });
                return;
            }

            var row = CreateProgramListRow();
            var itemCount = 1;
            ProgramList.AddChild(row);

            foreach (var (uid, component) in programs)
            {
                if (itemCount % 2 != 0)
                {
                    row = CreateProgramListRow();
                    ProgramList.AddChild(row);
                }

                var item = new PdaProgramItem();
                if (component.Icon is not null)
                    item.Icon.SetFromSpriteSpecifier(component.Icon);
                item.OnPressed += _ => OnProgramItemPressed?.Invoke(uid);

                switch (component.InstallationStatus)
                {
                    case InstallationStatus.Cartridge:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                        item.InstallButton.OnPressed += _ => OnInstallButtonPressed?.Invoke(uid);
                        break;
                    case InstallationStatus.Installed:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                        item.InstallButton.OnPressed += _ => OnUninstallButtonPressed?.Invoke(uid);
                        break;
                }

                item.ProgramName.Text = Loc.GetString(component.ProgramName);
                item.SetHeight = 20;
                row.AddChild(item);
                itemCount++;
            }

            if (itemCount % 2 == 0)
                row.AddChild(new Control() { HorizontalExpand = true });
        }

        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            ChangeView(HomeView);
        }

        public void HideProgramHeader()
        {
            ProgramTitle.IsCurrent = false;
            ProgramTitle.Visible = false;
            ProgramCloseButton.Visible = false;
            ProgramListButton.Visible = true;
            SettingsButton.Visible = true;
        }

        public void ToProgramView(string title)
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            ProgramTitle.IsCurrent = true;
            ProgramTitle.Visible = true;
            ProgramCloseButton.Visible = true;
            ProgramListButton.Visible = false;
            SettingsButton.Visible = false;
            ProgramTitle.LabelText = title;
            ChangeView(ProgramContentView);
        }

        public void ChangeView(int view)
        {
            if (ViewContainer.ChildCount <= view)
                return;
            if (_currentView >= 0 && _currentView < ViewContainer.ChildCount)
                ViewContainer.GetChild(_currentView).Visible = false;
            ViewContainer.GetChild(view).Visible = true;
            _currentView = view;
        }

        private static BoxContainer CreateProgramListRow()
        {
            return new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };
        }

        private void HideAllViews()
        {
            foreach (var view in ViewContainer.Children)
                view.Visible = false;
        }

        private static bool ColorsClose(Color a, Color b)
        {
            const float epsilon = 0.001f;
            return Math.Abs(a.R - b.R) < epsilon
                && Math.Abs(a.G - b.G) < epsilon
                && Math.Abs(a.B - b.B) < epsilon
                && Math.Abs(a.A - b.A) < epsilon;
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);
            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));
        }
    }
}