using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Shared.Utility;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{
    private Color? _defaultWallpaperColor;
    private Color? _wallpaperColor;
    private string? _wallpaperPath;

    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();
        set => Background.ModulateSelfOverride = Color.FromHex(value, Color.White);
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();
        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();
        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public Color? WallpaperColor
    {
        get => _wallpaperColor;
        set
        {
            _wallpaperColor = value;
            UpdateWallpaper();
        }
    }

    public Color? DefaultWallpaperColor
    {
        get => _defaultWallpaperColor;
        set
        {
            _defaultWallpaperColor = value;
            UpdateWallpaper();
        }
    }

    public string? WallpaperPath
    {
        get => _wallpaperPath;
        set
        {
            _wallpaperPath = value;
            UpdateWallpaper();
        }
    }

    public PdaWindow()
    {
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }

    private void UpdateWallpaper()
    {
        if (!string.IsNullOrEmpty(_wallpaperPath))
        {
            SetWallpaper(_wallpaperPath);
        }
        else
        {
            ContentBackground.ModulateSelfOverride = _wallpaperColor ?? _defaultWallpaperColor;
            ContentBackground.PanelOverride = null;
        }
    }

    private void SetWallpaper(string path)
    {
        try
        {
            var resCache = IoCManager.Resolve<IResourceCache>();
        
            if (resCache.TryGetResource<TextureResource>(new ResPath(path), out var textureResource))
            {
                var styleBox = new StyleBoxTexture();
                styleBox.Texture = textureResource.Texture;
                styleBox.SetPatchMargin(StyleBox.Margin.All, 0);
            
                ContentBackground.ModulateSelfOverride = Color.White;
                ContentBackground.PanelOverride = styleBox;
            
                if (ContentBackground is PanelContainer panel)
                {
                    panel.ModulateSelfOverride = Color.White;
                    panel.Modulate = Color.White;
                }
            }
            else
            {
                ContentBackground.ModulateSelfOverride = _wallpaperColor ?? _defaultWallpaperColor;
                ContentBackground.PanelOverride = null;
            }
        }
        catch (Exception)
        {
            ContentBackground.ModulateSelfOverride = _wallpaperColor ?? _defaultWallpaperColor;
            ContentBackground.PanelOverride = null;
        }
    }
}