using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterSetupWindow : DefaultWindow
{
    public CharacterSetupGui SetupGui { get; private set; }

    public CharacterSetupWindow(CharacterSetupGui setupGui)
    {
        RobustXamlLoader.Load(this);
        SetupGui = setupGui;
        Contents.AddChild(setupGui);
        SetSize = new Vector2(1400, 820);
    }
}