using System.IO;
using System.Linq;
using System.Numerics;
using System.Threading;
using Content.Client.ADT.Lobby.UI;
using Content.Client._VG.Sponsors;
using Content.Client.ADT.Traits.UI;
using Content.Client.Guidebook;
using System.Reflection;
using Content.Client.Humanoid;
using Content.Client.Lobby.UI.Loadouts;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Stylesheets;
using Content.Client.Sprite;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.ADT.CCVar;
using Content.Client._VG.Sponsors;
using Content.Shared.CCVar;
using Content.Shared.Clothing;
using Content.Shared.Corvax.CCCVars;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Mobs;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Timer = Robust.Shared.Timing.Timer;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Toolshed.Errors;
using Robust.Shared.Utility;
using Direction = Robust.Shared.Maths.Direction;
using static Content.Client.Corvax.SponsorOnlyHelpers;
using Content.Client.Corvax.TTS;
using Content.Client.ADT.UserInterface.Controls;
using Content.Client.ADT.CharecterFlavor;
using Content.Shared.ADT.CharecterFlavor;
using Content.Client._VG.Humanoid; // VG-Tweak

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly SponsorsManager _sponsorsManager = default!;
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;
        private readonly IDynamicTypeFactory _factory;
        [Dependency] private readonly DocumentParsingManager _parsingMan = default!;

        private readonly SpriteSystem _sprite;

        private int _maxNameLength;
        private bool _allowFlavorText;

        private FlavorText.FlavorText? _flavorText;
        private TextEdit? _flavorTextEdit;

        private BaseLoadoutWindow? _loadoutWindow;
        private TTSTab? _ttsTab;
        private bool _exporting;
        private bool _imaging;

        public event Action? Save;
        public event Action? ProfileChanged; // VG-Tweak

        public EntityUid PreviewDummy;
        public JobPrototype? JobOverride;
        public int? CharacterSlot;
        public HumanoidCharacterProfile? Profile;

        private List<SpeciesPrototype> _species = new();
        private List<(string, RequirementsSelector)> _jobPriorities = new();
        private readonly Dictionary<string, BoxContainer> _jobCategories;
        private Direction _previewRotation = Direction.North;
        private LegacyColorSelectorSliders _rgbSkinColorSelector;
        private bool _isDirty;
        private static readonly ProtoId<GuideEntryPrototype> DefaultSpeciesGuidebook = "Species";
        public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;
        private ISawmill _sawmill;
        private SpeciesWindow? _speciesWindow;

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings,
            IDynamicTypeFactory factory)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _factory = factory;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            ImportButton.OnPressed += args => ImportProfile();
            ExportButton.OnPressed += args => ExportProfile();
            ExportImageButton.OnPressed += args => ExportImage();
            OpenImagesButton.OnPressed += args => _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            ResetButton.OnPressed += args => SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            SaveButton.OnPressed += args => Save?.Invoke();

            #region Left
            #region Name
            NameEdit.OnTextChanged += args => SetName(args.Text);
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => RandomizeEverything();
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");
            #endregion Name

            #region Appearance
            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex
            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };
            #endregion

            #region Age
            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;
                SetAge(newAge);
            };
            #endregion

            #region Gender
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };
            #endregion

            // ADT Barks Start
            #region Voice
            if (configurationManager.GetCVar(ADTCCVars.BarksEnabled))
            {
                BarksContainer.Visible = true;
                InitializeBarks();
            }
            #endregion
            // ADT Barks End

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                UpdateHairPickers();
                OnSkinColorOnValueChanged();
            };

            // ADT Species Window start
            NewSpeciesButton.OnToggled += args =>
            {
                if (Profile == null)
                    return;
                _speciesWindow?.Dispose();
                if (!args.Pressed)
                {
                    _speciesWindow = null;
                }
                else
                {
                    _speciesWindow = new(Profile, _prototypeManager, _entManager, _controller, _resManager, _parsingMan);
                    _speciesWindow.OpenCenteredLeft();
                    var oldProfile = Profile.Clone();
                    _speciesWindow.ChooseAction += args =>
                    {
                        SetSpecies(args);
                        OnSkinColorOnValueChangedKeepColor(oldProfile);
                        UpdateHairPickers();
                        _speciesWindow?.Dispose();
                        _speciesWindow = null;
                        var name1 = _prototypeManager.Index(Profile?.Species ?? "Human").Name;
                        NewSpeciesButton.Text = Loc.GetString(name1);
                        NewSpeciesButton.Pressed = false;
                        this.SetDefaultLanguages();
                    };
                    _speciesWindow.OnClose += () =>
                    {
                        NewSpeciesButton.Pressed = false;
                        _speciesWindow = null;
                    };
                }
            };
            // ADT Species Window end

            #region Skin
            Skin.OnValueChanged += _ => OnSkinColorOnValueChanged();
            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new LegacyColorSelectorSliders());
            // ADT-Tweak-Start
            // _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
            // ADT-Tweak-End
            _rgbSkinColorSelector.OnColorChanged += _ => OnSkinColorOnValueChanged();
            #endregion

            #region Hair
            HairStylePicker.OnMarkingSelect += newStyle =>
            {
                if (Profile is null) return;
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithHairStyleName(newStyle.id));
                ReloadPreview();
            };

            HairStylePicker.OnColorChanged += newColor =>
            {
                if (Profile is null) return;
                var hairColorList = new List<Color>(newColor.marking.MarkingColors); // ADT-tweak
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithHairColor(hairColorList)); // ADT-tweak
                ReloadPreview();
            };

            FacialHairPicker.OnMarkingSelect += newStyle =>
            {
                if (Profile is null) return;
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithFacialHairStyleName(newStyle.id));
                ReloadPreview();
            };

            FacialHairPicker.OnColorChanged += newColor =>
            {
                if (Profile is null) return;
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithFacialHairColor(newColor.marking.MarkingColors[0]));
                ReloadPreview();
            };

            HairStylePicker.OnSlotRemove += _ =>
            {
                if (Profile is null) return;
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithHairStyleName(HairStyles.DefaultHairStyle));
                UpdateHairPickers();
                ReloadPreview();
            };

            FacialHairPicker.OnSlotRemove += _ =>
            {
                if (Profile is null) return;
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithFacialHairStyleName(HairStyles.DefaultFacialHairStyle));
                UpdateHairPickers();
                ReloadPreview();
            };

            HairStylePicker.OnSlotAdd += delegate()
            {
                if (Profile is null) return;
                var hair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.Hair, Profile.Species).Keys.FirstOrDefault();
                if (string.IsNullOrEmpty(hair)) return;
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithHairStyleName(hair));
                UpdateHairPickers();
                ReloadPreview();
            };

            FacialHairPicker.OnSlotAdd += delegate()
            {
                if (Profile is null) return;
                var hair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.FacialHair, Profile.Species).Keys.FirstOrDefault();
                if (string.IsNullOrEmpty(hair)) return;
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithFacialHairStyleName(hair));
                UpdateHairPickers();
                ReloadPreview();
            };
            #endregion

            #region SpawnPriority
            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };
            #endregion

            #region Eyes
            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null) return;
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithEyeColor(newColor));
                ReloadProfilePreview();
            };
            #endregion
            #endregion

            // ADT Languages start
            #region Languages
            RefreshLanguages();
            LanguagesSearchBar.OnTextChanged += OnLanguagesSearchTextChanged;
            #endregion
            // ADT Languages end

            #region Jobs
            PreferenceUnavailableButton.AddItem(Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"), (int)PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button", ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))), (int)PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);
                SetDirty();
            };

            _jobCategories = new Dictionary<string, BoxContainer>();
            RefreshAntags();
            RefreshJobs();
            #endregion

            RefreshTraits();
            Traits.OnTraitsChanged += OnTraitsSelectionChanged; // ADT-Tweak new Traits

            #region Markings // VG-Tweak Start
            Markings.ExcludeCategories = new HashSet<MarkingCategories> { MarkingCategories.Hair, MarkingCategories.FacialHair };
            Markings.OnMarkingAdded += OnMarkingSetChanged;
            Markings.OnMarkingRemoved += OnMarkingSetChanged;
            Markings.OnMarkingColorChange += OnMarkingSetChanged;
            Markings.OnMarkingRankChange += OnMarkingSetChanged;
            #endregion // VG-Tweak End

            RefreshFlavorText();
            RefreshVoiceTab(); // Corvax-TTS

            // ADT-Tweak start. Корректно вставляем вкладки для кастомизации персонажа и их названия
            #region InvokeRefresh
            bool ttsIsEnabled = _cfgManager.GetCVar(CCCVars.TTSEnabled);
            int valueTTSEnable = ttsIsEnabled ? 1 : 0;

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));
            if (ttsIsEnabled)
                TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-voice-tab"));

            TabContainer.SetTabTitle(1 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-languages-tab"));
            TabContainer.SetTabTitle(2 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-jobs-tab"));
            TabContainer.SetTabTitle(3 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-antags-tab"));
            TabContainer.SetTabTitle(4 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-traits-tab"));
            TabContainer.SetTabTitle(5 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-markings-tab"));

            if (_allowFlavorText)
                TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));
            #endregion
            // ADT-Tweak end.

            #region Dummy
            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };
            #endregion
            #endregion

            ShowClothes.OnToggled += args => ReloadPreview();
            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;
            UpdateSpeciesGuidebookIcon();
            ReloadPreview();
            IsDirty = false;
        }

        #region Markings // VG-Tweak Start

        private void OnMarkingSetChanged(MarkingSet set)
        {
            if (Profile == null) return;
            var markings = set.GetForwardEnumerator().ToList();
            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(markings));

            ReloadPreview();
            
            // VG-Tweak: Обновление превью в кастомном окне
            var window = UserInterfaceManager.GetUIController<LobbyUIController>().GetSetupWindow();
            window?.ForceRefreshPreview();
        }

        private void UpdateMarkings()
        {
            if (Profile == null) return;
            var speciesProto = _prototypeManager.Index<SpeciesPrototype>(Profile.Species);
            var markingSet = new MarkingSet(Profile.Appearance.Markings, speciesProto.MarkingPoints, _markingManager, _prototypeManager);
            Markings.SetData(markingSet, Profile.Species, Profile.Sex, Profile.Appearance.SkinColor, Profile.Appearance.EyeColor);
            Markings.ForceRebuild();
        }

        #endregion // VG-Tweak End

        #region Refresh

        public void RefreshFlavorText()
        {
            if (_allowFlavorText)
            {
                if (_flavorText != null)
                    return;

                _flavorText = new FlavorText.FlavorText();
                TabContainer.AddChild(_flavorText);
                TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));
                _flavorTextEdit = _flavorText.CFlavorTextInput;

                // ADT-tweak-start
                _flavorText.OnHeadshotUrlChanged += OnHeadshotUrlChange;
                _flavorText.OnPreviewRequested += OnFlavorPreviewRequested;
                // ADT-tweak-end
                _flavorText.OnFlavorTextChanged += OnFlavorTextChange;
            }
            else
            {
                if (_flavorText == null)
                    return;

                TabContainer.RemoveChild(_flavorText);
                _flavorText.OnFlavorTextChanged -= OnFlavorTextChange;
                // ADT-tweak-start
                _flavorText.OnHeadshotUrlChanged -= OnHeadshotUrlChange;
                _flavorText.OnPreviewRequested -= OnFlavorPreviewRequested;
                // ADT-tweak-end
                _flavorText.Dispose();
                _flavorTextEdit?.Dispose();
                _flavorTextEdit = null;
                _flavorText = null;
            }
        }

        // Corvax-TTS-Start
        #region Voice
        private void RefreshVoiceTab()
        {
            if (!_cfgManager.GetCVar(CCCVars.TTSEnabled))
                return;

            _ttsTab = new TTSTab();
            var children = new List<Control>();
            foreach (var child in TabContainer.Children)
                children.Add(child);

            TabContainer.RemoveAllChildren();

            for (int i = 0; i < children.Count; i++)
            {
                if (i == 1) // Set the tab to the 2nd place.
                {
                    TabContainer.AddChild(_ttsTab);
                }
                TabContainer.AddChild(children[i]);
            }

            _ttsTab.OnVoiceSelected += voiceId =>
            {
                SetVoice(voiceId);
                _ttsTab.SetSelectedVoice(voiceId);
            };

            _ttsTab.OnPreviewRequested += voiceId =>
            {
                _entManager.System<TTSSystem>().RequestPreviewTTS(voiceId);
            };
        }

        private void UpdateTTSVoicesControls()
        {
            if (Profile is null || _ttsTab is null)
                return;

            _ttsTab.UpdateControls(Profile, Profile.Sex, Profile.Species); //ADT-tweak: добавлена раса
            _ttsTab.SetSelectedVoice(Profile.Voice);
        }
        #endregion
        // Corvax-TTS-End

        public void RefreshTraits()
        {
            if (Profile != null)
            // ADT-Tweak start new Traits
            {
                var selectedTraits = new HashSet<ProtoId<TraitPrototype>>(Profile.TraitPreferences.Count);
                foreach (var traitId in Profile.TraitPreferences)
                {
                    if (_prototypeManager.HasIndex(traitId))
                    {
                        selectedTraits.Add(new ProtoId<TraitPrototype>(traitId));
                    }
                }

                Traits.SetSelectedTraits(selectedTraits, Profile);
                Traits.UpdateRequirements(Profile, jobId: null);
            }
            else
            {
                Traits.SetSelectedTraits(new HashSet<ProtoId<TraitPrototype>>(), Profile);
            }
        }

        private void OnTraitsSelectionChanged(HashSet<ProtoId<TraitPrototype>> traits)
        {
            if (Profile is null)
                return;

            foreach (var existingTrait in Profile.TraitPreferences)
            {
                Profile = Profile.WithoutTraitPreference(existingTrait, _prototypeManager);
            }

            foreach (var trait in traits)
            // ADT-Tweak end new Traits
            {
                Profile = Profile.WithTraitPreference(trait.Id, _prototypeManager);
            }

            SetDirty();
        }

        public void RefreshSpecies()
        {
            SpeciesButton.Clear();
            _species.Clear();

            _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>().Where(o => o.RoundStart));
            _species.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
            var speciesIds = _species.Select(o => o.ID).ToList();

            for (var i = 0; i < _species.Count; i++)
            {
                var name = Loc.GetString(_species[i].Name);

                if (_species[i].SponsorOnly) // Corvax-Sponsors
                    name += GetSponsorOnlySuffix();

                SpeciesButton.AddItem(name, i);

                if (Profile?.Species.Equals(_species[i].ID) == true)
                {
                    SpeciesButton.SelectId(i);

                    // ADT Species Window start
                    NewSpeciesButton.Text = name;
                    NewSpeciesButton.Pressed = false;
                    _speciesWindow?.Dispose();
                    // ADT Species Window end
                }
            }

            if (Profile != null)
            {
                if (!speciesIds.Contains(Profile.Species))
                {
                    SetSpecies(SharedHumanoidAppearanceSystem.DefaultSpecies);
                }
            }
        }

        public void RefreshAntags()
        {
            AntagList.RemoveAllChildren();
            var items = new[]
            {
                ("humanoid-profile-editor-antag-preference-yes-button", 0),
                ("humanoid-profile-editor-antag-preference-no-button", 1)
            };

            foreach (var antag in _prototypeManager.EnumeratePrototypes<AntagPrototype>().OrderBy(a => Loc.GetString(a.Name)))
            {
                if (!antag.SetPreference)
                    continue;

                var antagContainer = new BoxContainer()
                {
                    Orientation = LayoutOrientation.Horizontal,
                };

                var selector = new RequirementsSelector()
                {
                    Margin = new Thickness(3f, 3f, 3f, 0f),
                };
                selector.OnOpenGuidebook += OnOpenGuidebook;

                var title = Loc.GetString(antag.Name);
                var description = Loc.GetString(antag.Objective);
                selector.Setup(items, title, 250, description, guides: antag.Guides);
                selector.Select(Profile?.AntagPreferences.Contains(antag.ID) == true ? 0 : 1);

                if (!_requirements.IsAllowed(antag, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var reason))
                {
                    selector.LockRequirements(reason);
                    Profile = Profile?.WithAntagPreference(antag.ID, false);
                    SetDirty();
                }
                else
                {
                    selector.UnlockRequirements();
                }

                selector.OnSelected += preference =>
                {
                    Profile = Profile?.WithAntagPreference(antag.ID, preference == 0);
                    SetDirty();
                };

                antagContainer.AddChild(selector);
                antagContainer.AddChild(new Button()
                {
                    Disabled = true,
                    Text = Loc.GetString("loadout-window"),
                    HorizontalAlignment = HAlignment.Right,
                    Margin = new Thickness(3f, 0f, 0f, 0f),
                });

                AntagList.AddChild(antagContainer);
            }
        }

        public void RefreshJobs()
        {
            JobList.RemoveAllChildren();
            _jobCategories.Clear();
            _jobPriorities.Clear();
            var firstCategory = true;

            var departments = new List<DepartmentPrototype>();
            foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
            {
                if (department.EditorHidden)
                    continue;
                departments.Add(department);
            }

            departments.Sort(DepartmentUIComparer.Instance);

            var items = new[]
            {
                ("humanoid-profile-editor-job-priority-never-button", (int)JobPriority.Never),
                ("humanoid-profile-editor-job-priority-low-button", (int)JobPriority.Low),
                ("humanoid-profile-editor-job-priority-medium-button", (int)JobPriority.Medium),
                ("humanoid-profile-editor-job-priority-high-button", (int)JobPriority.High),
            };

            foreach (var department in departments)
            {
                var departmentName = Loc.GetString(department.Name);

                if (!_jobCategories.TryGetValue(department.ID, out var category))
                {
                    category = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Vertical,
                        Name = department.ID,
                        ToolTip = Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip",
                            ("departmentName", departmentName))
                    };

                    if (firstCategory)
                    {
                        firstCategory = false;
                    }
                    else
                    {
                        category.AddChild(new Control
                        {
                            MinSize = new Vector2(0, 23),
                        });
                    }

                    category.AddChild(new PanelContainer
                    {
                        PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                        Children =
                        {
                            new Label
                            {
                                Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                                    ("departmentName", departmentName)),
                                Margin = new Thickness(5f, 0, 0, 0)
                            }
                        }
                    });

                    _jobCategories[department.ID] = category;
                    JobList.AddChild(category);
                }

                var jobs = department.Roles.Select(jobId => _prototypeManager.Index(jobId))
                    .Where(job => job.SetPreference)
                    .ToArray();

                Array.Sort(jobs, JobUIComparer.Instance);

                foreach (var job in jobs)
                {
                    var jobContainer = new BoxContainer()
                    {
                        Orientation = LayoutOrientation.Horizontal,
                    };

                    var selector = new RequirementsSelector()
                    {
                        Margin = new Thickness(3f, 3f, 3f, 0f),
                    };
                    selector.OnOpenGuidebook += OnOpenGuidebook;

                    var icon = new TextureRect
                    {
                        TextureScale = new Vector2(2, 2),
                        VerticalAlignment = VAlignment.Center
                    };
                    var jobIcon = _prototypeManager.Index(job.Icon);
                    icon.Texture = _sprite.Frame0(jobIcon.Icon);
                    selector.Setup(items, job.LocalizedName, 200, job.LocalizedDescription, icon, job.Guides);

                    if (!_requirements.IsAllowed(job, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var reason))
                    {
                        selector.LockRequirements(reason);
                    }
                    else
                    {
                        selector.UnlockRequirements();
                    }

                    selector.OnSelected += selectedPrio =>
                    {
                        var selectedJobPrio = (JobPriority)selectedPrio;
                        Profile = Profile?.WithJobPriority(job.ID, selectedJobPrio);

                        foreach (var (jobId, other) in _jobPriorities)
                        {
                            if (jobId == job.ID)
                            {
                                other.Select(selectedPrio);
                                continue;
                            }

                            if (selectedJobPrio != JobPriority.High || (JobPriority)other.Selected != JobPriority.High)
                                continue;

                            other.Select((int)JobPriority.Medium);
                            Profile = Profile?.WithJobPriority(jobId, JobPriority.Medium);
                        }

                        ReloadPreview();
                        UpdateJobPriorities();
                        SetDirty();
                    };

                    var loadoutWindowBtn = new Button()
                    {
                        Text = Loc.GetString("loadout-window"),
                        HorizontalAlignment = HAlignment.Right,
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(3f, 3f, 0f, 0f),
                    };

                    var collection = IoCManager.Instance!;
                    var protoManager = collection.Resolve<IPrototypeManager>();

                    // ADT SAI Custom start
                    if (job.LoadoutButtonText != null)
                        loadoutWindowBtn.Text = Loc.GetString(job.LoadoutButtonText);
                    // ADT SAI Custom end

                    if (!protoManager.TryIndex<RoleLoadoutPrototype>(LoadoutSystem.GetJobPrototype(job.ID), out var roleLoadoutProto))
                    {
                        loadoutWindowBtn.Disabled = true;
                    }
                    else
                    {
                        loadoutWindowBtn.OnPressed += args =>
                        {
                            RoleLoadout? loadout = null;
                            Profile?.Loadouts.TryGetValue(LoadoutSystem.GetJobPrototype(job.ID), out loadout);
                            loadout = loadout?.Clone();
                            if (loadout == null)
                            {
                                loadout = new RoleLoadout(roleLoadoutProto.ID);
                                loadout.SetDefault(Profile, _playerManager.LocalSession, _prototypeManager);
                            }

                            // ADT SAI Custom start
                            if (job.LoadoutOverride != null)
                                OpenLoadoutOverride(job, loadout, job.LoadoutOverride);
                            else
                                OpenLoadout(job, loadout, roleLoadoutProto);
                            // ADT SAI Custom end
                        };
                    }

                    _jobPriorities.Add((job.ID, selector));
                    jobContainer.AddChild(selector);
                    jobContainer.AddChild(loadoutWindowBtn);
                    category.AddChild(jobContainer);
                }
            }

            UpdateJobPriorities();
        }

        public void RefreshLoadouts()
        {
            _loadoutWindow?.Dispose();
        }

        #endregion

        #region Voice

        private void RefreshVoiceTab()
        {
            if (!_cfgManager.GetCVar(CCCVars.TTSEnabled))
                return;

            _ttsTab = new TTSTab();
            var children = new List<Control>();
            foreach (var child in TabContainer.Children)
                children.Add(child);

            TabContainer.RemoveAllChildren();

            for (int i = 0; i < children.Count; i++)
            {
                if (i == 1)
                {
                    TabContainer.AddChild(_ttsTab);
                }
                TabContainer.AddChild(children[i]);
            }

            _ttsTab.OnVoiceSelected += voiceId =>
            {
                SetVoice(voiceId);
                _ttsTab.SetSelectedVoice(voiceId);
            };

            _ttsTab.OnPreviewRequested += voiceId =>
            {
                _entManager.System<TTSSystem>().RequestPreviewTTS(voiceId);
            };
        }

        private void UpdateTTSVoicesControls()
        {
            if (Profile is null || _ttsTab is null)
                return;

            _ttsTab.UpdateControls(Profile, Profile.Sex, Profile.Species);
            _ttsTab.SetSelectedVoice(Profile.Voice);
        }

        #endregion

        #region Profile Management

        private void SetDirty()
        {
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            IsDirty = true;
            ProfileChanged?.Invoke(); // VG-Tweak
        }

        private void ReloadPreview()
        {
            _entManager.DeleteEntity(PreviewDummy);
            PreviewDummy = EntityUid.Invalid;

            if (Profile == null || !_prototypeManager.HasIndex(Profile.Species))
                return;

            PreviewDummy = _controller.LoadProfileEntity(Profile, JobOverride, ShowClothes.Pressed);
            SpriteView.SetEntity(PreviewDummy);
            _entManager.System<MetaDataSystem>().SetEntityName(PreviewDummy, Profile.Name);

            SetDirty();
        }

        public void ResetToDefault()
        {
            SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            Markings.ForceRebuild(); // VG-Tweak
            UpdateTTSVoicesControls();
            UpdateBarkVoicesControls();
            UpdateHairPickers();

            RefreshLanguages();
            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();

            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            }
        }

        private void ReloadProfilePreview()
        {
            if (Profile == null || !_entManager.EntityExists(PreviewDummy))
                return;

            _entManager.System<HumanoidAppearanceSystem>().LoadProfile(PreviewDummy, Profile);
            SetDirty();
        }

        #endregion

        #region UI Update Methods

        private void UpdateNameEdit()
        {
            NameEdit.Text = Profile?.Name ?? "";
        }

        private void UpdateFlavorTextEdit()
        {
            if (_flavorTextEdit != null)
            {
                _flavorTextEdit.TextRope = new Rope.Leaf(Profile?.FlavorText ?? "");
                // ADT-Tweak-start
                if (_flavorText == null)
                    return;
                _flavorText.CHeadshotUrlInput.Text = Profile?.HeadshotUrl ?? "";
                // ADT-Tweak-end
            }
        }

        private void UpdateAgeEdit()
        {
            AgeEdit.Text = Profile?.Age.ToString() ?? "";
        }

        private void UpdateJobPriorities()
        {
            foreach (var (jobId, prioritySelector) in _jobPriorities)
            {
                var priority = Profile?.JobPriorities.GetValueOrDefault(jobId, JobPriority.Never) ?? JobPriority.Never;
                prioritySelector.Select((int)priority);
            }
        }

        private void UpdateSexControls()
        {
            if (Profile == null)
                return;

            SexButton.Clear();

            var sexes = new List<Sex>();

            if (_prototypeManager.Resolve<SpeciesPrototype>(Profile.Species, out var speciesProto))
            {
                foreach (var sex in speciesProto.Sexes)
                {
                    sexes.Add(sex);
                }
            }
            else
            {
                sexes.Add(Sex.Unsexed);
            }

            foreach (var sex in sexes)
            {
                SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int)sex);
            }

            if (sexes.Contains(Profile.Sex))
                SexButton.SelectId((int)Profile.Sex);
            else
                SexButton.SelectId((int)sexes[0]);
        }

        private void UpdateSkinColor()
        {
            if (Profile == null)
                return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var strategy = _prototypeManager.Index(skin).Strategy;

            switch (strategy.InputType)
            {
                case SkinColorationStrategyInput.Unary:
                    {
                        if (!Skin.Visible)
                        {
                            Skin.Visible = true;
                            RgbSkinColorContainer.Visible = false;
                        }
                        Skin.Value = strategy.ToUnary(Profile.Appearance.SkinColor);
                        break;
                    }
                case SkinColorationStrategyInput.Color:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }
                        _rgbSkinColorSelector.Color = strategy.ClosestSkinColor(Profile.Appearance.SkinColor);
                        break;
                    }
            }
        }

        public void UpdateSpeciesGuidebookIcon()
        {
            SpeciesInfoButton.StyleClasses.Clear();

            var species = Profile?.Species;
            if (species is null)
                return;

            if (!_prototypeManager.Resolve<SpeciesPrototype>(species, out var speciesProto))
                return;

            if (!_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                return;

            const string style = "SpeciesInfoDefault";
            SpeciesInfoButton.StyleIdentifier = style;
        }

        private void UpdateGenderControls()
        {
            if (Profile == null)
                return;

            PronounsButton.SelectId((int)Profile.Gender);
        }

        private void UpdateSpawnPriorityControls()
        {
            if (Profile == null)
                return;

            SpawnPriorityButton.SelectId((int)Profile.SpawnPriority);
        }

        private void UpdateHairPickers()
        {
            if (Profile == null)
                return;

            var hairMarking = Profile.Appearance.HairStyleId == HairStyles.DefaultHairStyle
                ? new List<Marking>()
                : new() { new(Profile.Appearance.HairStyleId, Profile.Appearance.HairColor) }; // ADT-tweak

            var facialHairMarking = Profile.Appearance.FacialHairStyleId == HairStyles.DefaultFacialHairStyle
                ? new List<Marking>()
                : new() { new(Profile.Appearance.FacialHairStyleId, new List<Color>() { Profile.Appearance.FacialHairColor }) };

            HairStylePicker.UpdateData(hairMarking, Profile.Species, 1);
            FacialHairPicker.UpdateData(facialHairMarking, Profile.Species, 1);
        }

        private void UpdateEyePickers()
        {
            if (Profile == null)
                return;

            EyeColorPicker.SetData(Profile.Appearance.EyeColor);
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        #endregion

        #region Actions

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }

        private void RandomizeEverything()
        {
            Profile = HumanoidCharacterProfile.Random();
            SetProfile(Profile, CharacterSlot);
            SetDirty();
        }

        private void RandomizeName()
        {
            if (Profile == null) return;
            var name = HumanoidCharacterProfile.GetName(Profile.Species, Profile.Gender);
            SetName(name);
            UpdateNameEdit();
        }

        private void SetAge(int newAge)
        {
            Profile = Profile?.WithAge(newAge);
            ReloadPreview();
        }

        private void SetSex(Sex newSex)
        {
            Profile = Profile?.WithSex(newSex);
            switch (newSex)
            {
                case Sex.Male:
                    Profile = Profile?.WithGender(Gender.Male);
                    break;
                case Sex.Female:
                    Profile = Profile?.WithGender(Gender.Female);
                    break;
                default:
                    Profile = Profile?.WithGender(Gender.Epicene);
                    break;
            }
            UpdateGenderControls();
            UpdateTTSVoicesControls();
            UpdateMarkings(); // VG-Tweak
            ReloadPreview();
        }

        private void SetGender(Gender newGender)
        {
            Profile = Profile?.WithGender(newGender);
            ReloadPreview();
        }

        private void SetVoice(string newVoice)
        {
            Profile = Profile?.WithVoice(newVoice);
            IsDirty = true;
        }

        // ADT Barks start
        private void SetBarkProto(string prototype)
        {
            Profile = Profile?.WithBarkProto(prototype);
            ReloadPreview();
            SetDirty();
        }

        private void SetBarkPitch(float pitch)
        {
            Profile = Profile?.WithBarkPitch(Math.Clamp(pitch, _cfgManager.GetCVar(ADTCCVars.BarksMinPitch), _cfgManager.GetCVar(ADTCCVars.BarksMaxPitch)));
            ReloadPreview();
            SetDirty();
        }

        private void SetBarkMinVariation(float variation)
        {
            Profile = Profile?.WithBarkMinVariation(Math.Clamp(variation, _cfgManager.GetCVar(ADTCCVars.BarksMinDelay), Profile.Bark.MaxVar));
            ReloadPreview();
            SetDirty();
        }

        private void SetBarkMaxVariation(float variation)
        {
            Profile = Profile?.WithBarkMaxVariation(Math.Clamp(variation, Profile.Bark.MinVar, _cfgManager.GetCVar(ADTCCVars.BarksMaxDelay)));
            ReloadPreview();
            SetDirty();
        }
        // ADT Barks end

        private void SetSpecies(string newSpecies)
        {
            Profile = Profile?.WithSpecies(newSpecies);
            OnSkinColorOnValueChanged();
            RefreshJobs();
            RefreshLoadouts();
            UpdateSexControls();
            UpdateSpeciesGuidebookIcon();
            UpdateMarkings(); // VG-Tweak
            ReloadPreview();
        }

        private void SetName(string newName)
        {
            Profile = Profile?.WithName(newName);
            SetDirty();

            if (!IsDirty)
                return;

            _entManager.System<MetaDataSystem>().SetEntityName(PreviewDummy, newName);
        }

        private void SetSpawnPriority(SpawnPriorityPreference newSpawnPriority)
        {
            Profile = Profile?.WithSpawnPriorityPreference(newSpawnPriority);
            SetDirty();
        }

        // VG-Tweak Start
        public void SetPdaWallpaperPath(string? path)
        {
            if (Profile == null)
                return;
            Profile = Profile.WithPdaWallpaperPath(path);
            SetDirty();
        }
        // VG-Tweak End

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;
                _isDirty = value;
                UpdateSaveButton();
            }
        }

        #endregion

        #region Loadout

        private void OpenLoadout(JobPrototype? jobProto, RoleLoadout roleLoadout, RoleLoadoutPrototype roleLoadoutProto)
        {
            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
            var collection = IoCManager.Instance;

            if (collection == null || _playerManager.LocalSession == null || Profile == null)
                return;

            JobOverride = jobProto;
            var session = _playerManager.LocalSession;

            _loadoutWindow = new LoadoutWindow(Profile, roleLoadout, roleLoadoutProto, _playerManager.LocalSession, collection)
            {
                Title = Loc.GetString("loadout-window-title-loadout", ("job", $"{jobProto?.LocalizedName}")),
            };

            if (_loadoutWindow is not LoadoutWindow window) // ADT SAI Custom start
                return; // ADT SAI Custom end

            window.RefreshLoadouts(roleLoadout, session, collection); // ADT SAI Custom tweaked
            _loadoutWindow.OpenCenteredLeft();

            window.OnNameChanged += name => // ADT SAI Custom tweaked
            {
                roleLoadout.EntityName = name;
                Profile = Profile.WithLoadout(roleLoadout);
                SetDirty();
            };

            window.OnLoadoutPressed += (loadoutGroup, loadoutProto) => // ADT SAI Custom tweaked
            {
                roleLoadout.AddLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                window.RefreshLoadouts(roleLoadout, session, collection); // ADT SAI Custom tweaked
                Profile = Profile?.WithLoadout(roleLoadout);
                ReloadPreview();
            };

            window.OnLoadoutUnpressed += (loadoutGroup, loadoutProto) => // ADT SAI Custom tweaked
            {
                roleLoadout.RemoveLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                window.RefreshLoadouts(roleLoadout, session, collection); // ADT SAI Custom tweaked
                Profile = Profile?.WithLoadout(roleLoadout);
                ReloadPreview();
            };

            JobOverride = jobProto;
            ReloadPreview();

            _loadoutWindow.OnClose += () =>
            {
                JobOverride = null;
                ReloadPreview();
            };

            if (Profile is null)
                return;

            UpdateJobPriorities();
        }

        // ADT SAI Custom start
        private void OpenLoadoutOverride(JobPrototype? jobProto, RoleLoadout roleLoadout, string windowName)
        {
            _loadoutWindow?.Dispose();
            _loadoutWindow = null;

            _loadoutWindow = _factory.CreateInstance(Type.GetType($"Content.Client.Lobby.UI.Loadouts.{windowName}")!) as BaseLoadoutWindow;
            if (_loadoutWindow is not ILoadoutOverride loadoutWindow)
                return;

            loadoutWindow.Refresh(Profile, roleLoadout, _prototypeManager);
            loadoutWindow.OnValueChanged += item =>
            {
                if (roleLoadout.ExtraData.ContainsKey(item.Key))
                    roleLoadout.ExtraData[item.Key] = item.Value;
                else
                    roleLoadout.ExtraData.Add(item.Key, item.Value);

                Profile = Profile?.WithLoadout(roleLoadout);
                loadoutWindow.Refresh(Profile, roleLoadout, _prototypeManager);
                ReloadPreview();
                SetDirty();
            };

            _loadoutWindow.OpenCenteredLeft();

            JobOverride = jobProto;
            ReloadPreview();

            _loadoutWindow.OnClose += () =>
            {
                JobOverride = null;
                ReloadPreview();
            };

            if (Profile is null)
                return;

            UpdateJobPriorities();
        }
        // ADT SAI Custom end

        #endregion

        #region Flavor Text

        private void OnFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithFlavorText(content);
            SetDirty();
        }

        //ADT-tweak-start: Юрл для хэдшота
        private CancellationTokenSource? _headshotRequestCts;
        private string? _lastHeadshotUrl;

        private async void OnHeadshotUrlChange(string content)
        {
            if (Profile is null)
                return;

            var url = content.Trim();

            if (url == _lastHeadshotUrl)
                return;

            _lastHeadshotUrl = url;

            Profile = Profile.WithHeadshotUrl(url);
            SetDirty();

            _headshotRequestCts?.Cancel();
            _headshotRequestCts?.Dispose();
            _headshotRequestCts = null;

            _headshotRequestCts = new CancellationTokenSource();

            var cts = _headshotRequestCts.Token;

            try
            {
                await Timer.Delay(500, cts);
                OnHeadshotPreviewRequestedDelayed(url);
            }
            catch (OperationCanceledException)
            {
            }
        }

        private void OnHeadshotPreviewRequestedDelayed(string url)
        {
            if (Profile is null)
                return;

            if (!_entManager.EntityExists(PreviewDummy))
                return;

            var flavor = _entManager.EnsureComponent<CharacterFlavorComponent>(PreviewDummy);
            flavor.FlavorText = Profile.FlavorText ?? string.Empty;
            flavor.HeadshotUrl = url;

            var controller = UserInterfaceManager.GetUIController<CharacterFlavorUiController>();
            controller.OpenPreviewMenu(PreviewDummy);

            if (!string.IsNullOrWhiteSpace(url))
            {
                _entManager.System<CharecterFlavorSystem>().RequestHeadshotPreview(url);
            }
        }

        private void OnFlavorPreviewRequested()
        {
            if (Profile is null)
                return;

            if (!_entManager.EntityExists(PreviewDummy))
                return;

            var flavor = _entManager.EnsureComponent<CharacterFlavorComponent>(PreviewDummy);
            flavor.FlavorText = Profile.FlavorText ?? string.Empty;
            flavor.HeadshotUrl = Profile.HeadshotUrl ?? string.Empty;

            var controller = UserInterfaceManager.GetUIController<CharacterFlavorUiController>();
            controller.OpenPreviewMenu(PreviewDummy);

            if (!string.IsNullOrWhiteSpace(Profile.HeadshotUrl))
            {
                _entManager.System<CharecterFlavorSystem>().RequestHeadshotPreview(Profile.HeadshotUrl);
            }
        }
        //ADT-tweak-end

        #endregion

        #region Skin Color

        private void OnSkinColorOnValueChanged()
        {
            if (Profile is null) return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var strategy = _prototypeManager.Index(skin).Strategy;

            switch (strategy.InputType)
            {
                case SkinColorationStrategyInput.Unary:
                    {
                        if (!Skin.Visible)
                        {
                            Skin.Visible = true;
                            RgbSkinColorContainer.Visible = false;
                        }
                        var color = strategy.FromUnary(Skin.Value);
                        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));
                        break;
                    }
                case SkinColorationStrategyInput.Color:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }
                        var color = strategy.ClosestSkinColor(_rgbSkinColorSelector.Color);
                        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));
                        break;
                    }
            }

            ReloadProfilePreview();
        }

        #endregion

        #region Species Window

        private void OnSkinColorOnValueChangedKeepColor(HumanoidCharacterProfile previous)
        {
            if (Profile is null) return;

            var skinTypeStr = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var color = previous.Appearance.SkinColor;

            switch (skinTypeStr)
            {
                case "HumanToned":
                    break;
                case "Hues":
                    color = AdjustBrightness(color, 0.9f, 1.0f);
                    break;
                case "TintedHues":
                    color = AdjustSaturation(color, 0.1f);
                    break;
                case "VoxFeathers":
                    color = ClampColor(color, 29f / 360f, 174f / 360f, 0.2f, 0.88f, 0.36f, 0.55f);
                    break;
                default:
                    break;
            }

            _rgbSkinColorSelector.Color = color;
            ReloadProfilePreview();
        }

        private Color AdjustBrightness(Color color, float min, float max)
        {
            var hsv = Color.ToHsv(color);
            hsv.Z = Math.Clamp(hsv.Z, min, max);
            return Color.FromHsv(hsv);
        }

        private Color AdjustSaturation(Color color, float maxSaturation)
        {
            var hsv = Color.ToHsv(color);
            hsv.Y = Math.Min(hsv.Y, maxSaturation);
            return Color.FromHsv(hsv);
        }

        private Color ClampColor(Color color, float minH, float maxH, float minS, float maxS, float minV, float maxV)
        {
            var hsv = Color.ToHsv(color);
            hsv.X = Math.Clamp(hsv.X, minH, maxH);
            hsv.Y = Math.Clamp(hsv.Y, minS, maxS);
            hsv.Z = Math.Clamp(hsv.Z, minV, maxV);
            return Color.FromHsv(hsv);
        }

        #endregion

        #region Events

        private void OnSpeciesInfoButtonPressed(BaseButton.ButtonEventArgs args)
        {
            var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
            var species = Profile?.Species ?? SharedHumanoidAppearanceSystem.DefaultSpecies;
            var page = DefaultSpeciesGuidebook;
            if (_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                page = new ProtoId<GuideEntryPrototype>(species.Id);

            if (_prototypeManager.Resolve(DefaultSpeciesGuidebook, out var guideRoot))
            {
                var dict = new Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry>();
                dict.Add(DefaultSpeciesGuidebook, guideRoot);
                guidebookController.OpenGuidebook(dict, includeChildren: true, selected: page);
            }
        }

        #endregion

        #region Bark

        private void InitializeBarks()
        {
            // ADT Barks initialization
        }

        private void UpdateBarkVoicesControls()
        {
            // ADT Barks update
        }

        #endregion

        #region Languages

        private void RefreshLanguages()
        {
            // ADT Languages refresh
        }

        private void OnLanguagesSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            // ADT Languages search
        }

        #endregion

        #region Export/Import

        private async void ExportImage()
        {
            if (_imaging)
                return;

            var dir = SpriteView.OverrideDirection ?? Direction.South;

            _imaging = true;
            await _entManager.System<ContentSpriteSystem>().Export(PreviewDummy, dir, includeId: false);
            _imaging = false;
        }

        private async void ImportProfile()
        {
            if (_exporting || CharacterSlot == null || Profile == null)
                return;

            StartExport();
            await using var file = await _dialogManager.OpenFile(new FileDialogFilters(new FileDialogFilters.Group("yml")), FileAccess.Read);

            if (file == null)
            {
                EndExport();
                return;
            }

            try
            {
                var sponsorPrototypes = Array.Empty<string>();
                var profile = _entManager.System<HumanoidAppearanceSystem>().FromStream(file, _playerManager.LocalSession!, sponsorPrototypes);
                var oldProfile = Profile;
                SetProfile(profile, CharacterSlot);

                IsDirty = !profile.MemberwiseEquals(oldProfile);
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when importing profile\n{exc.StackTrace}");
            }
            finally
            {
                EndExport();
            }
        }

        private async void ExportProfile()
        {
            if (Profile == null || _exporting)
                return;

            StartExport();
            var file = await _dialogManager.SaveFile(new FileDialogFilters(new FileDialogFilters.Group("yml")));

            if (file == null)
            {
                EndExport();
                return;
            }

            try
            {
                var dataNode = _entManager.System<HumanoidAppearanceSystem>().ToDataNode(Profile);
                await using var writer = new StreamWriter(file.Value.fileStream);
                dataNode.Write(writer);
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when exporting profile\n{exc.StackTrace}");
            }
            finally
            {
                EndExport();
                await file.Value.fileStream.DisposeAsync();
            }
        }

        private void StartExport()
        {
            _exporting = true;
            ImportButton.Disabled = true;
            ExportButton.Disabled = true;
        }

        private void EndExport()
        {
            _exporting = false;
            ImportButton.Disabled = false;
            ExportButton.Disabled = false;
        }

        public void TriggerImport()
        {
            ImportProfile();
        }

        public void TriggerExport()
        {
            ExportProfile();
        }

        #endregion

        #region Dispose

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;

            _headshotRequestCts?.Cancel();
            _headshotRequestCts = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            _entManager.DeleteEntity(PreviewDummy);
            PreviewDummy = EntityUid.Invalid;
        }

        #endregion
    }
}