using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Client._VG.Sponsors; // VG-Tweak

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        
        // VG-Tweak Start
        [Dependency] private readonly SponsorsManager _sponsorsManager = default!;
        private float _updateTimer;
        private static readonly Color ColorNonSponsor = Color.FromHex("#272727");
        // VG-Tweak End

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(ShowInterfaceContainer, LayoutPreset.Wide); // ADT-Tweak
            SetAnchorPreset(ShowInterface, LayoutPreset.BottomLeft); // ADT-Tweak

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            
            // ADT-Tweak-Start
            HideInterface.OnPressed += _ =>
            {
                SwitchState(LobbyGuiState.ScreenSaver);
            };
            ShowInterface.OnPressed += _ =>
            {
                SwitchState(LobbyGuiState.Default);
            };
            // ADT-Tweak-End

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
            
            // VG-Tweak Start
            UpdateSponsorButton();
            // VG-Tweak End
        }

        // VG-Tweak Start
        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            _updateTimer += args.DeltaSeconds;
            if (_updateTimer > 5.0f)
            {
                _updateTimer = 0;
                UpdateSponsorButton();
            }
        }

        private void UpdateSponsorButton()
        {
            if (SponsorInfoButton == null)
                return;

            var hasSponsor = _sponsorsManager.TryGetInfo(out var sponsorInfo);
            
            if (hasSponsor && sponsorInfo != null)
            {
                if (!string.IsNullOrEmpty(sponsorInfo.OOCColor))
                {
                    SponsorInfoButton.ModulateSelfOverride = Color.FromHex(sponsorInfo.OOCColor);
                }
                else
                {
                    SponsorInfoButton.ModulateSelfOverride = Color.White;
                }
                
                var tierValue = sponsorInfo.Tier ?? 0;
                SponsorInfoButton.Text = Loc.GetString("ui-lobby-sponsor-button-level", 
                    ("sponsorTier", tierValue));
            }
            else
            {
                SponsorInfoButton.ModulateSelfOverride = ColorNonSponsor;
                SponsorInfoButton.Text = Loc.GetString("ui-lobby-sponsor-button-main-level");
            }
        }
        // VG-Tweak End

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;
            
            // ADT-Tweak-Start
            ShowInterfaceContainer.Visible = false;
            MainContainer.Visible = true;
            // ADT-Tweak-End

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                    
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;

                // ADT-Tweak-Start
                case LobbyGuiState.ScreenSaver:
                    ShowInterfaceContainer.Visible = true;
                    MainContainer.Visible = false;
                    break;
                // ADT-Tweak-End
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup,
            
            ScreenSaver, // ADT-Tweak
        }
    }
}