using System;
using System.Collections.Generic;
using System.Linq;
using Robust.Shared.Enums;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private EntityUid? _previewDummy;
    private EntityUid? _leftDummy;
    private EntityUid? _rightDummy;
    
    private LobbyUIController _controller;
    
    private List<KeyValuePair<int, ICharacterProfile>> _sortedCharacters = new();
    private int _leftSlot = -1;
    private int _centerSlot = -1;
    private int _rightSlot = -1;

    private HumanoidCharacterProfile? _lastCenterProfile;
    private int _lastLeftSlot = -1;
    private int _lastRightSlot = -1;

    private static readonly Color _hiddenButtonColor = Color.Transparent;
    private static readonly Color _hoverButtonColor = Color.White.WithAlpha(0.15f);

    private bool _leftHovered = false;
    private bool _rightHovered = false;

    private bool _leftFullyVisible = false;
    private bool _rightFullyVisible = false;

    private const float CenterFadeDuration = 0.4f;
    private bool _fadingCenter = false;
    private float _fadeCenterTime = 0f;
    private HumanoidCharacterProfile? _pendingCenterProfile;

    private const float SideFadeInDuration = 0.2f;
    private bool _sideFadeInPending = false;
    private bool _sideFadeInActive = false;
    private float _sideFadeInTime = 0f;
    private HumanoidCharacterProfile? _newLeftProfile;
    private HumanoidCharacterProfile? _newRightProfile;

    private bool _initialized = false;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
        
        LeftCharacterButton.OnPressed += _ => OnCharacterButtonPressed(_leftSlot);
        RightCharacterButton.OnPressed += _ => OnCharacterButtonPressed(_rightSlot);
        
        SetupHoverEffects(LeftCharacterButton, isLeft: true);
        SetupHoverEffects(RightCharacterButton, isLeft: false);
    }

    private void SetupHoverEffects(Button button, bool isLeft)
    {
        button.OnMouseEntered += args =>
        {
            if (isLeft && !_leftFullyVisible)
                return;
            if (!isLeft && !_rightFullyVisible)
                return;

            if (isLeft)
                _leftHovered = true;
            else
                _rightHovered = true;
            button.ModulateSelfOverride = _hoverButtonColor;
        };
        
        button.OnMouseExited += args =>
        {
            if (isLeft)
                _leftHovered = false;
            else
                _rightHovered = false;
            button.ModulateSelfOverride = _hiddenButtonColor;
        };
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
        
        if (value)
        {
            UpdateCharacterSelector();
            if (!_initialized)
            {
                if (LeftCharacterButton.Visible) LeftSpriteView.ModulateSelfOverride = Color.White;
                if (RightCharacterButton.Visible) RightSpriteView.ModulateSelfOverride = Color.White;
                _leftFullyVisible = LeftCharacterButton.Visible;
                _rightFullyVisible = RightCharacterButton.Visible;
                _initialized = true;
            }
        }
    }

    public void SetSummaryText(string value)
    {
        var message = new FormattedMessage();
        message.AddText(value);
        Summary.SetMessage(message);
    }

    private EntityUid CreateDummy(HumanoidCharacterProfile profile, bool jobClothes = true)
    {
        return _controller.LoadProfileEntity(profile, null, jobClothes);
    }

    public void SetSprite(EntityUid uid)
    {
        if (_previewDummy != null)
        {
            _entManager.DeleteEntity(_previewDummy);
        }

        _previewDummy = uid;

        ViewBox.RemoveAllChildren();
        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(5f, 5f),
            MaxSize = new Vector2(122, 122),
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(uid);
        ViewBox.AddChild(spriteView);
    }

    public void UpdateCharacterSelector()
    {
        if (!_preferencesManager.ServerDataLoaded || _preferencesManager.Preferences == null)
            return;

        var preferences = _preferencesManager.Preferences;
        _sortedCharacters = new List<KeyValuePair<int, ICharacterProfile>>(preferences.Characters);
        
        if (_sortedCharacters.Count == 0)
            return;

        _sortedCharacters.Sort((a, b) => a.Key.CompareTo(b.Key));
        
        var selectedSlot = preferences.SelectedCharacterIndex;
        var selectedIndex = _sortedCharacters.FindIndex(c => c.Key == selectedSlot);
        
        if (selectedIndex < 0)
            selectedIndex = 0;

        int leftIndex = GetCycledIndex(selectedIndex, -1, _sortedCharacters.Count);
        int rightIndex = GetCycledIndex(selectedIndex, 1, _sortedCharacters.Count);

        if (_sortedCharacters.Count == 1)
        {
            leftIndex = -1;
            rightIndex = -1;
        }
        else if (_sortedCharacters.Count == 2)
        {
            leftIndex = selectedIndex == 0 ? 1 : 0;
            rightIndex = -1;
        }

        var centerProfile = _sortedCharacters[selectedIndex].Value as HumanoidCharacterProfile;
        var leftProfile = leftIndex >= 0 ? _sortedCharacters[leftIndex].Value as HumanoidCharacterProfile : null;
        var rightProfile = rightIndex >= 0 ? _sortedCharacters[rightIndex].Value as HumanoidCharacterProfile : null;

        int newLeftSlot = leftIndex >= 0 ? _sortedCharacters[leftIndex].Key : -1;
        int newRightSlot = rightIndex >= 0 ? _sortedCharacters[rightIndex].Key : -1;

        bool centerChanged = !ReferenceEquals(centerProfile, _lastCenterProfile);
        bool leftChanged = newLeftSlot != _lastLeftSlot;
        bool rightChanged = newRightSlot != _lastRightSlot;

        if (centerProfile != null)
        {
            UpdateSummary(centerProfile);
        }

        if (!centerChanged && !leftChanged && !rightChanged)
            return;

        _lastCenterProfile = centerProfile;
        _lastLeftSlot = newLeftSlot;
        _lastRightSlot = newRightSlot;

        _centerSlot = selectedSlot;
        _leftSlot = newLeftSlot;
        _rightSlot = newRightSlot;

        if (centerProfile != null)
        {
            StartFadeCenter(centerProfile);
        }

        if (leftProfile != null)
        {
            LeftCharName.Text = leftProfile.Name;
            LeftCharacterButton.Visible = true;
            _leftFullyVisible = false;
            LeftCharacterButton.ModulateSelfOverride = _hiddenButtonColor;

            CleanupLeftDummy();
            _leftDummy = CreateDummy(leftProfile);
            LeftSpriteView.SetEntity(_leftDummy.Value);

            if (_initialized)
            {
                LeftSpriteView.ModulateSelfOverride = Color.White.WithAlpha(0f);
                _newLeftProfile = leftProfile;
            }
            else
            {
                LeftSpriteView.ModulateSelfOverride = Color.White;
                _leftFullyVisible = true;
            }
        }
        else
        {
            _leftSlot = -1;
            _leftHovered = false;
            _leftFullyVisible = false;
            LeftCharacterButton.Visible = false;
            CleanupLeftDummy();
            _newLeftProfile = null;
        }

        if (rightProfile != null)
        {
            RightCharName.Text = rightProfile.Name;
            RightCharacterButton.Visible = true;
            _rightFullyVisible = false;
            RightCharacterButton.ModulateSelfOverride = _hiddenButtonColor;

            CleanupRightDummy();
            _rightDummy = CreateDummy(rightProfile);
            RightSpriteView.SetEntity(_rightDummy.Value);

            if (_initialized)
            {
                RightSpriteView.ModulateSelfOverride = Color.White.WithAlpha(0f);
                _newRightProfile = rightProfile;
            }
            else
            {
                RightSpriteView.ModulateSelfOverride = Color.White;
                _rightFullyVisible = true;
            }
        }
        else
        {
            _rightSlot = -1;
            _rightHovered = false;
            _rightFullyVisible = false;
            RightCharacterButton.Visible = false;
            CleanupRightDummy();
            _newRightProfile = null;
        }

        if (_initialized && (leftProfile != null || rightProfile != null))
        {
            _sideFadeInPending = true;
            _sideFadeInActive = false;
        }
        else
        {
            _sideFadeInPending = false;
            _sideFadeInActive = false;
        }
    }

    private void StartFadeCenter(HumanoidCharacterProfile profile)
    {
        _pendingCenterProfile = profile;
        _fadingCenter = true;
        _fadeCenterTime = 0f;
    }

    private int GetCycledIndex(int currentIndex, int offset, int totalCount)
    {
        if (totalCount <= 1) return -1;
        int newIndex = currentIndex + offset;
        if (newIndex < 0) newIndex = totalCount - 1;
        else if (newIndex >= totalCount) newIndex = 0;
        return newIndex;
    }

    private void UpdateSummary(HumanoidCharacterProfile profile)
    {
        var summary = GetCharacterSummary(profile);
        var message = new FormattedMessage();
        message.AddText(summary);
        Summary.SetMessage(message);
    }

    private string GetCharacterSummary(HumanoidCharacterProfile profile)
    {
        var genderText = GetGenderText(profile.Gender);
        var jobName = GetPreferredJobName(profile);
        var ageText = GetAgeText(profile.Age);
        return $"{profile.Name}, {jobName}, {genderText} {profile.Age} {ageText}";
    }

    private string GetGenderText(Gender gender)
    {
        return gender switch
        {
            Gender.Male => "Ему",
            Gender.Female => "Ей",
            Gender.Neuter => "Ему",
            Gender.Epicene => "Им",
            _ => "Ему"
        };
    }

    private string GetAgeText(int age)
    {
        int last = age % 10;
        int lastTwo = age % 100;
        if (lastTwo >= 11 && lastTwo <= 19) return "лет";
        if (last == 1) return "год";
        if (last >= 2 && last <= 4) return "года";
        return "лет";
    }

    private string GetPreferredJobName(HumanoidCharacterProfile profile)
    {
        var high = profile.JobPriorities.FirstOrDefault(p => p.Value == JobPriority.High).Key;
        if (high != default && _prototypeManager.TryIndex(high, out var job))
            return Loc.GetString(job.Name);
        return "безработный";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        float dt = args.DeltaSeconds;

        if (_fadingCenter)
        {
            _fadeCenterTime += dt;
            float progress = Math.Clamp(_fadeCenterTime / CenterFadeDuration, 0f, 1f);
            float alpha;
            if (progress < 0.5f)
            {
                alpha = 1f - progress * 2f;
            }
            else
            {
                if (_pendingCenterProfile != null && progress >= 0.5f && _previewDummy != null)
                {
                    var newDummy = CreateDummy(_pendingCenterProfile);
                    SetSprite(newDummy);
                    _pendingCenterProfile = null;
                }
                alpha = (progress - 0.5f) * 2f;
            }

            if (ViewBox.ChildCount > 0)
            {
                var sprite = ViewBox.GetChild(0) as SpriteView;
                if (sprite != null)
                    sprite.ModulateSelfOverride = Color.White.WithAlpha(alpha);
            }

            if (progress >= 1f)
            {
                _fadingCenter = false;
                if (_sideFadeInPending)
                {
                    _sideFadeInPending = false;
                    _sideFadeInActive = true;
                    _sideFadeInTime = 0f;
                }
            }
        }

        if (_sideFadeInActive)
        {
            _sideFadeInTime += dt;
            float progress = Math.Clamp(_sideFadeInTime / SideFadeInDuration, 0f, 1f);
            float alpha = progress;

            if (LeftCharacterButton.Visible && _newLeftProfile != null)
                LeftSpriteView.ModulateSelfOverride = Color.White.WithAlpha(alpha);
            if (RightCharacterButton.Visible && _newRightProfile != null)
                RightSpriteView.ModulateSelfOverride = Color.White.WithAlpha(alpha);

            if (progress >= 1f)
            {
                _sideFadeInActive = false;
                if (_newLeftProfile != null)
                {
                    LeftSpriteView.ModulateSelfOverride = Color.White;
                    _leftFullyVisible = true;
                    if (LeftCharacterButton.IsHovered)
                    {
                        _leftHovered = true;
                        LeftCharacterButton.ModulateSelfOverride = _hoverButtonColor;
                    }
                }
                if (_newRightProfile != null)
                {
                    RightSpriteView.ModulateSelfOverride = Color.White;
                    _rightFullyVisible = true;
                    if (RightCharacterButton.IsHovered)
                    {
                        _rightHovered = true;
                        RightCharacterButton.ModulateSelfOverride = _hoverButtonColor;
                    }
                }
            }
        }
    }

    private void OnCharacterButtonPressed(int slot)
    {
        if (slot < 0) return;
        _preferencesManager.SelectCharacter(slot);
        UpdateCharacterSelector();

        _controller.UpdateOpenCharacterSetupWindow(); // VG-Tweak
    }

    private void CleanupLeftDummy()
    {
        if (_leftDummy != null)
        {
            _entManager.DeleteEntity(_leftDummy);
            _leftDummy = null;
        }
    }

    private void CleanupRightDummy()
    {
        if (_rightDummy != null)
        {
            _entManager.DeleteEntity(_rightDummy);
            _rightDummy = null;
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _entManager.DeleteEntity(_previewDummy);
        _previewDummy = null;
        CleanupLeftDummy();
        CleanupRightDummy();
    }
}