using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Client._VG.Sponsors; // VG-Tweak

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
        
        // VG-Tweak Start
        [Dependency] private readonly SponsorsManager _sponsorsManager = default!;
        private float _updateTimer;
        private static readonly Color ColorNonSponsor = Color.FromHex("#272727");
        private SponsorInfoWindow? _sponsorWindow;
        // VG-Tweak End

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(ShowInterfaceContainer, LayoutPreset.Wide); // ADT-Tweak
            SetAnchorPreset(ShowInterface, LayoutPreset.BottomLeft); // ADT-Tweak
            SetAnchorPreset(CharacterSetupState, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            
            // ADT-Tweak Start
            HideInterface.OnPressed += _ => SwitchState(LobbyGuiState.ScreenSaver);
            ShowInterface.OnPressed += _ => SwitchState(LobbyGuiState.Default);
            // ADT-Tweak End

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
            
            CharacterSetup.OnPressed += _ => 
            {
                // VG-Tweak Start
                if (ReadyButton.Pressed)
                {
                    _consoleHost.ExecuteCommand("toggleready False");
                }
                // VG-Tweak End

                SwitchState(LobbyGuiState.CharacterSetup);
            };

            // VG-Tweak Start
            if (SponsorInfoButton != null)
            {
                SponsorInfoButton.OnPressed += _ => OnSponsorButtonPressed();
                UpdateSponsorButton();
            }
            // VG-Tweak End
        }

        // VG-Tweak Start
        private void OnSponsorButtonPressed()
        {
            if (_sponsorWindow != null)
            {
                _sponsorWindow.Close();
                _sponsorWindow = null;
                return;
            }
            
            _sponsorWindow = _uiManager.CreateWindow<SponsorInfoWindow>();
            _sponsorWindow.OnClose += () => _sponsorWindow = null;
            _sponsorWindow.OpenCentered();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            // VG-Tweak Start
            if (!StartTime.Visible)
                StartTime.Visible = true;

            if (string.IsNullOrEmpty(StartTime.Text))
                StartTime.Text = "Раунд уже в процессе";
            // VG-Tweak End

            _updateTimer += args.DeltaSeconds;
            if (_updateTimer > 5.0f)
            {
                _updateTimer = 0;
                UpdateSponsorButton();
            }
        }

        private void UpdateSponsorButton()
        {
            if (SponsorInfoButton == null) return;

            var hasSponsor = _sponsorsManager.TryGetInfo(out var sponsorInfo);
            
            if (hasSponsor && sponsorInfo != null)
            {
                if (!string.IsNullOrEmpty(sponsorInfo.OOCColor))
                    SponsorInfoButton.ModulateSelfOverride = Color.FromHex(sponsorInfo.OOCColor);
                else
                    SponsorInfoButton.ModulateSelfOverride = Color.White;
                
                var tierValue = sponsorInfo.Tier ?? 0;
                SponsorInfoButton.Text = Loc.GetString("ui-lobby-sponsor-button-level", ("sponsorTier", tierValue));
            }
            else
            {
                SponsorInfoButton.ModulateSelfOverride = ColorNonSponsor;
                SponsorInfoButton.Text = Loc.GetString("ui-lobby-sponsor-button-main-level");
            }
            SponsorInfoButton.Visible = true;
        }
        // VG-Tweak End

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;
            ShowInterfaceContainer.Visible = false; // ADT-Tweak
            MainContainer.Visible = true;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                    
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    MainContainer.Visible = false; // VG-Tweak
                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;

                case LobbyGuiState.ScreenSaver: // ADT-Tweak
                    ShowInterfaceContainer.Visible = true;
                    MainContainer.Visible = false;
                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup,
            ScreenSaver, // ADT-Tweak
        }
    }
}