using System.Linq;
using System.Numerics;
using Content.Client.Message;
using Content.Shared.Atmos;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Alert;
using Content.Shared._VG.Targeting;
using Content.Shared.Damage;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.Inventory;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.Mobs.Systems;
using Content.Shared.Nutrition.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Shared.Damage.Components;
using Content.Shared._VG.Surgery;

namespace Content.Client.HealthAnalyzer.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HealthAnalyzerWindow : FancyWindow
    {
        private static readonly Color Green = Color.FromHex("#00FF00");
        private static readonly Color Red = Color.FromHex("#FF0000");

        private readonly IEntityManager _entityManager;
        private readonly SpriteSystem _spriteSystem;
        private readonly IPrototypeManager _prototypes;
        private readonly IResourceCache _cache;

        private EntityUid _spriteViewEntity;
        private readonly EntProtoId _bodyView = "AlertSpriteView";
        private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;
        private EntityUid? _target;

        public event Action<TargetBodyPart?, EntityUid>? OnBodyPartSelected;

        public HealthAnalyzerWindow()
        {
            RobustXamlLoader.Load(this);

            var dependencies = IoCManager.Instance!;
            _entityManager = dependencies.Resolve<IEntityManager>();
            _spriteSystem = _entityManager.System<SpriteSystem>();
            _prototypes = dependencies.Resolve<IPrototypeManager>();
            _cache = dependencies.Resolve<IResourceCache>();

            _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
            {
                { TargetBodyPart.Head, HeadButton },
                { TargetBodyPart.Torso, ChestButton },
                { TargetBodyPart.Groin, GroinButton },
                { TargetBodyPart.LeftArm, LeftArmButton },
                { TargetBodyPart.LeftHand, LeftHandButton },
                { TargetBodyPart.RightArm, RightArmButton },
                { TargetBodyPart.RightHand, RightHandButton },
                { TargetBodyPart.LeftLeg, LeftLegButton },
                { TargetBodyPart.LeftFoot, LeftFootButton },
                { TargetBodyPart.RightLeg, RightLegButton },
                { TargetBodyPart.RightFoot, RightFootButton },
            };

            foreach (var bodyPartButton in _bodyPartControls)
            {
                bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
                bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key, bodyPartButton.Value);
            }
            ReturnButton.OnPressed += _ => ResetBodyPart();
        }

        public void SetActiveBodyPart(TargetBodyPart part, TextureButton button)
        {
            if (_target == null)
                return;
            OnBodyPartSelected?.Invoke(part == TargetBodyPart.Groin ? TargetBodyPart.Torso : part, _target.Value);
        }

        public void ResetBodyPart()
        {
            if (_target == null)
                return;
            OnBodyPartSelected?.Invoke(null, _target.Value);
        }

        public void SetActiveButtons(bool isHumanoid)
        {
            foreach (var button in _bodyPartControls)
                button.Value.Visible = isHumanoid;
        }

        public void Populate(HealthAnalyzerScannedUserMessage msg)
        {
            _target = _entityManager.GetEntity(msg.TargetEntity);
            EntityUid? part = msg.Part != null ? _entityManager.GetEntity(msg.Part.Value) : null;
            var isPart = part != null;

            if (_target == null
                || !_entityManager.TryGetComponent<DamageableComponent>(isPart ? part : _target, out var damageable))
            {
                NoPatientDataText.Visible = true;
                return;
            }

            SetActiveButtons(_entityManager.HasComponent<TargetingComponent>(_target.Value));

            ReturnButton.Visible = isPart;
            PartNameLabel.Visible = isPart;

            if (part != null)
                PartNameLabel.Text = _entityManager.HasComponent<MetaDataComponent>(part)
                    ? Identity.Name(part.Value, _entityManager)
                    : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

            NoPatientDataText.Visible = false;

            ScanModeLabel.Text = msg.ScanMode.HasValue
                ? msg.ScanMode.Value
                    ? Loc.GetString("health-analyzer-window-scan-mode-active")
                    : Loc.GetString("health-analyzer-window-scan-mode-inactive")
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

            ScanModeLabel.FontColorOverride = msg.ScanMode.HasValue && msg.ScanMode.Value ? Color.Green : Color.Red;

            SpriteView.SetEntity(SetupIcon(msg.Body) ?? _target.Value);
            SpriteView.Visible = msg.ScanMode.HasValue && msg.ScanMode.Value;
            PartView.Visible = SpriteView.Visible;
            NoDataTex.Visible = !SpriteView.Visible;

            var name = new FormattedMessage();
            name.PushColor(Color.White);
            name.AddText(_entityManager.HasComponent<MetaDataComponent>(_target.Value)
                ? Identity.Name(_target.Value, _entityManager)
                : Loc.GetString("health-analyzer-window-entity-unknown-text"));
            NameLabel.SetMessage(name);

            SpeciesLabel.Text =
                _entityManager.TryGetComponent<HumanoidAppearanceComponent>(_target.Value, out var humanoidAppearanceComponent)
                    ? Loc.GetString(_prototypes.Index<SpeciesPrototype>(humanoidAppearanceComponent.Species).Name)
                    : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

            TemperatureLabel.Text = !float.IsNaN(msg.Temperature)
                ? $"{msg.Temperature - Atmospherics.T0C:F1} °C ({msg.Temperature:F1} K)"
                : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

            // ADT-Tweak: blood color gradient
            if (!float.IsNaN(msg.BloodLevel))
            {
                var bloodPercent = msg.BloodLevel;
                var exclamations = bloodPercent switch
                {
                    <= 0f => "!!!!",
                    <= 0.25f => "!!!",
                    <= 0.5f => "!!",
                    <= 0.75f => "!",
                    _ => ""
                };
                BloodLabel.Text = $"{bloodPercent * 100:F1}%{exclamations}";
                var clampedPercent = Math.Max(bloodPercent, 0.5f);
                var scaled = (clampedPercent - 0.5f) / 0.5f;
                BloodLabel.FontColorOverride = Color.InterpolateBetween(Red, Green, scaled);
            }
            else
            {
                BloodLabel.Text = Loc.GetString("health-analyzer-window-entity-unknown-value-text");
                BloodLabel.FontColorOverride = null;
            }

            StatusLabel.Text =
                _entityManager.TryGetComponent<MobStateComponent>(_target.Value, out var mobStateComponent)
                    ? GetStatus(mobStateComponent.CurrentState)
                    : Loc.GetString("health-analyzer-window-entity-unknown-text");

            DamageLabel.Text = damageable.TotalDamage.ToString();

            var showAlerts = msg.Unrevivable == true || msg.Bleeding == true;
            AlertsDivider.Visible = showAlerts;
            AlertsContainer.Visible = showAlerts;

            if (showAlerts)
                AlertsContainer.DisposeAllChildren();

            if (msg.Unrevivable == true)
                AlertsContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                    Margin = new Thickness(0, 4),
                    MaxWidth = 300
                });

            if (msg.Bleeding == true)
                AlertsContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                    Margin = new Thickness(0, 4),
                    MaxWidth = 300
                });

            IReadOnlyDictionary<string, FixedPoint2> damagePerType = damageable.Damage.DamageDict;
            var groupOrder = new List<string> { "Burn", "Brute", "Airloss", "Toxin", "Genetic" };
            var sortedGroups = damageable.DamagePerGroup
                .OrderBy(g => groupOrder.IndexOf(g.Key))
                .ToDictionary(g => g.Key, g => g.Value);

            DrawDiagnosticGroups(sortedGroups, damagePerType);
            DrawMetabolizingChemicals(msg.MetabolizingReagents);
        }

        private static string GetStatus(MobState mobState)
        {
            return mobState switch
            {
                MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
                MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
                MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
                _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
            };
        }

        // ADT-Tweak: Diagnostic Groups
        private void DrawDiagnosticGroups(Dictionary<string, FixedPoint2> groups, IReadOnlyDictionary<string, FixedPoint2> damageDict)
        {
            GroupsContainer.RemoveAllChildren();
            GroupsContainer.HorizontalExpand = true;

            var listContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 4,
            };
            GroupsContainer.AddChild(listContainer);

            foreach (var (damageGroupId, damageAmount) in groups)
            {
                if (damageAmount <= 0)
                    continue;

                var groupTitleText = $"{Loc.GetString("health-analyzer-window-damage-group-text", ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName), ("amount", damageAmount))}";

                var groupBox = new PanelContainer { Margin = new Thickness(2), HorizontalExpand = true };
                groupBox.PanelOverride = new StyleBoxFlat { BorderColor = Color.Gray, BorderThickness = new Thickness(1), ContentMarginLeftOverride = 4, ContentMarginRightOverride = 4, ContentMarginTopOverride = 4, ContentMarginBottomOverride = 4 };

                var groupContainer = new BoxContainer { Align = BoxContainer.AlignMode.Begin, Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };
                groupContainer.AddChild(CreateDiagnosticGroupTitleRow(groupTitleText, (float)damageAmount, damageGroupId));

                var divider = new PanelContainer { MinHeight = 1, Margin = new Thickness(0, 0, 0, 4), HorizontalExpand = true };
                divider.PanelOverride = new StyleBoxFlat(Color.Gray);
                groupContainer.AddChild(divider);

                var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);
                foreach (var type in group.DamageTypes)
                {
                    if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                        continue;

                    var damageTypeName = _prototypes.Index<DamageTypePrototype>(type).LocalizedName;
                    var typeId = type.ToString().ToLowerInvariant();

                    var damageRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2), HorizontalExpand = true };
                    damageRow.AddChild(new TextureRect { SetSize = new Vector2(15, 15), Texture = GetTexture(typeId), Margin = new Thickness(0, 0, 4, 0), VerticalAlignment = VAlignment.Center });
                    damageRow.AddChild(new Label { Text = damageTypeName, HorizontalExpand = true, HorizontalAlignment = HAlignment.Left });
                    damageRow.AddChild(new Label { Text = typeAmount.ToString(), HorizontalAlignment = HAlignment.Right });
                    groupContainer.AddChild(damageRow);
                }

                groupBox.AddChild(groupContainer);
                listContainer.AddChild(groupBox);
            }
        }

        private void DrawMetabolizingChemicals(List<(string ReagentId, FixedPoint2 Quantity)>? reagents)
        {
            ChemicalsContainer.RemoveAllChildren();
            var hasChemicals = reagents != null && reagents.Count > 0;
            ChemicalsDivider.Visible = hasChemicals;
            ChemicalsContainer.Visible = hasChemicals;

            if (!hasChemicals || reagents == null)
                return;

            ChemicalsContainer.HorizontalExpand = true;
            var sortedReagents = reagents.OrderByDescending(r => r.Quantity).ToList();

            foreach (var reagent in sortedReagents)
            {
                var reagentName = reagent.ReagentId;
                var reagentColor = Color.White;
                if (_prototypes.TryIndex<ReagentPrototype>(reagent.ReagentId, out var reagentProto))
                {
                    reagentName = reagentProto.LocalizedName;
                    reagentColor = reagentProto.SubstanceColor;
                }

                var rowContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2), HorizontalExpand = true };
                var colorBar = new PanelContainer { MinWidth = 10, MinHeight = 16, Margin = new Thickness(0, 0, 6, 0) };
                colorBar.PanelOverride = new StyleBoxFlat(reagentColor);
                rowContainer.AddChild(colorBar);
                rowContainer.AddChild(new Label { Text = reagentName, HorizontalExpand = true, HorizontalAlignment = HAlignment.Left });
                rowContainer.AddChild(new Label { Text = $"{reagent.Quantity}u", HorizontalAlignment = HAlignment.Right });
                ChemicalsContainer.AddChild(rowContainer);
            }
        }

        private Texture GetTexture(string texture)
        {
            var rsiPath = new ResPath("/Textures/ADT/Objects/Devices/health_analyzer.rsi");
            var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);
            var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
            if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
                rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
            return _spriteSystem.Frame0(rsiSprite);
        }

        private BoxContainer CreateDiagnosticGroupTitleRow(string text, float damageAmount, string damageGroupId)
        {
            var clampedDamage = Math.Min(damageAmount, 100f);
            var damagePercent = clampedDamage / 100f;
            var titleColor = Color.InterpolateBetween(Green, Red, damagePercent);

            var exclamations = damageAmount switch
            {
                > 200f => " !!!!",
                > 100f => " !!!",
                > 75f => " !!",
                > 50f => " !",
                _ => ""
            };

            var titleRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 4), HorizontalExpand = true };
            titleRow.AddChild(new TextureRect { SetSize = new Vector2(15, 15), Texture = GetTexture(damageGroupId.ToLowerInvariant()), Margin = new Thickness(0, 0, 4, 0), VerticalAlignment = VAlignment.Center });
            titleRow.AddChild(new Label { Text = text + exclamations, HorizontalExpand = true, HorizontalAlignment = HAlignment.Left, FontColorOverride = titleColor });
            return titleRow;
        }

        private EntityUid? SetupIcon(Dictionary<TargetBodyPart, TargetIntegrity>? body)
        {
            if (body is null || _target == null)
                return null;

            if (!_entityManager.Deleted(_spriteViewEntity))
                _entityManager.QueueDeleteEntity(_spriteViewEntity);

            _spriteViewEntity = _entityManager.Spawn(_bodyView);

            if (!_entityManager.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
                return null;

            var dollPath = _entityManager.GetComponent<SurgeryTargetComponent>(_target.Value).DollPath!;

            int layer = 0;
            foreach (var (bodyPart, integrity) in body)
            {
                string enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
                int enumValue = (int)integrity;
                var rsi = new SpriteSpecifier.Rsi(new ResPath($"{dollPath}/{enumName.ToLowerInvariant()}.rsi"), $"{enumName.ToLowerInvariant()}_{enumValue}");
                if (!sprite.TryGetLayer(layer, out _))
                    sprite.AddLayer(_spriteSystem.Frame0(rsi));
                else
                    sprite.LayerSetTexture(layer, _spriteSystem.Frame0(rsi));
                sprite.LayerSetScale(layer, new Vector2(3f, 3f));
                layer++;
            }
            return _spriteViewEntity;
        }       
    }
}