using Content.Shared._VG.SimpleSkills;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VG.SimpleSkills;

[GenerateTypedNameReferences]
public sealed partial class LazySkillList : BoxContainer
{
    private List<(SimpleSkillPrototype Proto, bool Known)> _skills = new();
    private bool _loaded = false;
    private bool _loading = false;

    public LazySkillList()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetSkills(List<(SimpleSkillPrototype Proto, bool Known)> skills)
    {
        _skills = skills;
        _loaded = false;
        _loading = false;
        
        RemoveAllChildren();

        if (_skills.Count == 0)
        {
            var noSkillsLabel = new Label
            {
                Text = Loc.GetString("simple-skills-non"),
                HorizontalAlignment = HAlignment.Center,
                FontColorOverride = Color.Gray,
                Margin = new Thickness(0, 5, 0, 5)
            };
            AddChild(noSkillsLabel);
            return;
        }

        LoadSkills();
    }

    private void LoadSkills()
    {
        if (_loaded || _loading)
            return;

        _loading = true;

        RemoveAllChildren();

        foreach (var (proto, known) in _skills)
        {
            var entry = new SkillEntryControl();
            entry.SetSkill(proto, known);
            AddChild(entry);
        }

        _loaded = true;
        _loading = false;
    }

    public void RefreshSkills(List<(SimpleSkillPrototype Proto, bool Known)> skills)
    {
        SetSkills(skills);
    }
}