using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.GameObjects;
using Content.Shared._VG.SimpleSkills;

namespace Content.Client._VG.SimpleSkills;

[GenerateTypedNameReferences]
public sealed partial class SkillEntryControl : BoxContainer
{
    public SkillEntryControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetSkill(SimpleSkillPrototype proto, bool known)
    {
        SkillNameLabel.Text = proto.Name;
        SkillDescriptionLabel.Text = proto.Description;
        
        if (proto.Icon != null)
        {
            var spriteSystem = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
            IconTexture.Texture = spriteSystem.Frame0(proto.Icon);
        }
        
        SkillStatusLabel.Visible = false;
    }
}