using Content.Shared._VG.SimpleSkills;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VG.SimpleSkills;

[GenerateTypedNameReferences]
public sealed partial class SkillEntryControl : BoxContainer
{
    public SkillEntryControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetSkill(SimpleSkillPrototype proto, bool known)
    {
        SkillNameLabel.Text = proto.Name;
        SkillDescriptionLabel.Text = proto.Description;
        
        if (proto.Icon != null)
        {
            var spriteSystem = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
            IconTexture.Texture = spriteSystem.Frame0(proto.Icon);
        }
        
        if (known)
        {
            SkillStatusLabel.Text = Loc.GetString("simple-skills-known");
            SkillStatusLabel.FontColorOverride = Color.FromHex("#4caf50");
            SkillStatusLabel.Visible = true;
        }
        else
        {
            SkillStatusLabel.Visible = false;
        }
    }
}