using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using Robust.Shared.Localization;

namespace Content.Client.ADT.Language.UI;
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣀⡀
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣴⣿⣿⣿⣿⣿⣄
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣀⣴⣿⡿⠛⠉⠁⢀⠙⢿⣿⣆⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣀
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣴⣿⡿⠟⠉⢀⢀⢀⢀⢀⢀⠈⢻⣿⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣴⣾⣿⣿
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣴⣾⣿⠿⠋⠁⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⣿⣿⡄⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣶⣿⣿⡿⠛⠉
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣴⣿⣿⡟⠃⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢻⣿⣷⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣤⣾⣿⣿⠿⠛⠁
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣰⣿⣿⡿⠋⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⣿⣿⡀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣀⣴⣿⣿⡿⠋⠁⢀⢀⢀⢀⢀⢀⠐
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⡀⣀⣼⣿⡿⠏⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⣿⣿⣶⣶⣶⣦⣤⣤⣄⣀⣀⢀⢀⢀⢀⣤⣾⣿⡿⠟⠁⢀⢀⢀⢀⢀⢀⢀⡠⠈
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣴⣿⣿⣿⣿⠟⠁⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣀⣀⣠⣿⣿⡿⠿⠿⠿⠿⠿⣿⣿⣿⣿⣿⣿⣾⣿⣿⡿⠋⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠁
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢸⣿⡟⢹⣿⠋⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠒⣾⣿⣿⡿⠏⠁⢀⢀⢀⢀⢀⢀⢀⣭⣿⣿⣿⣿⠿⠿⠋⢀⢀⢀⢀⢀⢀⢀⢀⢀⢠⠈
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣾⣿⠁⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣾⣿⣿⡟⠃⢀⢀⢀⢀⢀⢀⢀⣴⣿⣿⣿⡿⠟⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣼⣿⣿⡆⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣴⣿⣿⣿⠿⢀⢀⢀⢀⢀⢀⢀⣠⣾⣿⣿⣿⠟⠁⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣇⠠⠤⠄
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢠⣿⣿⡿⠋⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⣿⣿⡟⢀⢀⢀⢀⢀⢀⢀⣠⣿⣿⣿⣿⠟⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠁⢀⢀⡀
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣰⣿⣿⡟⠁⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⣿⣿⡏⢀⢀⢀⢀⢀⢀⢀⢰⣿⣿⣿⣿⡏⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠊
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣶⣶⣤⣴⣿⣿⠋⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠘⣿⣿⣿⠇
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣄⣀⡀⢀⢀⢀⢀⢀⣼⣿⣿⣿⣿⣿⡿⠁⢀⢀⢀⢀⢀⢀⢀⢀⣀⣤⣶⣿⣶⣄⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠉⠁
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣼⣿⣿⣿⣿⣿⣿⣶⣦⣀⢀⣿⣿⡇⢀⠉⠉⢀⢀⢀⢀⢀⢀⢀⢀⢀⣾⣿⣿⣿⣿⣿⣿⡆
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⣸⣿⣿⠉⠉⠉⣿⣿⣿⣿⣿⣿⣿⣿⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢠⣿⣿⣿⣿⣿⣿⣿⣿⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣤⣤⣤⣤⣤⣄⡀
// ⢀⢀⢀⢀⢀⣾⣿⣿⣿⣿⣿⠏⢀⢀⢀⢿⢿⣿⣿⣿⣿⣿⣿⣿⣶⣄⡀⢀⢀⢀⢀⢀⢀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣶⡀
// ⢀⢀⢀⣴⣿⣿⠟⠉⠉⠉⢀⢀⢀⢀⢀⢀⢀⢀⠉⢩⡿⠿⣿⣿⣿⣿⣿⣶⣤⡀⢀⢀⢀⠸⣿⣿⣿⣿⣿⣿⣿⣿⠟⠁⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀
// ⢀⣴⣿⣿⡿⠁⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠘⢷⣦⣄⠈⠛⠿⢿⣿⣿⣿⣷⣄⡀⢀⠉⠻⢿⣿⣿⠿⠟⠁⢀⢀⢀⢀⡀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇
// ⢀⣿⣿⡏⢀⢀⢀⢀⢀⣴⣿⣿⣿⣦⡄⢀⢀⢀⢀⢀⢀⢀⠙⠛⠦⢀⡀⠉⠻⢿⣿⣿⣿⣦⣄⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟
// ⢀⣿⣿⡇⢀⢀⢀⣠⣿⣿⣿⣿⣿⣿⣿⡆⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠁⠂⢀⢀⠘⠛⢿⣿⣿⣷⣦⣀⢀⢀⢀⢀⢀⢀⢀⠈⠻⣶⣄⣀⢀⠈⠛⣦⡀⢀⢀⢀⣠⣾⣷⢀⢀⢀⢀⢀⢀⢀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁
// ⢀⣿⣿⡇⢀⢀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠠⠄⢀⠈⠙⠿⣿⣿⣿⣦⣄⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⠛⠒⠒⠚⠛⠋⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⠛⠿⢿⣿⣿⡿⠿⠛
// ⢀⣿⣿⡇⢀⢀⢀⠹⣿⣿⣿⣿⣿⣿⣿⠏⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⢀⠂⣠⡈⠛⢿⣿⣿⣿⣶⣄⡀
// ⢀⣿⣿⡇⢀⢀⢀⢀⠙⠻⣿⣿⣿⠟⠃⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⠛⣿⣷⣿⣿⣿⣿⣿⣿⣷⣤⡀
// ⢀⣿⣿⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⠛⣿⣿⣿⢻⣿⣿⣿⣿⣿⣷⣦⡀⢀⢀⣀⣀⣀
// ⢀⣿⣿⡇⢀⢀⢀⢀⢀⢀⣀⣤⣄⢀⢀⢀⢀⢀⢀⢀⢀⢠⣤⣄⣀⣀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⣿⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⣷⣶⣤⣄
// ⢰⣿⣿⡇⢀⢀⢀⢀⢀⢀⣿⣿⡿⠃⢀⢀⢀⢀⢀⢀⢀⢀⠘⠻⣿⣿⣦⣤⡀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⣿⣿⢸⣿⣿⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠻⣿⣿⣿⣿⣦⡀
// ⢸⣿⣿⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢹⣿⠙⣿⣿⣷⣦⣄⡀⢀⢀⢀⢀⢀⢀⣿⣿⣿⢸⣿⣿⢸⣿⣿⢹⣿⡏⣿⣿⣿⣿⣿⣿⣦⣝⣿⣿⣿⣿⡄
// ⢸⣿⣿⣇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣀⣀⣀⢀⢀⢀⢸⣿⢀⣿⡇⢸⣿⡿⣿⣶⣦⣄⢀⢀⢀⣿⣿⣿⣼⣿⣿⢸⣿⣿⢸⣿⡇⢻⣿⣿⢸⣿⡏⠛⠿⢿⣿⣿⣿⣇⡀
// ⠈⣿⣿⣿⣷⣄⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣾⣿⣿⣿⣿⣷⣤⣸⣿⡄⣿⣷⢸⣿⡇⣿⣿⠙⠿⢿⣷⣤⣿⣿⣿⣿⣿⣿⣾⣿⣿⣸⣿⡇⢸⣿⣿⠈⣿⡇⢀⢀⢀⠙⠻⣿⣿⣷⡀
// ⢀⢻⣿⣿⣿⣿⣿⣷⣶⣶⣶⣶⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⢸⣿⡇⣿⣿⢀⢀⢀⠈⠛⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣼⣿⣿⢀⣿⡇⢀⢀⢀⢀⢀⢸⣿⣿⣇
// ⢀⢀⠘⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣧⣿⣿⢀⢀⢀⢀⢀⢀⢀⠉⠹⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣿⡇⢀⢀⢀⢀⢀⠘⣿⣿⣿⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣀
// ⢀⢀⢀⢀⢀⠈⠉⠻⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣦⣀⢀⢀⢀⢀⢀⢀⢀⢀⠘⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⡇⢀⢀⢀⢀⢀⢀⢻⣿⣿⡆⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢠⣴⣶⣶⣾⣿⣿
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣭⣿⣿⣿⣿⣿⣿⣿⣷⣤⣀⡀⢀⢀⢀⢀⢀⢀⢀⠉⠙⠿⣿⣿⣽⣿⣇⢀⢀⢀⢀⢀⢀⢀⣿⣿⣇⢀⢀⢀⢀⢀⢀⢀⢀⢀⠐⠶⣤⡀⢀⢀⢀⣸⣿⡏⠙⠛⠛⠛
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠉⠛⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡛⢿⣿⣿⣿⣿⣿⣶⣤⡀⢀⢀⢀⢀⢀⢀⢀⢀⠈⠛⠻⢿⣿⣶⣦⣀⢀⢀⢀⣿⣿⣿⡄⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⠻⢷⣦⣴⡿⠟⠁
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⣤⣤⣀⡀⢀⢀⢀⢀⠉⠙⠿⣿⣿⣿⣿⣿⣿⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠉⠉
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢠⣾⣿⡿⠋⢀⢀⢀⢀⢀⢀⠈⠙⠿⣿⣿⣿⠿⠛⠉⠁⢀⢀⢀⢀⢀⢀⢀⠈⠉⠙⠛⠿⢿⣿⣿⣶⣤⡀⢀⢀⢀⢀⣿⣿⣿⣿⣿⣿⠃
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣾⣿⣿⠃⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⣿⠃⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠙⠻⣿⣿⣿⣤⢀⢀⢸⣿⣿⣿⡿⠟⠁
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢰⣿⣿⡟⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢠⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠙⠻⣿⣶⣦⣸⣿⣿⣿⠃
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣾⣿⣿⠁⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢸⡇⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠈⠻⢿⣿⣿⣿⣿⡄
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⣿⣿⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢸⣿⡄⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠙⠿⣿⣿⣷⡀
// ⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⣿⣿⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⣷⡄⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⠘⣿⣿⣿⣤
[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : FancyWindow
{
    private readonly LanguageSystem _language;
    private readonly IPrototypeManager _proto;
    private readonly Dictionary<string, LanguageEntry> _entries = new();
    private string _currentSearch = string.Empty;
    private string _currentLanguage = string.Empty;
    private Dictionary<string, LanguageKnowledge> _currentOptions = new();
    private Dictionary<string, LanguageKnowledge> _currentTranslator = new();

    public EntityUid Owner = EntityUid.Invalid;
    private Action<string>? _onLanguageSelected;

    // Событие с динамической подпиской
    public event Action<string>? OnLanguageSelected
    {
        add
        {
            _onLanguageSelected += value;
            // Перепривязываем обработчик ко всем существующим записям
            foreach (var entry in _entries.Values)
            {
                entry.OnLanguageSelected -= value; // избегаем дублирования
                entry.OnLanguageSelected += value;
            }
        }
        remove
        {
            _onLanguageSelected -= value;
            foreach (var entry in _entries.Values)
            {
                entry.OnLanguageSelected -= value;
            }
        }
    }

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        _language = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();
        SearchBar.OnTextChanged += OnSearchTextChanged;
        Title = Loc.GetString("language-menu-window-title");
    }

    public void UpdateState(string current, Dictionary<string, LanguageKnowledge> options, Dictionary<string, LanguageKnowledge> translator)
    {
        _currentLanguage = current;
        _currentOptions = options;
        _currentTranslator = translator;
        
        CurrentLanguageLabel.Text = Loc.GetString("language-menu-current-language",
            ("language", _language.GetLanguage(current).LocalizedName));
        
        int totalKnown = options.Count + translator.Count;
        LanguagesCountLabel.Text = Loc.GetString("language-menu-known-count", ("count", totalKnown));
        
        UpdateLanguageList();
        UpdateButtonsState();
    }

    private void UpdateLanguageList()
    {
        var allLanguages = _currentOptions.Concat(_currentTranslator)
            .GroupBy(x => x.Key)
            .Select(g => new { Id = g.Key, IsTranslator = _currentTranslator.ContainsKey(g.Key) })
            .ToList();

        allLanguages.Sort((a, b) =>
        {
            var pa = _proto.Index<LanguagePrototype>(a.Id).Priority;
            var pb = _proto.Index<LanguagePrototype>(b.Id).Priority;
            if (pb != pa) return pb.CompareTo(pa);
            return string.Compare(_proto.Index<LanguagePrototype>(a.Id).LocalizedName,
                                  _proto.Index<LanguagePrototype>(b.Id).LocalizedName,
                                  StringComparison.OrdinalIgnoreCase);
        });

        var filtered = string.IsNullOrEmpty(_currentSearch) ? allLanguages :
            allLanguages.Where(l => _proto.Index<LanguagePrototype>(l.Id).LocalizedName.Contains(_currentSearch, StringComparison.OrdinalIgnoreCase)).ToList();

        OptionsList.RemoveAllChildren();
        _entries.Clear();

        foreach (var lang in filtered)
        {
            var proto = _proto.Index<LanguagePrototype>(lang.Id);
            var entry = new LanguageEntry(proto, lang.IsTranslator);
            // Если обработчик уже установлен, подписываем новый элемент
            if (_onLanguageSelected != null)
                entry.OnLanguageSelected += _onLanguageSelected;
            OptionsList.AddChild(entry);
            _entries[lang.Id] = entry;
        }
    }

    private void UpdateButtonsState()
    {
        foreach (var entry in _entries.Values)
        {
            bool isCurrent = entry.Language == _currentLanguage;
            entry.SelectButton.Disabled = isCurrent;
            entry.SelectButton.Text = isCurrent
                ? Loc.GetString("language-choose-button-chosen")
                : Loc.GetString("language-choose-button");
        }
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _currentSearch = args.Text.Trim();
        UpdateLanguageList();
        UpdateButtonsState();
    }
}