using Content.Shared.ADT.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Content.Client.Stylesheets;
using Robust.Shared.Localization;

namespace Content.Client.ADT.Language.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageEntry : PanelContainer
{
    public Action<string>? OnLanguageSelected;
    public string Language { get; }

    private bool _expanded;

    public LanguageEntry(LanguagePrototype proto, bool translator)
    {
        RobustXamlLoader.Load(this);
        NameLabel.Text = proto.LocalizedName;
        if (proto.UiColor.HasValue)
            NameLabel.FontColorOverride = proto.UiColor.Value;

        DescriptionLabel.SetMessage(proto.LocalizedDescription);
        Language = proto.ID;

        SelectButton.OnPressed += _ => OnLanguageSelected?.Invoke(proto.ID);
        ExpandButton.OnPressed += ToggleDescription;

        if (translator)
            AddStyleClass("LanguagesEntryTranslator");
    }

    private void ToggleDescription(BaseButton.ButtonEventArgs args)
    {
        _expanded = !_expanded;
        DescriptionPanel.Visible = _expanded;
        ExpandButton.Text = _expanded
            ? Loc.GetString("language-menu-hide-description")
            : Loc.GetString("language-menu-show-description");
    }
}