using System;
using Content.Client.Lobby.UI.Loadouts;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client._VG.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class GlobalSocksWindow : BaseLoadoutWindow
{
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    private LoadoutGroupContainer? _groupContainer;
    private readonly HumanoidCharacterProfile _profile;
    private readonly ICommonSession? _session;
    private readonly IDependencyCollection _collection;
    private const string GroupId = "ADTSocks";

    public GlobalSocksWindow(HumanoidCharacterProfile profile, RoleLoadout globalLoadout, IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        _profile = profile;
        _collection = collection;
        
        var playerManager = collection.Resolve<IPlayerManager>();
        _session = playerManager.LocalSession;
        if (_session == null) return;

        var protoMan = collection.Resolve<IPrototypeManager>();
        if (!protoMan.TryIndex<LoadoutGroupPrototype>(GroupId, out var groupProto)) return;

        _groupContainer = new LoadoutGroupContainer(profile, globalLoadout, groupProto, _session, collection, false);
        GroupsContainer.AddChild(_groupContainer);

        _groupContainer.OnLoadoutPressed += args => OnLoadoutPressed?.Invoke(GroupId, args);
        _groupContainer.OnLoadoutUnpressed += args => OnLoadoutUnpressed?.Invoke(GroupId, args);
    }

    public void RefreshLoadouts(RoleLoadout globalLoadout)
    {
        if (_session == null || _groupContainer == null) return;
        _groupContainer.RefreshLoadouts(_profile, globalLoadout, _session, _collection, false);
    }
}