using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._VG.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VGCharacterSetupWindowGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        private HumanoidProfileEditor _profileEditor;
        private Direction _previewRotation = Direction.South;
        private EntityUid? _previewDummy;

        private bool _fadingPreview;
        private float _fadeTimer;
        private const float FadeDuration = 0.3f;
        private EntityUid? _oldPreviewDummy;
        private EntityUid? _newPreviewDummy;

        // Tracks last "heavy" state to detect when a full respawn is needed
        private string _lastPreviewSpecies = "";
        private bool _lastPreviewShowClothes = true;

        // Deduplication: process at most one appearance update per frame
        private bool _appearanceUpdatePending;
        private bool _fullRespawnPending;

        private bool _pdaPreviewActive;
        private PanelContainer? _pdaScreen;

        private bool _fadingPda;
        private float _fadePdaTimer;
        private const float FadePdaDuration = 0.2f;

        private bool _fadingPdaImage;
        private float _fadePdaImageTimer;
        private const float FadePdaImageDuration = 0.3f;
        private StyleBox? _oldPdaStyle;
        private StyleBox? _newPdaStyle;

        private List<(string path, TextureButton button, PanelContainer highlight)> _wallpaperButtons = new();
        private string? _currentWallpaperPath;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public VGCharacterSetupWindowGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _profileEditor = profileEditor;

            if (_profileEditor.TabContainer != null)
            {
                _profileEditor.TabContainer.Orphan();
                EditorContainer.AddChild(_profileEditor.TabContainer);
            }

            var originalNameEdit = _profileEditor.NameEdit;
            if (originalNameEdit != null)
            {
                originalNameEdit.Orphan();
                NameEditContainer.AddChild(originalNameEdit);
            }

            InsertOriginalButton(_profileEditor.SaveButton, SaveButton);
            InsertOriginalButton(_profileEditor.ResetButton, ResetButton);
            ImportButton.OnPressed += _ => _profileEditor.TriggerImport();
            ExportButton.OnPressed += _ => _profileEditor.TriggerExport();

            StatsButton.OnPressed += _ =>
            {
                new PlaytimeStatsWindow().OpenCentered();
            };
            AdminRemarksButton.OnPressed += _ =>
            {
                _consoleHost.ExecuteCommand("adminremarks");
            };

            InsertOriginalButton(_profileEditor.NameRandomize, NameRandomize);
            InsertOriginalButton(_profileEditor.RandomizeEverythingButton, RandomizeEverythingButton);

            if (_profileEditor.NameRandomize != null)
                _profileEditor.NameRandomize.OnPressed += _ =>
                {
                    UpdatePreviewInstant();
                };
            if (_profileEditor.RandomizeEverythingButton != null)
                _profileEditor.RandomizeEverythingButton.OnPressed += _ =>
                {
                    UpdatePreviewInstant();
                };

            _profileEditor.ProfileChanged += OnProfileChangedLight;

            if (_profileEditor.ShowClothes != null)
                _profileEditor.ShowClothes.OnToggled += _ => UpdatePreviewInstant();

            var warningMsg = new FormattedMessage();
            warningMsg.AddMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");
            WarningLabel.SetMessage(warningMsg);

            CreateCharacterButton.OnPressed += _ =>
            {
                var existingSlots = _preferencesManager.Preferences?.Characters.Keys.ToList() ?? new List<int>();
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());

                int newSlot = -1;
                var characters = _preferencesManager.Preferences?.Characters;
                if (characters != null)
                {
                    for (int i = 0; i < _preferencesManager.Settings!.MaxCharacterSlots; i++)
                    {
                        if (!existingSlots.Contains(i) && characters.ContainsKey(i))
                        {
                            newSlot = i;
                            break;
                        }
                    }
                }
                if (newSlot < 0) newSlot = characters?.Keys.LastOrDefault() ?? 0;

                _preferencesManager.SelectCharacter(newSlot);
                SelectCharacter?.Invoke(newSlot);
                UpdateProfileEditor();
                UpdatePreview();
                ReloadCharacterList();
                UpdatePdaWallpaperSelection();
            };

            ReloadCharacterList();
            CharacterSelector.OnItemSelected += args =>
            {
                var slot = (int)args.Id;
                _preferencesManager.SelectCharacter(slot);
                SelectCharacter?.Invoke(slot);
                UpdateProfileEditor();
                UpdatePreview();
                ReloadCharacterList();
                UpdatePdaWallpaperSelection();
            };

            DeleteCharacterButton.OnPressed += _ =>
            {
                var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;
                if (selectedSlot == null) return;
                if (_preferencesManager.Preferences!.Characters.Count <= 1) return;

                var slots = _preferencesManager.Preferences.Characters.Keys.OrderBy(k => k).ToList();
                int currentIndex = slots.IndexOf(selectedSlot.Value);
                int newSlot = -1;
                if (currentIndex > 0)
                    newSlot = slots[currentIndex - 1];
                else if (currentIndex < slots.Count - 1)
                    newSlot = slots[currentIndex + 1];
                else
                    return;

                _preferencesManager.SelectCharacter(newSlot);
                DeleteCharacter?.Invoke(selectedSlot.Value);
                UpdateProfileEditor();
                UpdatePreview();
                ReloadCharacterList();
                UpdatePdaWallpaperSelection();
            };

            RotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation switch
                {
                    Direction.South => Direction.West,
                    Direction.West  => Direction.North,
                    Direction.North => Direction.East,
                    Direction.East  => Direction.South,
                    _ => Direction.South
                };
                PreviewSprite.OverrideDirection = _previewRotation;
            };
            RotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation switch
                {
                    Direction.South => Direction.East,
                    Direction.East  => Direction.North,
                    Direction.North => Direction.West,
                    Direction.West  => Direction.South,
                    _ => Direction.South
                };
                PreviewSprite.OverrideDirection = _previewRotation;
            };

            if (_resourceCache.TryGetResource<RSIResource>("/Textures/_VG/Objects/Devices/pda.rsi", out var pdaRsi))
            {
                if (pdaRsi.RSI.TryGetState("pda", out var state))
                {
                    PdaWallpaperButton.TextureNormal = state.Frame0;
                }
            }

            InitPdaWallpaper();
            UpdatePdaWallpaperSelection();
        }

        private void InitPdaWallpaper()
        {
            var wallpapers = new[]
            {
                ("/Textures/_VG/PDA/Wallpapers/space1.png", Loc.GetString("pda-wallpaper-space")),
                ("/Textures/_VG/PDA/Wallpapers/space2.png", Loc.GetString("pda-wallpaper-space2")),
                ("/Textures/_VG/PDA/Wallpapers/blackhole.png", Loc.GetString("pda-wallpaper-blackhole")),
                ("/Textures/_VG/PDA/Wallpapers/forest.png", Loc.GetString("pda-wallpaper-forest")),
                ("/Textures/_VG/PDA/Wallpapers/smile.png", Loc.GetString("pda-wallpaper-smile")),
            };

            foreach (var (path, name) in wallpapers)
            {
                var highlight = new PanelContainer
                {
                    SetSize = new Vector2(84, 134),
                    Margin = new Thickness(0, 0, 4, 0),
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.Transparent,
                        ContentMarginLeftOverride = 2,
                        ContentMarginTopOverride = 2,
                        ContentMarginRightOverride = 2,
                        ContentMarginBottomOverride = 2
                    }
                };

                var textureButton = new TextureButton
                {
                    SetSize = new Vector2(95, 130),
                    ToolTip = name,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center
                };

                if (_resourceCache.TryGetResource<TextureResource>(new ResPath(path), out var texRes))
                {
                    textureButton.TextureNormal = texRes;
                }

                textureButton.OnPressed += _ =>
                {
                    SelectWallpaper(path);
                };

                highlight.AddChild(textureButton);
                PdaWallpaperButtons.AddChild(highlight);
                _wallpaperButtons.Add((path, textureButton, highlight));
            }

            PdaWallpaperButton.OnPressed += _ =>
            {
                TogglePdaPreview();
            };
        }

        private void SelectWallpaper(string path)
        {
            if (_currentWallpaperPath == path)
            {
                _currentWallpaperPath = null;
            }
            else
            {
                _currentWallpaperPath = path;
            }

            _profileEditor.SetPdaWallpaperPath(_currentWallpaperPath);
            UpdatePdaPreviewImage(_currentWallpaperPath, true);
            UpdateWallpaperButtonHighlight();
        }

        private void UpdateWallpaperButtonHighlight()
        {
            foreach (var (path, _, highlight) in _wallpaperButtons)
            {
                if (path == _currentWallpaperPath)
                {
                    highlight.PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.FromHex("#505050"),
                        ContentMarginLeftOverride = 2,
                        ContentMarginTopOverride = 2,
                        ContentMarginRightOverride = 2,
                        ContentMarginBottomOverride = 2
                    };
                }
                else
                {
                    highlight.PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.Transparent,
                        ContentMarginLeftOverride = 2,
                        ContentMarginTopOverride = 2,
                        ContentMarginRightOverride = 2,
                        ContentMarginBottomOverride = 2
                    };
                }
            }
        }

        private void TogglePdaPreview()
        {
            bool newActive = !_pdaPreviewActive;
            _pdaPreviewActive = newActive;
            PdaWallpaperPanel.Visible = newActive;

            if (newActive)
            {
                CharacterPreviewContent.Visible = false;
                CharacterPreviewContent.ModulateSelfOverride = Color.White;

                if (PdaPreviewContent.ChildCount == 0)
                    BuildPdaPreviewFrame();
                PdaPreviewContent.Visible = true;
                PdaPreviewContent.ModulateSelfOverride = Color.White.WithAlpha(0f);
                UpdatePdaPreviewImage(_currentWallpaperPath, false);
            }

            _fadingPda = true;
            _fadePdaTimer = 0f;
        }

        private void BuildPdaPreviewFrame()
        {
            PdaPreviewContent.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#717059"),
                ContentMarginLeftOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginBottomOverride = 6
            };

            var innerFrame = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#000000"),
                    ContentMarginLeftOverride = 4,
                    ContentMarginTopOverride = 4,
                    ContentMarginRightOverride = 4,
                    ContentMarginBottomOverride = 4
                }
            };

            _pdaScreen = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#25252a") }
            };

            innerFrame.AddChild(_pdaScreen);
            PdaPreviewContent.AddChild(innerFrame);
        }

        private void UpdatePdaPreviewImage(string? path, bool animate = true)
        {
            if (_pdaScreen == null)
                return;

            StyleBox newStyle;
            if (string.IsNullOrEmpty(path))
            {
                newStyle = new StyleBoxFlat { BackgroundColor = Color.FromHex("#25252a") };
            }
            else if (_resourceCache.TryGetResource<TextureResource>(new ResPath(path), out var textureResource))
            {
                var styleBox = new StyleBoxTexture
                {
                    Texture = textureResource.Texture,
                };
                styleBox.SetPatchMargin(StyleBox.Margin.All, 0);
                newStyle = styleBox;
            }
            else
            {
                newStyle = new StyleBoxFlat { BackgroundColor = Color.FromHex("#25252a") };
            }

            if (!_pdaPreviewActive || !animate)
            {
                _pdaScreen.PanelOverride = newStyle;
                _pdaScreen.ModulateSelfOverride = Color.White;
                return;
            }

            if (_fadingPdaImage)
            {
                _pdaScreen.PanelOverride = _newPdaStyle ?? newStyle;
                _fadingPdaImage = false;
            }

            _oldPdaStyle = _pdaScreen.PanelOverride;
            _newPdaStyle = newStyle;
            _fadingPdaImage = true;
            _fadePdaImageTimer = 0f;
            _pdaScreen.PanelOverride = _oldPdaStyle;
        }

        public void UpdatePdaWallpaperSelection()
        {
            _currentWallpaperPath = _profileEditor.Profile?.PdaWallpaperPath;
            UpdateWallpaperButtonHighlight();
            if (_pdaPreviewActive)
                UpdatePdaPreviewImage(_currentWallpaperPath, false);
        }

        private void InsertOriginalButton(Button? originalButton, Button ourButton)
        {
            if (originalButton == null || ourButton?.Parent is not BoxContainer container) return;
            originalButton.Orphan();
            container.AddChild(originalButton);
            originalButton.SetPositionInParent(ourButton.GetPositionInParent());
            ourButton.Visible = false;
        }

        public void ReloadCharacterPickers() => ReloadCharacterList();

        private void ReloadCharacterList()
        {
            CharacterSelector.Clear();
            if (!_preferencesManager.ServerDataLoaded || _preferencesManager.Preferences == null) return;

            var characters = _preferencesManager.Preferences.Characters.OrderBy(kv => kv.Key).ToList();
            foreach (var (slot, character) in characters)
            {
                CharacterSelector.AddItem(character.Name, slot);
                if (slot == _preferencesManager.Preferences.SelectedCharacterIndex)
                    CharacterSelector.SelectId(slot);
            }
        }

        public void UpdateProfileEditor()
        {
            var selected = _preferencesManager.Preferences?.SelectedCharacter;
            if (selected is HumanoidCharacterProfile humanoid)
                _profileEditor.SetProfile(humanoid, _preferencesManager.Preferences?.SelectedCharacterIndex);
            UpdatePreview();
            UpdatePdaWallpaperSelection();
        }

        public void UpdatePreview()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            bool clothes = _profileEditor.ShowClothes?.Pressed ?? true;
            _lastPreviewSpecies = profile.Species;
            _lastPreviewShowClothes = clothes;

            var controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            var newDummy = controller.LoadProfileEntity(profile, null, clothes);

            if (_previewDummy == null)
            {
                _previewDummy = newDummy;
                PreviewSprite.SetEntity(_previewDummy.Value);
                PreviewSprite.ModulateSelfOverride = Color.White;
                return;
            }

            if (_fadingPreview)
            {
                if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy.Value);
                if (_newPreviewDummy != null) _entManager.DeleteEntity(_newPreviewDummy.Value);
            }

            _oldPreviewDummy = _previewDummy;
            _newPreviewDummy = newDummy;
            _fadingPreview = true;
            _fadeTimer = 0f;

            PreviewSprite.SetEntity(_newPreviewDummy.Value);
            PreviewSprite.ModulateSelfOverride = Color.White.WithAlpha(0f);
        }

        // Called on appearance-only changes (markings, skin color, eye color) — no entity respawn.
        // Deduplicates: schedules at most one update per frame.
        private void OnProfileChangedLight()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            bool showClothes = _profileEditor.ShowClothes?.Pressed ?? true;

            // Species or clothes changed → need full respawn
            if (profile.Species != _lastPreviewSpecies || showClothes != _lastPreviewShowClothes)
            {
                _fullRespawnPending = true;
                _appearanceUpdatePending = false;
            }
            else
            {
                _appearanceUpdatePending = true;
            }
        }

        public void UpdatePreviewInstant()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            _fullRespawnPending = false;
            _appearanceUpdatePending = false;

            bool clothes = _profileEditor.ShowClothes?.Pressed ?? true;
            _lastPreviewSpecies = profile.Species;
            _lastPreviewShowClothes = clothes;

            if (_previewDummy != null) _entManager.DeleteEntity(_previewDummy.Value);
            if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy.Value);
            if (_newPreviewDummy != null) _entManager.DeleteEntity(_newPreviewDummy.Value);
            _fadingPreview = false;
            _oldPreviewDummy = null;
            _newPreviewDummy = null;

            var controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _previewDummy = controller.LoadProfileEntity(profile, null, clothes);
            PreviewSprite.SetEntity(_previewDummy.Value);
            PreviewSprite.ModulateSelfOverride = Color.White;
        }

        // Updates the existing preview entity in-place — no respawn, no lag.
        private void UpdatePreviewAppearance()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            if (_previewDummy == null || !_entManager.EntityExists(_previewDummy.Value))
            {
                UpdatePreviewInstant();
                return;
            }

            _entManager.System<HumanoidAppearanceSystem>().LoadProfile(_previewDummy.Value, profile);
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            // Process deferred preview updates — at most once per frame
            if (_fullRespawnPending)
            {
                _fullRespawnPending = false;
                _appearanceUpdatePending = false;
                UpdatePreviewInstant();
            }
            else if (_appearanceUpdatePending)
            {
                _appearanceUpdatePending = false;
                UpdatePreviewAppearance();
            }

            if (_fadingPreview)
            {
                _fadeTimer += args.DeltaSeconds;
                float progress = Math.Min(_fadeTimer / FadeDuration, 1f);
                PreviewSprite.ModulateSelfOverride = Color.White.WithAlpha(progress);
                if (progress >= 1f)
                {
                    _fadingPreview = false;
                    if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy);
                    _oldPreviewDummy = null;
                    _previewDummy = _newPreviewDummy;
                    _newPreviewDummy = null;
                }
            }

            if (_fadingPda)
            {
                _fadePdaTimer += args.DeltaSeconds;
                float progress = Math.Min(_fadePdaTimer / FadePdaDuration, 1f);

                if (_pdaPreviewActive)
                {
                    PdaPreviewContent.ModulateSelfOverride = Color.White.WithAlpha(progress);
                }
                else
                {
                    PdaPreviewContent.ModulateSelfOverride = Color.White.WithAlpha(1f - progress);
                }

                if (progress >= 1f)
                {
                    _fadingPda = false;
                    if (!_pdaPreviewActive)
                    {
                        PdaPreviewContent.Visible = false;
                        PdaPreviewContent.ModulateSelfOverride = Color.White;
                        CharacterPreviewContent.Visible = true;
                        CharacterPreviewContent.ModulateSelfOverride = Color.White;
                    }
                    else
                    {
                        PdaPreviewContent.ModulateSelfOverride = Color.White;
                    }
                }
            }

            if (_fadingPdaImage)
            {
                _fadePdaImageTimer += args.DeltaSeconds;
                float progress = Math.Min(_fadePdaImageTimer / FadePdaImageDuration, 1f);

                if (progress < 0.5f)
                {
                    float alpha = 1f - progress * 2f;
                    if (_pdaScreen != null)
                        _pdaScreen.ModulateSelfOverride = Color.White.WithAlpha(alpha);
                }
                else
                {
                    if (_newPdaStyle != null && _pdaScreen != null && _pdaScreen.PanelOverride != _newPdaStyle)
                    {
                        _pdaScreen.PanelOverride = _newPdaStyle;
                        _pdaScreen.ModulateSelfOverride = Color.White.WithAlpha(0f);
                    }
                    float alpha = (progress - 0.5f) * 2f;
                    if (_pdaScreen != null)
                        _pdaScreen.ModulateSelfOverride = Color.White.WithAlpha(alpha);
                }

                if (progress >= 1f)
                {
                    _fadingPdaImage = false;
                    if (_pdaScreen != null)
                        _pdaScreen.ModulateSelfOverride = Color.White;
                    _oldPdaStyle = null;
                    _newPdaStyle = null;
                }
            }
        }

        public void UpdateNameField()
        {
            // Поле имени теперь оригинальное, обновляется автоматически
        }

        public HumanoidProfileEditor GetProfileEditor()
        {
            return _profileEditor;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy.Value);
            if (_newPreviewDummy != null) _entManager.DeleteEntity(_newPreviewDummy.Value);
            if (_previewDummy != null) _entManager.DeleteEntity(_previewDummy.Value);
        }
    }
}