using System.ComponentModel;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VG.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class VGCharacterSetupWindow : DefaultWindow
{
    public event Action<CancelEventArgs>? ClosingRequested;

    public VGCharacterSetupWindow(Control content)
    {
        RobustXamlLoader.Load(this);
        Contents.AddChild(content);
        SetSize = new Vector2(1400, 860);
    }

    public override void Close()
    {
        var args = new CancelEventArgs();
        ClosingRequested?.Invoke(args);
        if (args.Cancel)
            return;
        base.Close();
    }
}