using System;
using System.Linq;
using System.Numerics;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._VG.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VGCharacterSetupWindowGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        private HumanoidProfileEditor _profileEditor;
        private Direction _previewRotation = Direction.South;
        private EntityUid? _previewDummy;

        // VG-Tweak Start: Анимация превью
        private bool _fadingPreview;
        private float _fadeTimer;
        private const float FadeDuration = 0.3f;
        private EntityUid? _oldPreviewDummy;
        private EntityUid? _newPreviewDummy;
        // VG-Tweak End

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public VGCharacterSetupWindowGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _profileEditor = profileEditor;

            if (_profileEditor.TabContainer != null)
            {
                _profileEditor.TabContainer.Orphan();
                EditorContainer.AddChild(_profileEditor.TabContainer);
            }

            InsertOriginalButton(_profileEditor.SaveButton, SaveButton);
            InsertOriginalButton(_profileEditor.ResetButton, ResetButton);
            InsertOriginalButton(_profileEditor.ImportButton, ImportButton);
            InsertOriginalButton(_profileEditor.ExportButton, ExportButton);

            InsertOriginalButton(_profileEditor.NameRandomize, NameRandomize);
            InsertOriginalButton(_profileEditor.RandomizeEverythingButton, RandomizeEverythingButton);

            if (_profileEditor.NameRandomize != null)
                _profileEditor.NameRandomize.OnPressed += _ =>
                {
                    UpdatePreview();
                    UpdateNameField();
                };
            if (_profileEditor.RandomizeEverythingButton != null)
                _profileEditor.RandomizeEverythingButton.OnPressed += _ =>
                {
                    UpdatePreview();
                    UpdateNameField();
                };

            var warningMsg = new FormattedMessage();
            warningMsg.AddMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");
            WarningLabel.SetMessage(warningMsg);

            if (_profileEditor.NameEdit != null)
            {
                NameEdit.Text = _profileEditor.NameEdit.Text ?? "";
                _profileEditor.NameEdit.OnTextChanged += args =>
                {
                    if (NameEdit.Text != args.Text)
                        NameEdit.Text = args.Text;
                };
                NameEdit.OnTextChanged += args =>
                {
                    if (_profileEditor.NameEdit.Text != args.Text)
                        _profileEditor.NameEdit.Text = args.Text;
                };
            }

            CreateCharacterButton.OnPressed += _ =>
            {
                var existingSlots = _preferencesManager.Preferences?.Characters.Keys.ToList() ?? new List<int>();
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());

                int newSlot = -1;
                var characters = _preferencesManager.Preferences?.Characters;
                if (characters != null)
                {
                    for (int i = 0; i < _preferencesManager.Settings!.MaxCharacterSlots; i++)
                    {
                        if (!existingSlots.Contains(i) && characters.ContainsKey(i))
                        {
                            newSlot = i;
                            break;
                        }
                    }
                }
                if (newSlot < 0) newSlot = characters?.Keys.LastOrDefault() ?? 0;

                _preferencesManager.SelectCharacter(newSlot);
                SelectCharacter?.Invoke(newSlot);
                UpdateProfileEditor();
                UpdatePreview();
                UpdateNameField();
                ReloadCharacterList();
            };

            ReloadCharacterList();
            CharacterSelector.OnItemSelected += args =>
            {
                var slot = (int)args.Id;
                _preferencesManager.SelectCharacter(slot);
                SelectCharacter?.Invoke(slot);
                UpdateProfileEditor();
                UpdatePreview();
                UpdateNameField();
                ReloadCharacterList();
            };

            DeleteCharacterButton.OnPressed += _ =>
            {
                var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;
                if (selectedSlot == null) return;
                if (_preferencesManager.Preferences!.Characters.Count <= 1) return;

                var slots = _preferencesManager.Preferences.Characters.Keys.OrderBy(k => k).ToList();
                int currentIndex = slots.IndexOf(selectedSlot.Value);
                int newSlot = -1;
                if (currentIndex > 0)
                    newSlot = slots[currentIndex - 1];
                else if (currentIndex < slots.Count - 1)
                    newSlot = slots[currentIndex + 1];
                else
                    return;

                _preferencesManager.SelectCharacter(newSlot);
                DeleteCharacter?.Invoke(selectedSlot.Value);
                UpdateProfileEditor();
                UpdatePreview();
                UpdateNameField();
                ReloadCharacterList();
            };

            RotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation switch
                {
                    Direction.South => Direction.West,
                    Direction.West  => Direction.North,
                    Direction.North => Direction.East,
                    Direction.East  => Direction.South,
                    _ => Direction.South
                };
                PreviewSprite.OverrideDirection = _previewRotation;
            };
            RotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation switch
                {
                    Direction.South => Direction.East,
                    Direction.East  => Direction.North,
                    Direction.North => Direction.West,
                    Direction.West  => Direction.South,
                    _ => Direction.South
                };
                PreviewSprite.OverrideDirection = _previewRotation;
            };
        }

        private void InsertOriginalButton(Button? originalButton, Button ourButton)
        {
            if (originalButton == null || ourButton?.Parent is not BoxContainer container) return;
            originalButton.Orphan();
            container.AddChild(originalButton);
            originalButton.SetPositionInParent(ourButton.GetPositionInParent());
            ourButton.Visible = false;
        }

        public void ReloadCharacterPickers() => ReloadCharacterList();

        private void ReloadCharacterList()
        {
            CharacterSelector.Clear();
            if (!_preferencesManager.ServerDataLoaded || _preferencesManager.Preferences == null) return;

            var characters = _preferencesManager.Preferences.Characters.OrderBy(kv => kv.Key).ToList();
            foreach (var (slot, character) in characters)
            {
                CharacterSelector.AddItem(character.Name, slot);
                if (slot == _preferencesManager.Preferences.SelectedCharacterIndex)
                    CharacterSelector.SelectId(slot);
            }
        }

        public void UpdateProfileEditor()
        {
            var selected = _preferencesManager.Preferences?.SelectedCharacter;
            if (selected is HumanoidCharacterProfile humanoid)
                _profileEditor.SetProfile(humanoid, _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        // VG-Tweak Start: Анимированное обновление превью
        public void UpdatePreview()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            var controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            var newDummy = controller.LoadProfileEntity(profile, null, true);

            if (_previewDummy == null)
            {
                // Первая загрузка – без анимации
                _previewDummy = newDummy;
                PreviewSprite.SetEntity(_previewDummy.Value);
                PreviewSprite.ModulateSelfOverride = Color.White;
                return;
            }

            // Запускаем fade-in для нового спрайта
            if (_fadingPreview)
            {
                // Если анимация уже идёт, удаляем незавершённые dummy
                if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy);
                if (_newPreviewDummy != null) _entManager.DeleteEntity(_newPreviewDummy);
            }

            _oldPreviewDummy = _previewDummy;
            _newPreviewDummy = newDummy;
            _fadingPreview = true;
            _fadeTimer = 0f;

            // Подменяем спрайт на новый с нулевой альфой
            PreviewSprite.SetEntity(_newPreviewDummy.Value);
            PreviewSprite.ModulateSelfOverride = Color.White.WithAlpha(0f);
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            if (!_fadingPreview) return;

            _fadeTimer += args.DeltaSeconds;
            float progress = Math.Min(_fadeTimer / FadeDuration, 1f);

            PreviewSprite.ModulateSelfOverride = Color.White.WithAlpha(progress);

            if (progress >= 1f)
            {
                _fadingPreview = false;
                // Удаляем старый dummy
                if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy);
                _oldPreviewDummy = null;
                // Обновляем текущий dummy
                _previewDummy = _newPreviewDummy;
                _newPreviewDummy = null;
            }
        }
        // VG-Tweak End

        public void UpdateNameField()
        {
            if (_profileEditor.NameEdit != null)
                NameEdit.Text = _profileEditor.NameEdit.Text ?? "";
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy);
            if (_newPreviewDummy != null) _entManager.DeleteEntity(_newPreviewDummy);
            if (_previewDummy != null) _entManager.DeleteEntity(_previewDummy);
        }
    }
}