using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client._VG.Lobby.UI.Loadouts;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._VG.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VGCharacterSetupWindowGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        private HumanoidProfileEditor _profileEditor;
        private Direction _previewRotation = Direction.South;
        private EntityUid? _previewDummy;

        private bool _fadingPreview;
        private float _fadeTimer;
        private const float FadeDuration = 0.3f;
        private EntityUid? _oldPreviewDummy;
        private EntityUid? _newPreviewDummy;

        private string _lastPreviewSpecies = "";
        private bool _lastPreviewShowClothes = true;

        private bool _appearanceUpdatePending;
        private bool _fullRespawnPending;

        private bool _pdaPreviewActive;
        private PanelContainer? _pdaScreen;

        private bool _fadingPda;
        private float _fadePdaTimer;
        private const float FadePdaDuration = 0.2f;

        private bool _fadingPdaImage;
        private float _fadePdaImageTimer;
        private const float FadePdaImageDuration = 0.3f;
        private StyleBox? _oldPdaStyle;
        private StyleBox? _newPdaStyle;

        private List<(string path, TextureButton button, PanelContainer highlight)> _wallpaperButtons = new();
        private string? _currentWallpaperPath;

        // VG-Tweak Start: Поля для глобальных лодаутов (три отдельных окна)
        private GlobalBottomWindow? _globalBottomWindow;
        private GlobalTopWindow? _globalTopWindow;
        private GlobalSocksWindow? _globalSocksWindow;
        // VG-Tweak End

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public VGCharacterSetupWindowGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _profileEditor = profileEditor;

            if (_profileEditor.TabContainer != null)
            {
                _profileEditor.TabContainer.Orphan();
                EditorContainer.AddChild(_profileEditor.TabContainer);
            }

            var originalNameEdit = _profileEditor.NameEdit;
            if (originalNameEdit != null)
            {
                originalNameEdit.Orphan();
                NameEditContainer.AddChild(originalNameEdit);
            }

            InsertOriginalButton(_profileEditor.SaveButton, SaveButton);
            InsertOriginalButton(_profileEditor.ResetButton, ResetButton);
            ImportButton.OnPressed += _ => _profileEditor.TriggerImport();
            ExportButton.OnPressed += _ => _profileEditor.TriggerExport();

            StatsButton.OnPressed += _ => new PlaytimeStatsWindow().OpenCentered();
            AdminRemarksButton.OnPressed += _ => _consoleHost.ExecuteCommand("adminremarks");

            InsertOriginalButton(_profileEditor.NameRandomize, NameRandomize);
            InsertOriginalButton(_profileEditor.RandomizeEverythingButton, RandomizeEverythingButton);

            if (_profileEditor.NameRandomize != null)
                _profileEditor.NameRandomize.OnPressed += _ => UpdatePreviewInstant();
            if (_profileEditor.RandomizeEverythingButton != null)
                _profileEditor.RandomizeEverythingButton.OnPressed += _ => UpdatePreviewInstant();

            _profileEditor.ProfileChanged += OnProfileChangedLight;

            if (_profileEditor.ShowClothes != null)
                _profileEditor.ShowClothes.OnToggled += _ => UpdatePreviewInstant();

            // VG-Tweak: Кнопка переключения одежды в панели превью
            ClothesToggleButton.OnPressed += _ =>
            {
                if (_profileEditor.ShowClothes != null)
                {
                    _profileEditor.ShowClothes.Pressed = !_profileEditor.ShowClothes.Pressed;
                    UpdatePreviewInstant();
                }
            };

            var warningMsg = new FormattedMessage();
            warningMsg.AddMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");
            WarningLabel.SetMessage(warningMsg);

            CreateCharacterButton.OnPressed += _ =>
            {
                var existingSlots = _preferencesManager.Preferences?.Characters.Keys.ToList() ?? new List<int>();
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());

                int newSlot = -1;
                var characters = _preferencesManager.Preferences?.Characters;
                if (characters != null)
                {
                    for (int i = 0; i < _preferencesManager.Settings!.MaxCharacterSlots; i++)
                    {
                        if (!existingSlots.Contains(i) && characters.ContainsKey(i))
                        {
                            newSlot = i;
                            break;
                        }
                    }
                }
                if (newSlot < 0) newSlot = characters?.Keys.LastOrDefault() ?? 0;

                _preferencesManager.SelectCharacter(newSlot);
                SelectCharacter?.Invoke(newSlot);
                UpdateProfileEditor();
                UpdatePreview();
                ReloadCharacterList();
                UpdatePdaWallpaperSelection();
            };

            ReloadCharacterList();
            CharacterSelector.OnItemSelected += args =>
            {
                var slot = (int)args.Id;
                _preferencesManager.SelectCharacter(slot);
                SelectCharacter?.Invoke(slot);
                UpdateProfileEditor();
                UpdatePreview();
                ReloadCharacterList();
                UpdatePdaWallpaperSelection();
            };

            DeleteCharacterButton.OnPressed += _ =>
            {
                var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;
                if (selectedSlot == null) return;
                if (_preferencesManager.Preferences!.Characters.Count <= 1) return;

                var slots = _preferencesManager.Preferences.Characters.Keys.OrderBy(k => k).ToList();
                int currentIndex = slots.IndexOf(selectedSlot.Value);
                int newSlot = -1;
                if (currentIndex > 0) newSlot = slots[currentIndex - 1];
                else if (currentIndex < slots.Count - 1) newSlot = slots[currentIndex + 1];
                else return;

                _preferencesManager.SelectCharacter(newSlot);
                DeleteCharacter?.Invoke(selectedSlot.Value);
                UpdateProfileEditor();
                UpdatePreview();
                ReloadCharacterList();
                UpdatePdaWallpaperSelection();
            };

            RotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation switch
                {
                    Direction.South => Direction.West,
                    Direction.West  => Direction.North,
                    Direction.North => Direction.East,
                    Direction.East  => Direction.South,
                    _ => Direction.South
                };
                PreviewSprite.OverrideDirection = _previewRotation;
            };
            RotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation switch
                {
                    Direction.South => Direction.East,
                    Direction.East  => Direction.North,
                    Direction.North => Direction.West,
                    Direction.West  => Direction.South,
                    _ => Direction.South
                };
                PreviewSprite.OverrideDirection = _previewRotation;
            };

            if (_resourceCache.TryGetResource<RSIResource>("/Textures/_VG/Objects/Devices/pda.rsi", out var pdaRsi))
            {
                if (pdaRsi.RSI.TryGetState("pda", out var state))
                    PdaWallpaperButton.TextureNormal = state.Frame0;
            }

            InitPdaWallpaper();
            UpdatePdaWallpaperSelection();

            // VG-Tweak Start: Инициализация кнопок глобальных лодаутов (три отдельных окна)
            GlobalBottomButton.OnPressed += _ => OpenGlobalBottomWindow();
            GlobalTopButton.OnPressed += _ => OpenGlobalTopWindow();
            GlobalSocksButton.OnPressed += _ => OpenGlobalSocksWindow();
            // VG-Tweak End
        }

        private void InitPdaWallpaper()
        {
            var wallpapers = new[]
            {
                ("/Textures/_VG/PDA/Wallpapers/space1.png", Loc.GetString("pda-wallpaper-space")),
                ("/Textures/_VG/PDA/Wallpapers/space2.png", Loc.GetString("pda-wallpaper-space2")),
                ("/Textures/_VG/PDA/Wallpapers/blackhole.png", Loc.GetString("pda-wallpaper-blackhole")),
                ("/Textures/_VG/PDA/Wallpapers/forest.png", Loc.GetString("pda-wallpaper-forest")),
                ("/Textures/_VG/PDA/Wallpapers/smile.png", Loc.GetString("pda-wallpaper-smile")),
            };

            foreach (var (path, name) in wallpapers)
            {
                var highlight = new PanelContainer
                {
                    SetSize = new Vector2(84, 134),
                    Margin = new Thickness(0, 0, 4, 0),
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.Transparent,
                        ContentMarginLeftOverride = 2,
                        ContentMarginTopOverride = 2,
                        ContentMarginRightOverride = 2,
                        ContentMarginBottomOverride = 2
                    }
                };

                var textureButton = new TextureButton
                {
                    SetSize = new Vector2(95, 130),
                    ToolTip = name,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center
                };

                if (_resourceCache.TryGetResource<TextureResource>(new ResPath(path), out var texRes))
                    textureButton.TextureNormal = texRes;

                textureButton.OnPressed += _ => SelectWallpaper(path);

                highlight.AddChild(textureButton);
                PdaWallpaperButtons.AddChild(highlight);
                _wallpaperButtons.Add((path, textureButton, highlight));
            }

            PdaWallpaperButton.OnPressed += _ => TogglePdaPreview();

            // VG-Tweak Start: Загрузка иконок для кнопок глобальных лодаутов
            // Загрузка иконки для носков
            if (_resourceCache.TryGetResource<RSIResource>("/Textures/ADT/Clothing/Underwear/Socks/socksknee.rsi", out var socksRsi))
            {
                if (socksRsi.RSI.TryGetState("icon", out var socksState))
                    GlobalSocksButton.TextureNormal = socksState.Frame0;
            }
            
            // Загрузка иконки для нижнего белья
            if (_resourceCache.TryGetResource<RSIResource>("/Textures/ADT/Clothing/Underwear/Bottom/boxers.rsi", out var bottomRsi))
            {
                if (bottomRsi.RSI.TryGetState("icon", out var bottomState))
                    GlobalBottomButton.TextureNormal = bottomState.Frame0;
            }
            
            // Загрузка иконки для футболки
            if (_resourceCache.TryGetResource<RSIResource>("/Textures/ADT/Clothing/Underwear/Top/t_shirt.rsi", out var topRsi))
            {
                if (topRsi.RSI.TryGetState("icon", out var topState))
                    GlobalTopButton.TextureNormal = topState.Frame0;
            }
            // VG-Tweak End
        }

        private void SelectWallpaper(string path)
        {
            _currentWallpaperPath = _currentWallpaperPath == path ? null : path;
            _profileEditor.SetPdaWallpaperPath(_currentWallpaperPath);
            UpdatePdaPreviewImage(_currentWallpaperPath, true);
            UpdateWallpaperButtonHighlight();
        }

        private void UpdateWallpaperButtonHighlight()
        {
            foreach (var (path, _, highlight) in _wallpaperButtons)
            {
                highlight.PanelOverride = path == _currentWallpaperPath
                    ? new StyleBoxFlat { BackgroundColor = Color.FromHex("#505050"), ContentMarginLeftOverride = 2, ContentMarginTopOverride = 2, ContentMarginRightOverride = 2, ContentMarginBottomOverride = 2 }
                    : new StyleBoxFlat { BackgroundColor = Color.Transparent, ContentMarginLeftOverride = 2, ContentMarginTopOverride = 2, ContentMarginRightOverride = 2, ContentMarginBottomOverride = 2 };
            }
        }

        private void TogglePdaPreview()
        {
            _pdaPreviewActive = !_pdaPreviewActive;
            PdaWallpaperPanel.Visible = _pdaPreviewActive;

            if (_pdaPreviewActive)
            {
                CharacterPreviewContent.Visible = false;
                CharacterPreviewContent.ModulateSelfOverride = Color.White;

                if (PdaPreviewContent.ChildCount == 0)
                    BuildPdaPreviewFrame();
                PdaPreviewContent.Visible = true;
                PdaPreviewContent.ModulateSelfOverride = Color.White.WithAlpha(0f);
                UpdatePdaPreviewImage(_currentWallpaperPath, false);
            }

            _fadingPda = true;
            _fadePdaTimer = 0f;
        }

        private void BuildPdaPreviewFrame()
        {
            PdaPreviewContent.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#717059"),
                ContentMarginLeftOverride = 6, ContentMarginTopOverride = 6,
                ContentMarginRightOverride = 6, ContentMarginBottomOverride = 6
            };

            var innerFrame = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#000000"),
                    ContentMarginLeftOverride = 4, ContentMarginTopOverride = 4,
                    ContentMarginRightOverride = 4, ContentMarginBottomOverride = 4
                }
            };

            _pdaScreen = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#25252a") }
            };

            innerFrame.AddChild(_pdaScreen);
            PdaPreviewContent.AddChild(innerFrame);
        }

        private void UpdatePdaPreviewImage(string? path, bool animate = true)
        {
            if (_pdaScreen == null) return;

            StyleBox newStyle;
            if (string.IsNullOrEmpty(path))
                newStyle = new StyleBoxFlat { BackgroundColor = Color.FromHex("#25252a") };
            else if (_resourceCache.TryGetResource<TextureResource>(new ResPath(path), out var textureResource))
            {
                newStyle = new StyleBoxTexture { Texture = textureResource.Texture };
                ((StyleBoxTexture)newStyle).SetPatchMargin(StyleBox.Margin.All, 0);
            }
            else
                newStyle = new StyleBoxFlat { BackgroundColor = Color.FromHex("#25252a") };

            if (!_pdaPreviewActive || !animate)
            {
                _pdaScreen.PanelOverride = newStyle;
                _pdaScreen.ModulateSelfOverride = Color.White;
                return;
            }

            if (_fadingPdaImage)
            {
                _pdaScreen.PanelOverride = _newPdaStyle ?? newStyle;
                _fadingPdaImage = false;
            }

            _oldPdaStyle = _pdaScreen.PanelOverride;
            _newPdaStyle = newStyle;
            _fadingPdaImage = true;
            _fadePdaImageTimer = 0f;
            _pdaScreen.PanelOverride = _oldPdaStyle;
        }

        public void UpdatePdaWallpaperSelection()
        {
            _currentWallpaperPath = _profileEditor.Profile?.PdaWallpaperPath;
            UpdateWallpaperButtonHighlight();
            if (_pdaPreviewActive)
                UpdatePdaPreviewImage(_currentWallpaperPath, false);
        }

        private void InsertOriginalButton(Button? originalButton, Button ourButton)
        {
            if (originalButton == null || ourButton?.Parent is not BoxContainer container) return;
            originalButton.Orphan();
            container.AddChild(originalButton);
            originalButton.SetPositionInParent(ourButton.GetPositionInParent());
            ourButton.Visible = false;
        }

        public void ReloadCharacterPickers() => ReloadCharacterList();

        private void ReloadCharacterList()
        {
            CharacterSelector.Clear();
            if (!_preferencesManager.ServerDataLoaded || _preferencesManager.Preferences == null) return;

            var characters = _preferencesManager.Preferences.Characters.OrderBy(kv => kv.Key).ToList();
            foreach (var (slot, character) in characters)
            {
                CharacterSelector.AddItem(character.Name, slot);
                if (slot == _preferencesManager.Preferences.SelectedCharacterIndex)
                    CharacterSelector.SelectId(slot);
            }
        }

        public void UpdateProfileEditor()
        {
            var selected = _preferencesManager.Preferences?.SelectedCharacter;
            if (selected is HumanoidCharacterProfile humanoid)
                _profileEditor.SetProfile(humanoid, _preferencesManager.Preferences?.SelectedCharacterIndex);
            UpdatePreview();
            UpdatePdaWallpaperSelection();
        }

        public void UpdatePreview()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            bool clothes = _profileEditor.ShowClothes?.Pressed ?? true;
            _lastPreviewSpecies = profile.Species;
            _lastPreviewShowClothes = clothes;
            ClothesToggleButton.Pressed = !clothes;

            var controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            var newDummy = controller.LoadProfileEntity(profile, null, clothes);

            if (_previewDummy == null)
            {
                _previewDummy = newDummy;
                PreviewSprite.SetEntity(_previewDummy.Value);
                PreviewSprite.ModulateSelfOverride = Color.White;
                return;
            }

            if (_fadingPreview)
            {
                if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy.Value);
                if (_newPreviewDummy != null) _entManager.DeleteEntity(_newPreviewDummy.Value);
            }

            _oldPreviewDummy = _previewDummy;
            _newPreviewDummy = newDummy;
            _fadingPreview = true;
            _fadeTimer = 0f;

            PreviewSprite.SetEntity(_newPreviewDummy.Value);
            PreviewSprite.ModulateSelfOverride = Color.White.WithAlpha(0f);
        }

        private void OnProfileChangedLight()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            bool showClothes = _profileEditor.ShowClothes?.Pressed ?? true;

            if (profile.Species != _lastPreviewSpecies || showClothes != _lastPreviewShowClothes)
            {
                _fullRespawnPending = true;
                _appearanceUpdatePending = false;
            }
            else
            {
                _appearanceUpdatePending = true;
            }
        }

        public void UpdatePreviewInstant()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            _fullRespawnPending = false;
            _appearanceUpdatePending = false;

            bool clothes = _profileEditor.ShowClothes?.Pressed ?? true;
            _lastPreviewSpecies = profile.Species;
            _lastPreviewShowClothes = clothes;
            ClothesToggleButton.Pressed = !clothes;

            if (_previewDummy != null) _entManager.DeleteEntity(_previewDummy.Value);
            if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy.Value);
            if (_newPreviewDummy != null) _entManager.DeleteEntity(_newPreviewDummy.Value);
            _fadingPreview = false;
            _oldPreviewDummy = null;
            _newPreviewDummy = null;

            var controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _previewDummy = controller.LoadProfileEntity(profile, null, clothes);
            PreviewSprite.SetEntity(_previewDummy.Value);
            PreviewSprite.ModulateSelfOverride = Color.White;
        }

        private void UpdatePreviewAppearance()
        {
            var profile = _profileEditor.Profile;
            if (profile == null) return;

            if (_previewDummy == null || !_entManager.EntityExists(_previewDummy.Value))
            {
                UpdatePreviewInstant();
                return;
            }

            _entManager.System<HumanoidAppearanceSystem>().LoadProfile(_previewDummy.Value, profile);
        }

        // VG-Tweak Start: Открытие окна глобального лодаута (нижнее бельё) с автоматическим закрытием других окон
        private void OpenGlobalBottomWindow()
        {
            // Закрываем другие окна перед открытием нового
            _globalTopWindow?.Dispose();
            _globalTopWindow = null;
            _globalSocksWindow?.Dispose();
            _globalSocksWindow = null;

            // Если окно уже открыто - просто закрываем его (toggle behaviour)
            if (_globalBottomWindow != null && _globalBottomWindow.IsOpen)
            {
                _globalBottomWindow.Dispose();
                _globalBottomWindow = null;
                return;
            }

            var profile = _profileEditor.Profile;
            if (profile == null) return;

            var protoMan = _prototypeManager;
            if (!protoMan.HasIndex<RoleLoadoutPrototype>("GlobalLoadout")) return;

            var globalLoadout = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);

            _globalBottomWindow?.Dispose();
            _globalBottomWindow = new GlobalBottomWindow(profile, globalLoadout, IoCManager.Instance!);

            _globalBottomWindow.OnLoadoutPressed += (group, proto) =>
            {
                var newGlobal = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);
                newGlobal.AddLoadout(group, proto, protoMan);
                profile = profile.WithLoadout(newGlobal);
                _profileEditor.SetProfile(profile, _profileEditor.CharacterSlot);
                _globalBottomWindow?.RefreshLoadouts(newGlobal);
            };

            _globalBottomWindow.OnLoadoutUnpressed += (group, proto) =>
            {
                var newGlobal = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);
                newGlobal.RemoveLoadout(group, proto, protoMan);
                profile = profile.WithLoadout(newGlobal);
                _profileEditor.SetProfile(profile, _profileEditor.CharacterSlot);
                _globalBottomWindow?.RefreshLoadouts(newGlobal);
            };

            _globalBottomWindow.OnClose += () => _globalBottomWindow = null;
            _globalBottomWindow.OpenCentered();
        }

        private void OpenGlobalTopWindow()
        {
            _globalBottomWindow?.Dispose();
            _globalBottomWindow = null;
            _globalSocksWindow?.Dispose();
            _globalSocksWindow = null;

            if (_globalTopWindow != null && _globalTopWindow.IsOpen)
            {
                _globalTopWindow.Dispose();
                _globalTopWindow = null;
                return;
            }

            var profile = _profileEditor.Profile;
            if (profile == null) return;

            var protoMan = _prototypeManager;
            if (!protoMan.HasIndex<RoleLoadoutPrototype>("GlobalLoadout")) return;

            var globalLoadout = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);

            _globalTopWindow?.Dispose();
            _globalTopWindow = new GlobalTopWindow(profile, globalLoadout, IoCManager.Instance!);

            _globalTopWindow.OnLoadoutPressed += (group, proto) =>
            {
                var newGlobal = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);
                newGlobal.AddLoadout(group, proto, protoMan);
                profile = profile.WithLoadout(newGlobal);
                _profileEditor.SetProfile(profile, _profileEditor.CharacterSlot);
                _globalTopWindow?.RefreshLoadouts(newGlobal);
            };

            _globalTopWindow.OnLoadoutUnpressed += (group, proto) =>
            {
                var newGlobal = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);
                newGlobal.RemoveLoadout(group, proto, protoMan);
                profile = profile.WithLoadout(newGlobal);
                _profileEditor.SetProfile(profile, _profileEditor.CharacterSlot);
                _globalTopWindow?.RefreshLoadouts(newGlobal);
            };

            _globalTopWindow.OnClose += () => _globalTopWindow = null;
            _globalTopWindow.OpenCentered();
        }

        private void OpenGlobalSocksWindow()
        {
            _globalBottomWindow?.Dispose();
            _globalBottomWindow = null;
            _globalTopWindow?.Dispose();
            _globalTopWindow = null;

            if (_globalSocksWindow != null && _globalSocksWindow.IsOpen)
            {
                _globalSocksWindow.Dispose();
                _globalSocksWindow = null;
                return;
            }

            var profile = _profileEditor.Profile;
            if (profile == null) return;

            var protoMan = _prototypeManager;
            if (!protoMan.HasIndex<RoleLoadoutPrototype>("GlobalLoadout")) return;

            var globalLoadout = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);

            _globalSocksWindow?.Dispose();
            _globalSocksWindow = new GlobalSocksWindow(profile, globalLoadout, IoCManager.Instance!);

            _globalSocksWindow.OnLoadoutPressed += (group, proto) =>
            {
                var newGlobal = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);
                newGlobal.AddLoadout(group, proto, protoMan);
                profile = profile.WithLoadout(newGlobal);
                _profileEditor.SetProfile(profile, _profileEditor.CharacterSlot);
                _globalSocksWindow?.RefreshLoadouts(newGlobal);
            };

            _globalSocksWindow.OnLoadoutUnpressed += (group, proto) =>
            {
                var newGlobal = profile.GetLoadoutOrDefault("GlobalLoadout", null, protoMan);
                newGlobal.RemoveLoadout(group, proto, protoMan);
                profile = profile.WithLoadout(newGlobal);
                _profileEditor.SetProfile(profile, _profileEditor.CharacterSlot);
                _globalSocksWindow?.RefreshLoadouts(newGlobal);
            };

            _globalSocksWindow.OnClose += () => _globalSocksWindow = null;
            _globalSocksWindow.OpenCentered();
        }
        // VG-Tweak End

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (_fullRespawnPending)
            {
                _fullRespawnPending = false;
                _appearanceUpdatePending = false;
                UpdatePreviewInstant();
            }
            else if (_appearanceUpdatePending)
            {
                _appearanceUpdatePending = false;
                UpdatePreviewAppearance();
            }

            if (_fadingPreview)
            {
                _fadeTimer += args.DeltaSeconds;
                float progress = Math.Min(_fadeTimer / FadeDuration, 1f);
                PreviewSprite.ModulateSelfOverride = Color.White.WithAlpha(progress);
                if (progress >= 1f)
                {
                    _fadingPreview = false;
                    if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy);
                    _oldPreviewDummy = null;
                    _previewDummy = _newPreviewDummy;
                    _newPreviewDummy = null;
                }
            }

            if (_fadingPda)
            {
                _fadePdaTimer += args.DeltaSeconds;
                float progress = Math.Min(_fadePdaTimer / FadePdaDuration, 1f);
                PdaPreviewContent.ModulateSelfOverride = _pdaPreviewActive
                    ? Color.White.WithAlpha(progress)
                    : Color.White.WithAlpha(1f - progress);

                if (progress >= 1f)
                {
                    _fadingPda = false;
                    if (!_pdaPreviewActive)
                    {
                        PdaPreviewContent.Visible = false;
                        PdaPreviewContent.ModulateSelfOverride = Color.White;
                        CharacterPreviewContent.Visible = true;
                        CharacterPreviewContent.ModulateSelfOverride = Color.White;
                    }
                    else
                    {
                        PdaPreviewContent.ModulateSelfOverride = Color.White;
                    }
                }
            }

            if (_fadingPdaImage)
            {
                _fadePdaImageTimer += args.DeltaSeconds;
                float progress = Math.Min(_fadePdaImageTimer / FadePdaImageDuration, 1f);

                if (progress < 0.5f)
                {
                    float alpha = 1f - progress * 2f;
                    if (_pdaScreen != null)
                        _pdaScreen.ModulateSelfOverride = Color.White.WithAlpha(alpha);
                }
                else
                {
                    if (_newPdaStyle != null && _pdaScreen != null && _pdaScreen.PanelOverride != _newPdaStyle)
                    {
                        _pdaScreen.PanelOverride = _newPdaStyle;
                        _pdaScreen.ModulateSelfOverride = Color.White.WithAlpha(0f);
                    }
                    float alpha = (progress - 0.5f) * 2f;
                    if (_pdaScreen != null)
                        _pdaScreen.ModulateSelfOverride = Color.White.WithAlpha(alpha);
                }

                if (progress >= 1f)
                {
                    _fadingPdaImage = false;
                    if (_pdaScreen != null)
                        _pdaScreen.ModulateSelfOverride = Color.White;
                    _oldPdaStyle = null;
                    _newPdaStyle = null;
                }
            }
        }

        public void UpdateNameField()
        {
            // Поле имени теперь оригинальное, обновляется автоматически
        }

        public HumanoidProfileEditor GetProfileEditor()
        {
            return _profileEditor;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_oldPreviewDummy != null) _entManager.DeleteEntity(_oldPreviewDummy.Value);
            if (_newPreviewDummy != null) _entManager.DeleteEntity(_newPreviewDummy.Value);
            if (_previewDummy != null) _entManager.DeleteEntity(_previewDummy.Value);
            _globalBottomWindow?.Dispose();
            _globalTopWindow?.Dispose();
            _globalSocksWindow?.Dispose();
        }
    }
}