using Content.Client.UserInterface.Controls;
using Content.Shared._VG.Event;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._VG.Event;

[GenerateTypedNameReferences]
public sealed partial class BeaconConsoleWindow : FancyWindow
{
    private BoxContainer? _authScreen;
    private BoxContainer? _lockoutScreen;
    private BoxContainer? _mainContent;
    private LineEdit? _passwordField;
    private Button? _authButton;
    private Button? _activateButton;
    private Label? _statusLabel;
    private PanelContainer? _radarDisabledOverlay;
    private Content.Client.Shuttles.UI.ShuttleNavControl? _radarScreen;
    private PanelContainer? _radarContainer;

    public Action<string>? OnAttemptAuth;
    public Action? OnActivatePressed;

    public BeaconConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        
        _authScreen = this.FindControl<BoxContainer>("AuthScreen");
        _lockoutScreen = this.FindControl<BoxContainer>("LockoutScreen");
        _mainContent = this.FindControl<BoxContainer>("MainContent");
        _passwordField = this.FindControl<LineEdit>("PasswordField");
        _authButton = this.FindControl<Button>("AuthButton");
        _activateButton = this.FindControl<Button>("ActivateButton");
        _statusLabel = this.FindControl<Label>("StatusLabel");
        _radarDisabledOverlay = this.FindControl<PanelContainer>("RadarDisabledOverlay");
        _radarScreen = this.FindControl<Content.Client.Shuttles.UI.ShuttleNavControl>("RadarScreen");
        _radarContainer = this.FindControl<PanelContainer>("RadarContainer");
        
        if (_authButton != null)
            _authButton.OnPressed += _ => OnAttemptAuth?.Invoke(_passwordField?.Text ?? string.Empty);
        if (_activateButton != null)
            _activateButton.OnPressed += _ => OnActivatePressed?.Invoke();
    }

    public void UpdateState(BeaconConsoleBoundUserInterfaceState state, NavInterfaceState? navState)
    {
        if (_authScreen == null || _lockoutScreen == null || _mainContent == null) return;

        _authScreen.Visible = !state.IsEnabled && !state.IsLocked;
        _lockoutScreen.Visible = state.IsLocked;
        _mainContent.Visible = state.IsEnabled && !state.IsLocked;

        if (!state.IsEnabled) return;

        _radarDisabledOverlay!.Visible = !state.IsBeaconActive;
        _radarScreen!.Visible = state.IsBeaconActive;
        _activateButton!.Disabled = state.IsBeaconActive;

        if (_statusLabel != null)
        {
            _statusLabel.Text = state.IsBeaconActive ? "АКТИВЕН" : "ГОТОВ";
            _statusLabel.FontColorOverride = state.IsBeaconActive ? Color.Green : Color.Yellow;
        }

        if (state.IsBeaconActive && navState != null)
        {
            _radarScreen?.UpdateState(navState);
        }
    }
}