using Content.Client.Xenonids.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects; // Для EntityUid

namespace Content.Client._VG.Surgery;

// Убрали GenerateTypedNameReferences, если в XAML нет элементов с Name="something"
public sealed partial class SurgeryStepButton : XenoChoiceControl
{
    public EntityUid Step { get; set; }

    public SurgeryStepButton()
    {
        RobustXamlLoader.Load(this);
    }
}