using Content.Client.Pinpointer.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;
using System.Numerics;

namespace Content.Client._VG.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NavigatorUiFragment : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public NavMapControl? NavMap;
    private EntityUid? _owner;
    private const int NavMapHeight = 570;
    private const int NavMapWidth = 540;

    public NavigatorUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        
        // Включаем обрезку содержимого для родительского контейнера
        RectClipContent = true;
    }

    public void Setup(EntityUid? owner)
    {
        _owner = owner;
        NavMap = new NavMapControl();
        NavMap.Owner = owner;
        NavMap.HorizontalExpand = true;
        NavMap.VerticalExpand = true;
        
        // Ограничиваем размер карты
        NavMap.MinSize = new Vector2(NavMapWidth, NavMapHeight);
        NavMap.MaxSize = new Vector2(NavMapWidth, NavMapHeight);
        NavMap.SetSize = new Vector2(NavMapWidth, NavMapHeight);
        
        // Включаем обрезку для самой карты
        NavMap.RectClipContent = true;

        NavMapContainer.AddChild(NavMap);
    }

    public void UpdateState(EntityUid? mapUid, string stationName)
    {
        StationNameLabel.Text = stationName;

        if (NavMap != null && mapUid != null)
        {
            NavMap.MapUid = mapUid;
            NavMap.ForceNavMapUpdate();
        }

        UpdateOwnerPosition();
    }

    private void UpdateOwnerPosition()
    {
        if (NavMap == null || _owner == null || !_entManager.EntityExists(_owner.Value))
            return;

        var transformSystem = _entManager.System<SharedTransformSystem>();

        var ownerEntityCoords = new EntityCoordinates(_owner.Value, Vector2.Zero);

        NavMap.TrackedCoordinates.Clear();
        NavMap.TrackedCoordinates[ownerEntityCoords] = (true, Color.Red);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateOwnerPosition();
    }
}