name: Update Contrib and Patreons in credits

on:
  workflow_dispatch:  # Только ручной запуск
  # schedule:
  #   - cron: 0 0 * * 0  # Отключаем автоматический

jobs:
  get_credits:
    runs-on: ubuntu-latest
    # Отключаем для форка
    if: github.repository == 'VG-SpaceStation14/VGSpaceStation14'

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: master

      - name: Get Contributors
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: Tools/dump_github_contributors.ps1 > Resources/Credits/GitHub.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update Credits
          title: Update Credits
          body: This is an automated Pull Request. This PR updates the github contributors in the credits section.
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: automated/credits-update